{ **************************************************************************
    FreePascal/Delphi DirectX 12 Header Files

    Copyright (C) 2013-2025 Norbert Sonnleitner

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
************************************************************************** }

{ **************************************************************************
   Additional Copyright (C) for this modul:

   Copyright (c) Microsoft Corporation.  All rights reserved.
   This file is automatically generated.  Please do not edit it directly.

   This unit consists of the following header files
   File name: D2D1Effects.h
   Header version: 10.0.26100.6584

  ************************************************************************** }

unit DX12.D2D1Effects;

{$IFDEF FPC}
{$mode delphiunicode}{$H+}
{$modeswitch ADVANCEDRECORDS}
{$modeswitch TypeHelpers}
{$ENDIF}

interface

uses
    Classes, SysUtils;

    {$Z4}

const
    // Built in effect CLSIDs
    CLSID_D2D12DAffineTransform: TGUID = '{6AA97485-6354-4CFC-908C-E4A74F62C96C}';
    CLSID_D2D13DPerspectiveTransform: TGUID = '{C2844D0B-3D86-46E7-85BA-526C9240F3FB}';
    CLSID_D2D13DTransform: TGUID = '{E8467B04-EC61-4B8A-B5DE-D4D73DEBEA5A}';
    CLSID_D2D1ArithmeticComposite: TGUID = '{FC151437-049A-4784-A24A-F1C4DAF20987}';
    CLSID_D2D1Atlas: TGUID = '{913E2BE4-FDCF-4FE2-A5F0-2454F14FF408}';
    CLSID_D2D1BitmapSource: TGUID = '{5FB6C24D-C6DD-4231-9404-50F4D5C3252D}';
    CLSID_D2D1Blend: TGUID = '{81C5B77B-13F8-4CDD-AD20-C890547AC65D}';
    CLSID_D2D1Border: TGUID = '{2A2D49C0-4ACF-43C7-8C6A-7C4A27874D27}';
    CLSID_D2D1Brightness: TGUID = '{8CEA8D1E-77B0-4986-B3B9-2F0C0EAE7887}';
    CLSID_D2D1ColorManagement: TGUID = '{1A28524C-FDD6-4AA4-AE8F-837EB8267B37}';
    CLSID_D2D1ColorMatrix: TGUID = '{921F03D6-641C-47DF-852D-B4BB6153AE11}';
    CLSID_D2D1Composite: TGUID = '{48FC9F51-F6AC-48F1-8B58-3B28AC46F76D}';
    CLSID_D2D1ConvolveMatrix: TGUID = '{407F8C08-5533-4331-A341-23CC3877843E}';
    CLSID_D2D1Crop: TGUID = '{E23F7110-0E9A-4324-AF47-6A2C0C46F35B}';
    CLSID_D2D1DirectionalBlur: TGUID = '{174319A6-58E9-49B2-BB63-CAF2C811A3DB}';
    CLSID_D2D1DiscreteTransfer: TGUID = '{90866FCD-488E-454B-AF06-E5041B66C36C}';
    CLSID_D2D1DisplacementMap: TGUID = '{EDC48364-0417-4111-9450-43845FA9F890}';
    CLSID_D2D1DistantDiffuse: TGUID = '{3E7EFD62-A32D-46D4-A83C-5278889AC954}';
    CLSID_D2D1DistantSpecular: TGUID = '{428C1EE5-77B8-4450-8AB5-72219C21ABDA}';
    CLSID_D2D1DpiCompensation: TGUID = '{6C26C5C7-34E0-46FC-9CFD-E5823706E228}';
    CLSID_D2D1Flood: TGUID = '{61C23C20-AE69-4D8E-94CF-50078DF638F2}';
    CLSID_D2D1GammaTransfer: TGUID = '{409444C4-C419-41A0-B0C1-8CD0C0A18E42}';
    CLSID_D2D1GaussianBlur: TGUID = '{1FEB6D69-2FE6-4AC9-8C58-1D7F93E7A6A5}';
    CLSID_D2D1Scale: TGUID = '{9DAF9369-3846-4D0E-A44E-0C607934A5D7}';
    CLSID_D2D1Histogram: TGUID = '{881DB7D0-F7EE-4D4D-A6D2-4697ACC66EE8}';
    CLSID_D2D1HueRotation: TGUID = '{0F4458EC-4B32-491B-9E85-BD73F44D3EB6}';
    CLSID_D2D1LinearTransfer: TGUID = '{AD47C8FD-63EF-4ACC-9B51-67979C036C06}';
    CLSID_D2D1LuminanceToAlpha: TGUID = '{41251AB7-0BEB-46F8-9DA7-59E93FCCE5DE}';
    CLSID_D2D1Morphology: TGUID = '{EAE6C40D-626A-4C2D-BFCB-391001ABE202}';
    CLSID_D2D1OpacityMetadata: TGUID = '{6C53006A-4450-4199-AA5B-AD1656FECE5E}';
    CLSID_D2D1PointDiffuse: TGUID = '{B9E303C3-C08C-4F91-8B7B-38656BC48C20}';
    CLSID_D2D1PointSpecular: TGUID = '{09C3CA26-3AE2-4F09-9EBC-ED3865D53F22}';
    CLSID_D2D1Premultiply: TGUID = '{06EAB419-DEED-4018-80D2-3E1D471ADEB2}';
    CLSID_D2D1Saturation: TGUID = '{5CB2D9CF-327D-459F-A0CE-40C0B2086BF7}';
    CLSID_D2D1Shadow: TGUID = '{C67EA361-1863-4E69-89DB-695D3E9A5B6B}';
    CLSID_D2D1SpotDiffuse: TGUID = '{818A1105-7932-44F4-AA86-08AE7B2F2C93}';
    CLSID_D2D1SpotSpecular: TGUID = '{EDAE421E-7654-4A37-9DB8-71ACC1BEB3C1}';
    CLSID_D2D1TableTransfer: TGUID = '{5BF818C3-5E43-48CB-B631-868396D6A1D4}';
    CLSID_D2D1Tile: TGUID = '{B0784138-3B76-4BC5-B13B-0FA2AD02659F}';
    CLSID_D2D1Turbulence: TGUID = '{CF2BB6AE-889A-4AD7-BA29-A2FD732C9FC9}';
    CLSID_D2D1UnPremultiply: TGUID = '{FB9AC489-AD8D-41ED-9999-BB6347D110F7}';


type
    /// Specifies how the Crop effect handles the crop rectangle falling on fractional
    /// pixel coordinates.
    TD2D1_BORDER_MODE = (
        D2D1_BORDER_MODE_SOFT = 0,
        D2D1_BORDER_MODE_HARD = 1,
        D2D1_BORDER_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_BORDER_MODE = ^TD2D1_BORDER_MODE;



    /// Specifies the color channel the Displacement map effect extracts the intensity
    /// from and uses it to spatially displace the image in the X or Y direction.
    TD2D1_CHANNEL_SELECTOR = (
        D2D1_CHANNEL_SELECTOR_R = 0,
        D2D1_CHANNEL_SELECTOR_G = 1,
        D2D1_CHANNEL_SELECTOR_B = 2,
        D2D1_CHANNEL_SELECTOR_A = 3,
        D2D1_CHANNEL_SELECTOR_FORCE_DWORD = longint($ffffffff));

    PD2D1_CHANNEL_SELECTOR = ^TD2D1_CHANNEL_SELECTOR;



    /// Speficies whether a flip and/or rotation operation should be performed by the
    /// Bitmap source effect
    TD2D1_BITMAPSOURCE_ORIENTATION = (
        D2D1_BITMAPSOURCE_ORIENTATION_DEFAULT = 1,
        D2D1_BITMAPSOURCE_ORIENTATION_FLIP_HORIZONTAL = 2,
        D2D1_BITMAPSOURCE_ORIENTATION_ROTATE_CLOCKWISE180 = 3,
        D2D1_BITMAPSOURCE_ORIENTATION_ROTATE_CLOCKWISE180_FLIP_HORIZONTAL = 4,
        D2D1_BITMAPSOURCE_ORIENTATION_ROTATE_CLOCKWISE270_FLIP_HORIZONTAL = 5,
        D2D1_BITMAPSOURCE_ORIENTATION_ROTATE_CLOCKWISE90 = 6,
        D2D1_BITMAPSOURCE_ORIENTATION_ROTATE_CLOCKWISE90_FLIP_HORIZONTAL = 7,
        D2D1_BITMAPSOURCE_ORIENTATION_ROTATE_CLOCKWISE270 = 8,
        D2D1_BITMAPSOURCE_ORIENTATION_FORCE_DWORD = longint($ffffffff));

    PD2D1_BITMAPSOURCE_ORIENTATION = ^TD2D1_BITMAPSOURCE_ORIENTATION;



    /// The enumeration of the Gaussian Blur effect's top level properties.
    /// Effect description: Applies a gaussian blur to a bitmap with the specified blur
    /// radius and angle.
    TD2D1_GAUSSIANBLUR_PROP = (
        /// Property Name: "StandardDeviation"
        /// Property Type: FLOAT
        D2D1_GAUSSIANBLUR_PROP_STANDARD_DEVIATION = 0,
        /// Property Name: "Optimization"
        /// Property Type: D2D1_GAUSSIANBLUR_OPTIMIZATION
        D2D1_GAUSSIANBLUR_PROP_OPTIMIZATION = 1,
        /// Property Name: "BorderMode"
        /// Property Type: D2D1_BORDER_MODE
        D2D1_GAUSSIANBLUR_PROP_BORDER_MODE = 2,
        D2D1_GAUSSIANBLUR_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_GAUSSIANBLUR_PROP = ^TD2D1_GAUSSIANBLUR_PROP;




    TD2D1_GAUSSIANBLUR_OPTIMIZATION = (
        D2D1_GAUSSIANBLUR_OPTIMIZATION_SPEED = 0,
        D2D1_GAUSSIANBLUR_OPTIMIZATION_BALANCED = 1,
        D2D1_GAUSSIANBLUR_OPTIMIZATION_QUALITY = 2,
        D2D1_GAUSSIANBLUR_OPTIMIZATION_FORCE_DWORD = $ffffffff);

    PD2D1_GAUSSIANBLUR_OPTIMIZATION = ^TD2D1_GAUSSIANBLUR_OPTIMIZATION;



    /// The enumeration of the Directional Blur effect's top level properties.
    /// Effect description: Applies a directional blur to a bitmap with the specified
    /// blur radius and angle.
    TD2D1_DIRECTIONALBLUR_PROP = (
        /// Property Name: "StandardDeviation"
        /// Property Type: FLOAT
        D2D1_DIRECTIONALBLUR_PROP_STANDARD_DEVIATION = 0,
        /// Property Name: "Angle"
        /// Property Type: FLOAT
        D2D1_DIRECTIONALBLUR_PROP_ANGLE = 1,
        /// Property Name: "Optimization"
        /// Property Type: D2D1_DIRECTIONALBLUR_OPTIMIZATION
        D2D1_DIRECTIONALBLUR_PROP_OPTIMIZATION = 2,
        /// Property Name: "BorderMode"
        /// Property Type: D2D1_BORDER_MODE
        D2D1_DIRECTIONALBLUR_PROP_BORDER_MODE = 3,
        D2D1_DIRECTIONALBLUR_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_DIRECTIONALBLUR_PROP = ^TD2D1_DIRECTIONALBLUR_PROP;




    TD2D1_DIRECTIONALBLUR_OPTIMIZATION = (
        D2D1_DIRECTIONALBLUR_OPTIMIZATION_SPEED = 0,
        D2D1_DIRECTIONALBLUR_OPTIMIZATION_BALANCED = 1,
        D2D1_DIRECTIONALBLUR_OPTIMIZATION_QUALITY = 2,
        D2D1_DIRECTIONALBLUR_OPTIMIZATION_FORCE_DWORD = $ffffffff);

    PD2D1_DIRECTIONALBLUR_OPTIMIZATION = ^TD2D1_DIRECTIONALBLUR_OPTIMIZATION;



    /// The enumeration of the Shadow effect's top level properties.
    /// Effect description: Applies a shadow to a bitmap based on its alpha channel.
    TD2D1_SHADOW_PROP = (
        /// Property Name: "BlurStandardDeviation"
        /// Property Type: FLOAT
        D2D1_SHADOW_PROP_BLUR_STANDARD_DEVIATION = 0,
        /// Property Name: "Color"
        /// Property Type: D2D1_VECTOR_4F
        D2D1_SHADOW_PROP_COLOR = 1,
        /// Property Name: "Optimization"
        /// Property Type: D2D1_SHADOW_OPTIMIZATION
        D2D1_SHADOW_PROP_OPTIMIZATION = 2,
        D2D1_SHADOW_PROP_FORCE_DWORD = longint($ffffffff));

    PD2D1_SHADOW_PROP = ^TD2D1_SHADOW_PROP;




    TD2D1_SHADOW_OPTIMIZATION = (
        D2D1_SHADOW_OPTIMIZATION_SPEED = 0,
        D2D1_SHADOW_OPTIMIZATION_BALANCED = 1,
        D2D1_SHADOW_OPTIMIZATION_QUALITY = 2,
        D2D1_SHADOW_OPTIMIZATION_FORCE_DWORD = longint($ffffffff));

    PD2D1_SHADOW_OPTIMIZATION = ^TD2D1_SHADOW_OPTIMIZATION;



    /// The enumeration of the Blend effect's top level properties.
    /// Effect description: Blends a foreground and background using a pre-defined blend
    /// mode.
    TD2D1_BLEND_PROP = (
        /// Property Name: "Mode"
        /// Property Type: D2D1_BLEND_MODE
        D2D1_BLEND_PROP_MODE = 0,
        D2D1_BLEND_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_BLEND_PROP = ^TD2D1_BLEND_PROP;




    TD2D1_BLEND_MODE = (
        D2D1_BLEND_MODE_MULTIPLY = 0,
        D2D1_BLEND_MODE_SCREEN = 1,
        D2D1_BLEND_MODE_DARKEN = 2,
        D2D1_BLEND_MODE_LIGHTEN = 3,
        D2D1_BLEND_MODE_DISSOLVE = 4,
        D2D1_BLEND_MODE_COLOR_BURN = 5,
        D2D1_BLEND_MODE_LINEAR_BURN = 6,
        D2D1_BLEND_MODE_DARKER_COLOR = 7,
        D2D1_BLEND_MODE_LIGHTER_COLOR = 8,
        D2D1_BLEND_MODE_COLOR_DODGE = 9,
        D2D1_BLEND_MODE_LINEAR_DODGE = 10,
        D2D1_BLEND_MODE_OVERLAY = 11,
        D2D1_BLEND_MODE_SOFT_LIGHT = 12,
        D2D1_BLEND_MODE_HARD_LIGHT = 13,
        D2D1_BLEND_MODE_VIVID_LIGHT = 14,
        D2D1_BLEND_MODE_LINEAR_LIGHT = 15,
        D2D1_BLEND_MODE_PIN_LIGHT = 16,
        D2D1_BLEND_MODE_HARD_MIX = 17,
        D2D1_BLEND_MODE_DIFFERENCE = 18,
        D2D1_BLEND_MODE_EXCLUSION = 19,
        D2D1_BLEND_MODE_HUE = 20,
        D2D1_BLEND_MODE_SATURATION = 21,
        D2D1_BLEND_MODE_COLOR = 22,
        D2D1_BLEND_MODE_LUMINOSITY = 23,
        D2D1_BLEND_MODE_SUBTRACT = 24,
        D2D1_BLEND_MODE_DIVISION = 25,
        D2D1_BLEND_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_BLEND_MODE = ^TD2D1_BLEND_MODE;



    /// The enumeration of the Saturation effect's top level properties.
    /// Effect description: Alters the saturation of the bitmap based on the user
    /// specified saturation value.
    TD2D1_SATURATION_PROP = (
        /// Property Name: "Saturation"
        /// Property Type: FLOAT
        D2D1_SATURATION_PROP_SATURATION = 0,
        D2D1_SATURATION_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_SATURATION_PROP = ^TD2D1_SATURATION_PROP;




    /// The enumeration of the Hue Rotation effect's top level properties.
    /// Effect description: Changes the Hue of a bitmap based on a user specified Hue
    /// Rotation angle.
    TD2D1_HUEROTATION_PROP = (
        /// Property Name: "Angle"
        /// Property Type: FLOAT
        D2D1_HUEROTATION_PROP_ANGLE = 0,
        D2D1_HUEROTATION_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_HUEROTATION_PROP = ^TD2D1_HUEROTATION_PROP;


    /// The enumeration of the Color Matrix effect's top level properties.
    /// Effect description: Applies a user specified color matrix to each channel of the
    /// input bitmap.
    TD2D1_COLORMATRIX_PROP = (
        /// Property Name: "ColorMatrix"
        /// Property Type: D2D1_MATRIX_5X4_F
        D2D1_COLORMATRIX_PROP_COLOR_MATRIX = 0,
        /// Property Name: "AlphaMode"
        /// Property Type: D2D1_COLORMATRIX_ALPHA_MODE
        D2D1_COLORMATRIX_PROP_ALPHA_MODE = 1,
        /// Property Name: "ClampOutput"
        /// Property Type: BOOL
        D2D1_COLORMATRIX_PROP_CLAMP_OUTPUT = 2,
        D2D1_COLORMATRIX_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_COLORMATRIX_PROP = ^TD2D1_COLORMATRIX_PROP;




    TD2D1_COLORMATRIX_ALPHA_MODE = (
        D2D1_COLORMATRIX_ALPHA_MODE_PREMULTIPLIED = 1,
        D2D1_COLORMATRIX_ALPHA_MODE_STRAIGHT = 2,
        D2D1_COLORMATRIX_ALPHA_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_COLORMATRIX_ALPHA_MODE = ^TD2D1_COLORMATRIX_ALPHA_MODE;



    /// The enumeration of the Bitmap Source effect's top level properties.
    /// Effect description: Provides an image source.
    TD2D1_BITMAPSOURCE_PROP = (
        /// Property Name: "WicBitmapSource"
        /// Property Type: IUnknown *
        D2D1_BITMAPSOURCE_PROP_WIC_BITMAP_SOURCE = 0,
        /// Property Name: "Scale"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_BITMAPSOURCE_PROP_SCALE = 1,
        /// Property Name: "InterpolationMode"
        /// Property Type: D2D1_BITMAPSOURCE_INTERPOLATION_MODE
        D2D1_BITMAPSOURCE_PROP_INTERPOLATION_MODE = 2,
        /// Property Name: "EnableDPICorrection"
        /// Property Type: BOOL
        D2D1_BITMAPSOURCE_PROP_ENABLE_DPI_CORRECTION = 3,
        /// Property Name: "AlphaMode"
        /// Property Type: D2D1_BITMAPSOURCE_ALPHA_MODE
        D2D1_BITMAPSOURCE_PROP_ALPHA_MODE = 4,
        /// Property Name: "Orientation"
        /// Property Type: D2D1_BITMAPSOURCE_ORIENTATION
        D2D1_BITMAPSOURCE_PROP_ORIENTATION = 5,
        D2D1_BITMAPSOURCE_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_BITMAPSOURCE_PROP = ^TD2D1_BITMAPSOURCE_PROP;




    TD2D1_BITMAPSOURCE_INTERPOLATION_MODE = (
        D2D1_BITMAPSOURCE_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_BITMAPSOURCE_INTERPOLATION_MODE_LINEAR = 1,
        D2D1_BITMAPSOURCE_INTERPOLATION_MODE_CUBIC = 2,
        D2D1_BITMAPSOURCE_INTERPOLATION_MODE_FANT = 6,
        D2D1_BITMAPSOURCE_INTERPOLATION_MODE_MIPMAP_LINEAR = 7,
        D2D1_BITMAPSOURCE_INTERPOLATION_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_BITMAPSOURCE_INTERPOLATION_MODE = ^TD2D1_BITMAPSOURCE_INTERPOLATION_MODE;


    TD2D1_BITMAPSOURCE_ALPHA_MODE = (
        D2D1_BITMAPSOURCE_ALPHA_MODE_PREMULTIPLIED = 1,
        D2D1_BITMAPSOURCE_ALPHA_MODE_STRAIGHT = 2,
        D2D1_BITMAPSOURCE_ALPHA_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_BITMAPSOURCE_ALPHA_MODE = ^TD2D1_BITMAPSOURCE_ALPHA_MODE;



    /// The enumeration of the Composite effect's top level properties.
    /// Effect description: Composites foreground and background images using the
    /// selected composition mode.
    TD2D1_COMPOSITE_PROP = (
        /// Property Name: "Mode"
        /// Property Type: D2D1_COMPOSITE_MODE
        D2D1_COMPOSITE_PROP_MODE = 0,
        D2D1_COMPOSITE_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_COMPOSITE_PROP = ^TD2D1_COMPOSITE_PROP;




    /// The enumeration of the 3D Transform effect's top level properties.
    /// Effect description: Applies a 3D transform to a bitmap.
    TD2D1_3DTRANSFORM_PROP = (
        /// Property Name: "InterpolationMode"
        /// Property Type: D2D1_3DTRANSFORM_INTERPOLATION_MODE
        D2D1_3DTRANSFORM_PROP_INTERPOLATION_MODE = 0,
        /// Property Name: "BorderMode"
        /// Property Type: D2D1_BORDER_MODE
        D2D1_3DTRANSFORM_PROP_BORDER_MODE = 1,
        /// Property Name: "TransformMatrix"
        /// Property Type: D2D1_MATRIX_4X4_F
        D2D1_3DTRANSFORM_PROP_TRANSFORM_MATRIX = 2,
        D2D1_3DTRANSFORM_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_3DTRANSFORM_PROP = ^TD2D1_3DTRANSFORM_PROP;




    TD2D1_3DTRANSFORM_INTERPOLATION_MODE = (
        D2D1_3DTRANSFORM_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_3DTRANSFORM_INTERPOLATION_MODE_LINEAR = 1,
        D2D1_3DTRANSFORM_INTERPOLATION_MODE_CUBIC = 2,
        D2D1_3DTRANSFORM_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_3DTRANSFORM_INTERPOLATION_MODE_ANISOTROPIC = 4,
        D2D1_3DTRANSFORM_INTERPOLATION_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_3DTRANSFORM_INTERPOLATION_MODE = ^TD2D1_3DTRANSFORM_INTERPOLATION_MODE;



    /// The enumeration of the 3D Perspective Transform effect's top level properties.
    /// Effect description: Applies a 3D perspective transform to a bitmap.
    TD2D1_3DPERSPECTIVETRANSFORM_PROP = (
        /// Property Name: "InterpolationMode"
        /// Property Type: D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE
        D2D1_3DPERSPECTIVETRANSFORM_PROP_INTERPOLATION_MODE = 0,
        /// Property Name: "BorderMode"
        /// Property Type: D2D1_BORDER_MODE
        D2D1_3DPERSPECTIVETRANSFORM_PROP_BORDER_MODE = 1,
        /// Property Name: "Depth"
        /// Property Type: FLOAT
        D2D1_3DPERSPECTIVETRANSFORM_PROP_DEPTH = 2,
        /// Property Name: "PerspectiveOrigin"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_3DPERSPECTIVETRANSFORM_PROP_PERSPECTIVE_ORIGIN = 3,
        /// Property Name: "LocalOffset"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_3DPERSPECTIVETRANSFORM_PROP_LOCAL_OFFSET = 4,
        /// Property Name: "GlobalOffset"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_3DPERSPECTIVETRANSFORM_PROP_GLOBAL_OFFSET = 5,
        /// Property Name: "RotationOrigin"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_3DPERSPECTIVETRANSFORM_PROP_ROTATION_ORIGIN = 6,
        /// Property Name: "Rotation"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_3DPERSPECTIVETRANSFORM_PROP_ROTATION = 7,
        D2D1_3DPERSPECTIVETRANSFORM_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_3DPERSPECTIVETRANSFORM_PROP = ^TD2D1_3DPERSPECTIVETRANSFORM_PROP;




    TD2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE = (
        D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE_LINEAR = 1,
        D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE_CUBIC = 2,
        D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE_ANISOTROPIC = 4,
        D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE = ^TD2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE;



    /// The enumeration of the 2D Affine Transform effect's top level properties.
    /// Effect description: Applies a 2D affine transform to a bitmap.
    TD2D1_2DAFFINETRANSFORM_PROP = (
        /// Property Name: "InterpolationMode"
        /// Property Type: D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE
        D2D1_2DAFFINETRANSFORM_PROP_INTERPOLATION_MODE = 0,
        /// Property Name: "BorderMode"
        /// Property Type: D2D1_BORDER_MODE
        D2D1_2DAFFINETRANSFORM_PROP_BORDER_MODE = 1,
        /// Property Name: "TransformMatrix"
        /// Property Type: D2D1_MATRIX_3X2_F
        D2D1_2DAFFINETRANSFORM_PROP_TRANSFORM_MATRIX = 2,
        /// Property Name: "Sharpness"
        /// Property Type: FLOAT
        D2D1_2DAFFINETRANSFORM_PROP_SHARPNESS = 3,
        D2D1_2DAFFINETRANSFORM_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_2DAFFINETRANSFORM_PROP = ^TD2D1_2DAFFINETRANSFORM_PROP;




    TD2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE = (
        D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_LINEAR = 1,
        D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_CUBIC = 2,
        D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_ANISOTROPIC = 4,
        D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_HIGH_QUALITY_CUBIC = 5,
        D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE = ^TD2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE;



    /// The enumeration of the DPI Compensation effect's top level properties.
    /// Effect description: Scales according to the input DPI and the current context
    /// DPI
    TD2D1_DPICOMPENSATION_PROP = (
        /// Property Name: "InterpolationMode"
        /// Property Type: D2D1_DPICOMPENSATION_INTERPOLATION_MODE
        D2D1_DPICOMPENSATION_PROP_INTERPOLATION_MODE = 0,
        /// Property Name: "BorderMode"
        /// Property Type: D2D1_BORDER_MODE
        D2D1_DPICOMPENSATION_PROP_BORDER_MODE = 1,
        /// Property Name: "InputDpi"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_DPICOMPENSATION_PROP_INPUT_DPI = 2,
        D2D1_DPICOMPENSATION_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_DPICOMPENSATION_PROP = ^TD2D1_DPICOMPENSATION_PROP;




    TD2D1_DPICOMPENSATION_INTERPOLATION_MODE = (
        D2D1_DPICOMPENSATION_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_DPICOMPENSATION_INTERPOLATION_MODE_LINEAR = 1,
        D2D1_DPICOMPENSATION_INTERPOLATION_MODE_CUBIC = 2,
        D2D1_DPICOMPENSATION_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_DPICOMPENSATION_INTERPOLATION_MODE_ANISOTROPIC = 4,
        D2D1_DPICOMPENSATION_INTERPOLATION_MODE_HIGH_QUALITY_CUBIC = 5,
        D2D1_DPICOMPENSATION_INTERPOLATION_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_DPICOMPENSATION_INTERPOLATION_MODE = ^TD2D1_DPICOMPENSATION_INTERPOLATION_MODE;



    /// The enumeration of the Scale effect's top level properties.
    /// Effect description: Applies scaling operation to the bitmap.
    TD2D1_SCALE_PROP = (
        /// Property Name: "Scale"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_SCALE_PROP_SCALE = 0,
        /// Property Name: "CenterPoint"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_SCALE_PROP_CENTER_POINT = 1,
        /// Property Name: "InterpolationMode"
        /// Property Type: D2D1_SCALE_INTERPOLATION_MODE
        D2D1_SCALE_PROP_INTERPOLATION_MODE = 2,
        /// Property Name: "BorderMode"
        /// Property Type: D2D1_BORDER_MODE
        D2D1_SCALE_PROP_BORDER_MODE = 3,
        /// Property Name: "Sharpness"
        /// Property Type: FLOAT
        D2D1_SCALE_PROP_SHARPNESS = 4,
        D2D1_SCALE_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_SCALE_PROP = ^TD2D1_SCALE_PROP;




    TD2D1_SCALE_INTERPOLATION_MODE = (
        D2D1_SCALE_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_SCALE_INTERPOLATION_MODE_LINEAR = 1,
        D2D1_SCALE_INTERPOLATION_MODE_CUBIC = 2,
        D2D1_SCALE_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_SCALE_INTERPOLATION_MODE_ANISOTROPIC = 4,
        D2D1_SCALE_INTERPOLATION_MODE_HIGH_QUALITY_CUBIC = 5,
        D2D1_SCALE_INTERPOLATION_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_SCALE_INTERPOLATION_MODE = ^TD2D1_SCALE_INTERPOLATION_MODE;



    /// The enumeration of the Turbulence effect's top level properties.
    /// Effect description: Generates a bitmap based on the Perlin noise turbulence
    /// function.


    TD2D1_TURBULENCE_PROP = (
        /// Property Name: "Offset"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_TURBULENCE_PROP_OFFSET = 0,
        /// Property Name: "Size"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_TURBULENCE_PROP_SIZE = 1,
        /// Property Name: "BaseFrequency"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_TURBULENCE_PROP_BASE_FREQUENCY = 2,
        /// Property Name: "NumOctaves"
        /// Property Type: UINT32
        D2D1_TURBULENCE_PROP_NUM_OCTAVES = 3,
        /// Property Name: "Seed"
        /// Property Type: INT32
        D2D1_TURBULENCE_PROP_SEED = 4,
        /// Property Name: "Noise"
        /// Property Type: D2D1_TURBULENCE_NOISE
        D2D1_TURBULENCE_PROP_NOISE = 5,
        /// Property Name: "Stitchable"
        /// Property Type: BOOL
        D2D1_TURBULENCE_PROP_STITCHABLE = 6,
        D2D1_TURBULENCE_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_TURBULENCE_PROP = ^TD2D1_TURBULENCE_PROP;




    TD2D1_TURBULENCE_NOISE = (
        D2D1_TURBULENCE_NOISE_FRACTAL_SUM = 0,
        D2D1_TURBULENCE_NOISE_TURBULENCE = 1,
        D2D1_TURBULENCE_NOISE_FORCE_DWORD = $ffffffff);

    PD2D1_TURBULENCE_NOISE = ^TD2D1_TURBULENCE_NOISE;



    /// The enumeration of the Displacement Map effect's top level properties.
    /// Effect description: Displaces a bitmap based on user specified setting and
    /// another bitmap.
    TD2D1_DISPLACEMENTMAP_PROP = (
        /// Property Name: "Scale"
        /// Property Type: FLOAT
        D2D1_DISPLACEMENTMAP_PROP_SCALE = 0,
        /// Property Name: "XChannelSelect"
        /// Property Type: D2D1_CHANNEL_SELECTOR
        D2D1_DISPLACEMENTMAP_PROP_X_CHANNEL_SELECT = 1,
        /// Property Name: "YChannelSelect"
        /// Property Type: D2D1_CHANNEL_SELECTOR
        D2D1_DISPLACEMENTMAP_PROP_Y_CHANNEL_SELECT = 2,
        D2D1_DISPLACEMENTMAP_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_DISPLACEMENTMAP_PROP = ^TD2D1_DISPLACEMENTMAP_PROP;




    /// The enumeration of the Color Management effect's top level properties.
    /// Effect description: Changes colors based on user provided color contexts.
    TD2D1_COLORMANAGEMENT_PROP = (
        /// Property Name: "SourceColorContext"
        /// Property Type: ID2D1ColorContext *
        D2D1_COLORMANAGEMENT_PROP_SOURCE_COLOR_CONTEXT = 0,
        /// Property Name: "SourceRenderingIntent"
        /// Property Type: D2D1_RENDERING_INTENT
        D2D1_COLORMANAGEMENT_PROP_SOURCE_RENDERING_INTENT = 1,
        /// Property Name: "DestinationColorContext"
        /// Property Type: ID2D1ColorContext *
        D2D1_COLORMANAGEMENT_PROP_DESTINATION_COLOR_CONTEXT = 2,
        /// Property Name: "DestinationRenderingIntent"
        /// Property Type: D2D1_RENDERING_INTENT
        D2D1_COLORMANAGEMENT_PROP_DESTINATION_RENDERING_INTENT = 3,
        /// Property Name: "AlphaMode"
        /// Property Type: D2D1_COLORMANAGEMENT_ALPHA_MODE
        D2D1_COLORMANAGEMENT_PROP_ALPHA_MODE = 4,
        /// Property Name: "Quality"
        /// Property Type: D2D1_COLORMANAGEMENT_QUALITY
        D2D1_COLORMANAGEMENT_PROP_QUALITY = 5,
        D2D1_COLORMANAGEMENT_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_COLORMANAGEMENT_PROP = ^TD2D1_COLORMANAGEMENT_PROP;




    TD2D1_COLORMANAGEMENT_ALPHA_MODE = (
        D2D1_COLORMANAGEMENT_ALPHA_MODE_PREMULTIPLIED = 1,
        D2D1_COLORMANAGEMENT_ALPHA_MODE_STRAIGHT = 2,
        D2D1_COLORMANAGEMENT_ALPHA_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_COLORMANAGEMENT_ALPHA_MODE = ^TD2D1_COLORMANAGEMENT_ALPHA_MODE;


    TD2D1_COLORMANAGEMENT_QUALITY = (
        D2D1_COLORMANAGEMENT_QUALITY_PROOF = 0,
        D2D1_COLORMANAGEMENT_QUALITY_NORMAL = 1,
        D2D1_COLORMANAGEMENT_QUALITY_BEST = 2,
        D2D1_COLORMANAGEMENT_QUALITY_FORCE_DWORD = $ffffffff);

    PD2D1_COLORMANAGEMENT_QUALITY = ^TD2D1_COLORMANAGEMENT_QUALITY;



    /// Specifies which ICC rendering intent the Color management effect should use.


    TD2D1_COLORMANAGEMENT_RENDERING_INTENT = (
        D2D1_COLORMANAGEMENT_RENDERING_INTENT_PERCEPTUAL = 0,
        D2D1_COLORMANAGEMENT_RENDERING_INTENT_RELATIVE_COLORIMETRIC = 1,
        D2D1_COLORMANAGEMENT_RENDERING_INTENT_SATURATION = 2,
        D2D1_COLORMANAGEMENT_RENDERING_INTENT_ABSOLUTE_COLORIMETRIC = 3,
        D2D1_COLORMANAGEMENT_RENDERING_INTENT_FORCE_DWORD = $ffffffff);

    PD2D1_COLORMANAGEMENT_RENDERING_INTENT = ^TD2D1_COLORMANAGEMENT_RENDERING_INTENT;



    /// The enumeration of the Histogram effect's top level properties.
    /// Effect description: Computes the histogram of an image.
    TD2D1_HISTOGRAM_PROP = (
        /// Property Name: "NumBins"
        /// Property Type: UINT32
        D2D1_HISTOGRAM_PROP_NUM_BINS = 0,
        /// Property Name: "ChannelSelect"
        /// Property Type: D2D1_CHANNEL_SELECTOR
        D2D1_HISTOGRAM_PROP_CHANNEL_SELECT = 1,
        /// Property Name: "HistogramOutput"
        /// Property Type: (blob)
        D2D1_HISTOGRAM_PROP_HISTOGRAM_OUTPUT = 2,
        D2D1_HISTOGRAM_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_HISTOGRAM_PROP = ^TD2D1_HISTOGRAM_PROP;




    /// The enumeration of the Point-Specular effect's top level properties.
    /// Effect description: Creates a specular lighting effect with a point light
    /// source.
    TD2D1_POINTSPECULAR_PROP = (
        /// Property Name: "LightPosition"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_POINTSPECULAR_PROP_LIGHT_POSITION = 0,
        /// Property Name: "SpecularExponent"
        /// Property Type: FLOAT
        D2D1_POINTSPECULAR_PROP_SPECULAR_EXPONENT = 1,
        /// Property Name: "SpecularConstant"
        /// Property Type: FLOAT
        D2D1_POINTSPECULAR_PROP_SPECULAR_CONSTANT = 2,
        /// Property Name: "SurfaceScale"
        /// Property Type: FLOAT
        D2D1_POINTSPECULAR_PROP_SURFACE_SCALE = 3,
        /// Property Name: "Color"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_POINTSPECULAR_PROP_COLOR = 4,
        /// Property Name: "KernelUnitLength"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_POINTSPECULAR_PROP_KERNEL_UNIT_LENGTH = 5,
        /// Property Name: "ScaleMode"
        /// Property Type: D2D1_POINTSPECULAR_SCALE_MODE
        D2D1_POINTSPECULAR_PROP_SCALE_MODE = 6,
        D2D1_POINTSPECULAR_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_POINTSPECULAR_PROP = ^TD2D1_POINTSPECULAR_PROP;




    TD2D1_POINTSPECULAR_SCALE_MODE = (
        D2D1_POINTSPECULAR_SCALE_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_POINTSPECULAR_SCALE_MODE_LINEAR = 1,
        D2D1_POINTSPECULAR_SCALE_MODE_CUBIC = 2,
        D2D1_POINTSPECULAR_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_POINTSPECULAR_SCALE_MODE_ANISOTROPIC = 4,
        D2D1_POINTSPECULAR_SCALE_MODE_HIGH_QUALITY_CUBIC = 5,
        D2D1_POINTSPECULAR_SCALE_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_POINTSPECULAR_SCALE_MODE = ^TD2D1_POINTSPECULAR_SCALE_MODE;



    /// The enumeration of the Spot-Specular effect's top level properties.
    /// Effect description: Creates a specular lighting effect with a spot light source.
    TD2D1_SPOTSPECULAR_PROP = (
        /// Property Name: "LightPosition"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_SPOTSPECULAR_PROP_LIGHT_POSITION = 0,
        /// Property Name: "PointsAt"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_SPOTSPECULAR_PROP_POINTS_AT = 1,
        /// Property Name: "Focus"
        /// Property Type: FLOAT
        D2D1_SPOTSPECULAR_PROP_FOCUS = 2,
        /// Property Name: "LimitingConeAngle"
        /// Property Type: FLOAT
        D2D1_SPOTSPECULAR_PROP_LIMITING_CONE_ANGLE = 3,
        /// Property Name: "SpecularExponent"
        /// Property Type: FLOAT
        D2D1_SPOTSPECULAR_PROP_SPECULAR_EXPONENT = 4,
        /// Property Name: "SpecularConstant"
        /// Property Type: FLOAT
        D2D1_SPOTSPECULAR_PROP_SPECULAR_CONSTANT = 5,
        /// Property Name: "SurfaceScale"
        /// Property Type: FLOAT
        D2D1_SPOTSPECULAR_PROP_SURFACE_SCALE = 6,
        /// Property Name: "Color"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_SPOTSPECULAR_PROP_COLOR = 7,
        /// Property Name: "KernelUnitLength"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_SPOTSPECULAR_PROP_KERNEL_UNIT_LENGTH = 8,
        /// Property Name: "ScaleMode"
        /// Property Type: D2D1_SPOTSPECULAR_SCALE_MODE
        D2D1_SPOTSPECULAR_PROP_SCALE_MODE = 9,
        D2D1_SPOTSPECULAR_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_SPOTSPECULAR_PROP = ^TD2D1_SPOTSPECULAR_PROP;




    TD2D1_SPOTSPECULAR_SCALE_MODE = (
        D2D1_SPOTSPECULAR_SCALE_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_SPOTSPECULAR_SCALE_MODE_LINEAR = 1,
        D2D1_SPOTSPECULAR_SCALE_MODE_CUBIC = 2,
        D2D1_SPOTSPECULAR_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_SPOTSPECULAR_SCALE_MODE_ANISOTROPIC = 4,
        D2D1_SPOTSPECULAR_SCALE_MODE_HIGH_QUALITY_CUBIC = 5,
        D2D1_SPOTSPECULAR_SCALE_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_SPOTSPECULAR_SCALE_MODE = ^TD2D1_SPOTSPECULAR_SCALE_MODE;



    /// The enumeration of the Distant-Specular effect's top level properties.
    /// Effect description: Creates a specular lighting effect with a distant light
    /// source.
    TD2D1_DISTANTSPECULAR_PROP = (
        /// Property Name: "Azimuth"
        /// Property Type: FLOAT
        D2D1_DISTANTSPECULAR_PROP_AZIMUTH = 0,
        /// Property Name: "Elevation"
        /// Property Type: FLOAT
        D2D1_DISTANTSPECULAR_PROP_ELEVATION = 1,
        /// Property Name: "SpecularExponent"
        /// Property Type: FLOAT
        D2D1_DISTANTSPECULAR_PROP_SPECULAR_EXPONENT = 2,
        /// Property Name: "SpecularConstant"
        /// Property Type: FLOAT
        D2D1_DISTANTSPECULAR_PROP_SPECULAR_CONSTANT = 3,
        /// Property Name: "SurfaceScale"
        /// Property Type: FLOAT
        D2D1_DISTANTSPECULAR_PROP_SURFACE_SCALE = 4,
        /// Property Name: "Color"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_DISTANTSPECULAR_PROP_COLOR = 5,
        /// Property Name: "KernelUnitLength"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_DISTANTSPECULAR_PROP_KERNEL_UNIT_LENGTH = 6,
        /// Property Name: "ScaleMode"
        /// Property Type: D2D1_DISTANTSPECULAR_SCALE_MODE
        D2D1_DISTANTSPECULAR_PROP_SCALE_MODE = 7,
        D2D1_DISTANTSPECULAR_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_DISTANTSPECULAR_PROP = ^TD2D1_DISTANTSPECULAR_PROP;




    TD2D1_DISTANTSPECULAR_SCALE_MODE = (
        D2D1_DISTANTSPECULAR_SCALE_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_DISTANTSPECULAR_SCALE_MODE_LINEAR = 1,
        D2D1_DISTANTSPECULAR_SCALE_MODE_CUBIC = 2,
        D2D1_DISTANTSPECULAR_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_DISTANTSPECULAR_SCALE_MODE_ANISOTROPIC = 4,
        D2D1_DISTANTSPECULAR_SCALE_MODE_HIGH_QUALITY_CUBIC = 5,
        D2D1_DISTANTSPECULAR_SCALE_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_DISTANTSPECULAR_SCALE_MODE = ^TD2D1_DISTANTSPECULAR_SCALE_MODE;



    /// The enumeration of the Point-Diffuse effect's top level properties.
    /// Effect description: Creates a diffuse lighting effect with a point light source.
    TD2D1_POINTDIFFUSE_PROP = (
        /// Property Name: "LightPosition"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_POINTDIFFUSE_PROP_LIGHT_POSITION = 0,
        /// Property Name: "DiffuseConstant"
        /// Property Type: FLOAT
        D2D1_POINTDIFFUSE_PROP_DIFFUSE_CONSTANT = 1,
        /// Property Name: "SurfaceScale"
        /// Property Type: FLOAT
        D2D1_POINTDIFFUSE_PROP_SURFACE_SCALE = 2,
        /// Property Name: "Color"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_POINTDIFFUSE_PROP_COLOR = 3,
        /// Property Name: "KernelUnitLength"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_POINTDIFFUSE_PROP_KERNEL_UNIT_LENGTH = 4,
        /// Property Name: "ScaleMode"
        /// Property Type: D2D1_POINTDIFFUSE_SCALE_MODE
        D2D1_POINTDIFFUSE_PROP_SCALE_MODE = 5,
        D2D1_POINTDIFFUSE_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_POINTDIFFUSE_PROP = ^TD2D1_POINTDIFFUSE_PROP;




    TD2D1_POINTDIFFUSE_SCALE_MODE = (
        D2D1_POINTDIFFUSE_SCALE_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_POINTDIFFUSE_SCALE_MODE_LINEAR = 1,
        D2D1_POINTDIFFUSE_SCALE_MODE_CUBIC = 2,
        D2D1_POINTDIFFUSE_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_POINTDIFFUSE_SCALE_MODE_ANISOTROPIC = 4,
        D2D1_POINTDIFFUSE_SCALE_MODE_HIGH_QUALITY_CUBIC = 5,
        D2D1_POINTDIFFUSE_SCALE_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_POINTDIFFUSE_SCALE_MODE = ^TD2D1_POINTDIFFUSE_SCALE_MODE;



    /// The enumeration of the Spot-Diffuse effect's top level properties.
    /// Effect description: Creates a diffuse lighting effect with a spot light source.
    TD2D1_SPOTDIFFUSE_PROP = (
        /// Property Name: "LightPosition"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_SPOTDIFFUSE_PROP_LIGHT_POSITION = 0,
        /// Property Name: "PointsAt"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_SPOTDIFFUSE_PROP_POINTS_AT = 1,
        /// Property Name: "Focus"
        /// Property Type: FLOAT
        D2D1_SPOTDIFFUSE_PROP_FOCUS = 2,
        /// Property Name: "LimitingConeAngle"
        /// Property Type: FLOAT
        D2D1_SPOTDIFFUSE_PROP_LIMITING_CONE_ANGLE = 3,
        /// Property Name: "DiffuseConstant"
        /// Property Type: FLOAT
        D2D1_SPOTDIFFUSE_PROP_DIFFUSE_CONSTANT = 4,
        /// Property Name: "SurfaceScale"
        /// Property Type: FLOAT
        D2D1_SPOTDIFFUSE_PROP_SURFACE_SCALE = 5,
        /// Property Name: "Color"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_SPOTDIFFUSE_PROP_COLOR = 6,
        /// Property Name: "KernelUnitLength"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_SPOTDIFFUSE_PROP_KERNEL_UNIT_LENGTH = 7,
        /// Property Name: "ScaleMode"
        /// Property Type: D2D1_SPOTDIFFUSE_SCALE_MODE
        D2D1_SPOTDIFFUSE_PROP_SCALE_MODE = 8,
        D2D1_SPOTDIFFUSE_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_SPOTDIFFUSE_PROP = ^TD2D1_SPOTDIFFUSE_PROP;




    TD2D1_SPOTDIFFUSE_SCALE_MODE = (
        D2D1_SPOTDIFFUSE_SCALE_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_SPOTDIFFUSE_SCALE_MODE_LINEAR = 1,
        D2D1_SPOTDIFFUSE_SCALE_MODE_CUBIC = 2,
        D2D1_SPOTDIFFUSE_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_SPOTDIFFUSE_SCALE_MODE_ANISOTROPIC = 4,
        D2D1_SPOTDIFFUSE_SCALE_MODE_HIGH_QUALITY_CUBIC = 5,
        D2D1_SPOTDIFFUSE_SCALE_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_SPOTDIFFUSE_SCALE_MODE = ^TD2D1_SPOTDIFFUSE_SCALE_MODE;



    /// The enumeration of the Distant-Diffuse effect's top level properties.
    /// Effect description: Creates a diffuse lighting effect with a distant light
    /// source.
    TD2D1_DISTANTDIFFUSE_PROP = (
        /// Property Name: "Azimuth"
        /// Property Type: FLOAT
        D2D1_DISTANTDIFFUSE_PROP_AZIMUTH = 0,
        /// Property Name: "Elevation"
        /// Property Type: FLOAT
        D2D1_DISTANTDIFFUSE_PROP_ELEVATION = 1,
        /// Property Name: "DiffuseConstant"
        /// Property Type: FLOAT
        D2D1_DISTANTDIFFUSE_PROP_DIFFUSE_CONSTANT = 2,
        /// Property Name: "SurfaceScale"
        /// Property Type: FLOAT
        D2D1_DISTANTDIFFUSE_PROP_SURFACE_SCALE = 3,
        /// Property Name: "Color"
        /// Property Type: D2D1_VECTOR_3F
        D2D1_DISTANTDIFFUSE_PROP_COLOR = 4,
        /// Property Name: "KernelUnitLength"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_DISTANTDIFFUSE_PROP_KERNEL_UNIT_LENGTH = 5,
        /// Property Name: "ScaleMode"
        /// Property Type: D2D1_DISTANTDIFFUSE_SCALE_MODE
        D2D1_DISTANTDIFFUSE_PROP_SCALE_MODE = 6,
        D2D1_DISTANTDIFFUSE_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_DISTANTDIFFUSE_PROP = ^TD2D1_DISTANTDIFFUSE_PROP;




    TD2D1_DISTANTDIFFUSE_SCALE_MODE = (
        D2D1_DISTANTDIFFUSE_SCALE_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_DISTANTDIFFUSE_SCALE_MODE_LINEAR = 1,
        D2D1_DISTANTDIFFUSE_SCALE_MODE_CUBIC = 2,
        D2D1_DISTANTDIFFUSE_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_DISTANTDIFFUSE_SCALE_MODE_ANISOTROPIC = 4,
        D2D1_DISTANTDIFFUSE_SCALE_MODE_HIGH_QUALITY_CUBIC = 5,
        D2D1_DISTANTDIFFUSE_SCALE_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_DISTANTDIFFUSE_SCALE_MODE = ^TD2D1_DISTANTDIFFUSE_SCALE_MODE;



    /// The enumeration of the Flood effect's top level properties.
    /// Effect description: Renders an infinite sized floodfill of the given color.
    TD2D1_FLOOD_PROP = (
        /// Property Name: "Color"
        /// Property Type: D2D1_VECTOR_4F
        D2D1_FLOOD_PROP_COLOR = 0,
        D2D1_FLOOD_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_FLOOD_PROP = ^TD2D1_FLOOD_PROP;




    /// The enumeration of the Linear Transfer effect's top level properties.
    /// Effect description: Remaps the color intensities of the input bitmap based on a
    /// user specified linear transfer function for each RGBA channel.
    TD2D1_LINEARTRANSFER_PROP = (
        /// Property Name: "RedYIntercept"
        /// Property Type: FLOAT
        D2D1_LINEARTRANSFER_PROP_RED_Y_INTERCEPT = 0,
        /// Property Name: "RedSlope"
        /// Property Type: FLOAT
        D2D1_LINEARTRANSFER_PROP_RED_SLOPE = 1,
        /// Property Name: "RedDisable"
        /// Property Type: BOOL
        D2D1_LINEARTRANSFER_PROP_RED_DISABLE = 2,
        /// Property Name: "GreenYIntercept"
        /// Property Type: FLOAT
        D2D1_LINEARTRANSFER_PROP_GREEN_Y_INTERCEPT = 3,
        /// Property Name: "GreenSlope"
        /// Property Type: FLOAT
        D2D1_LINEARTRANSFER_PROP_GREEN_SLOPE = 4,
        /// Property Name: "GreenDisable"
        /// Property Type: BOOL
        D2D1_LINEARTRANSFER_PROP_GREEN_DISABLE = 5,
        /// Property Name: "BlueYIntercept"
        /// Property Type: FLOAT
        D2D1_LINEARTRANSFER_PROP_BLUE_Y_INTERCEPT = 6,
        /// Property Name: "BlueSlope"
        /// Property Type: FLOAT
        D2D1_LINEARTRANSFER_PROP_BLUE_SLOPE = 7,
        /// Property Name: "BlueDisable"
        /// Property Type: BOOL
        D2D1_LINEARTRANSFER_PROP_BLUE_DISABLE = 8,
        /// Property Name: "AlphaYIntercept"
        /// Property Type: FLOAT
        D2D1_LINEARTRANSFER_PROP_ALPHA_Y_INTERCEPT = 9,
        /// Property Name: "AlphaSlope"
        /// Property Type: FLOAT
        D2D1_LINEARTRANSFER_PROP_ALPHA_SLOPE = 10,
        /// Property Name: "AlphaDisable"
        /// Property Type: BOOL
        D2D1_LINEARTRANSFER_PROP_ALPHA_DISABLE = 11,
        /// Property Name: "ClampOutput"
        /// Property Type: BOOL
        D2D1_LINEARTRANSFER_PROP_CLAMP_OUTPUT = 12,
        D2D1_LINEARTRANSFER_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_LINEARTRANSFER_PROP = ^TD2D1_LINEARTRANSFER_PROP;




    /// The enumeration of the Gamma Transfer effect's top level properties.
    /// Effect description: Remaps the color intensities of the input bitmap based on a
    /// user specified gamma transfer function for each RGBA channel.
    TD2D1_GAMMATRANSFER_PROP = (
        /// Property Name: "RedAmplitude"
        /// Property Type: FLOAT
        D2D1_GAMMATRANSFER_PROP_RED_AMPLITUDE = 0,
        /// Property Name: "RedExponent"
        /// Property Type: FLOAT
        D2D1_GAMMATRANSFER_PROP_RED_EXPONENT = 1,
        /// Property Name: "RedOffset"
        /// Property Type: FLOAT
        D2D1_GAMMATRANSFER_PROP_RED_OFFSET = 2,
        /// Property Name: "RedDisable"
        /// Property Type: BOOL
        D2D1_GAMMATRANSFER_PROP_RED_DISABLE = 3,
        /// Property Name: "GreenAmplitude"
        /// Property Type: FLOAT
        D2D1_GAMMATRANSFER_PROP_GREEN_AMPLITUDE = 4,
        /// Property Name: "GreenExponent"
        /// Property Type: FLOAT
        D2D1_GAMMATRANSFER_PROP_GREEN_EXPONENT = 5,
        /// Property Name: "GreenOffset"
        /// Property Type: FLOAT
        D2D1_GAMMATRANSFER_PROP_GREEN_OFFSET = 6,
        /// Property Name: "GreenDisable"
        /// Property Type: BOOL
        D2D1_GAMMATRANSFER_PROP_GREEN_DISABLE = 7,
        /// Property Name: "BlueAmplitude"
        /// Property Type: FLOAT
        D2D1_GAMMATRANSFER_PROP_BLUE_AMPLITUDE = 8,
        /// Property Name: "BlueExponent"
        /// Property Type: FLOAT
        D2D1_GAMMATRANSFER_PROP_BLUE_EXPONENT = 9,
        /// Property Name: "BlueOffset"
        /// Property Type: FLOAT
        D2D1_GAMMATRANSFER_PROP_BLUE_OFFSET = 10,
        /// Property Name: "BlueDisable"
        /// Property Type: BOOL
        D2D1_GAMMATRANSFER_PROP_BLUE_DISABLE = 11,
        /// Property Name: "AlphaAmplitude"
        /// Property Type: FLOAT
        D2D1_GAMMATRANSFER_PROP_ALPHA_AMPLITUDE = 12,
        /// Property Name: "AlphaExponent"
        /// Property Type: FLOAT
        D2D1_GAMMATRANSFER_PROP_ALPHA_EXPONENT = 13,
        /// Property Name: "AlphaOffset"
        /// Property Type: FLOAT
        D2D1_GAMMATRANSFER_PROP_ALPHA_OFFSET = 14,
        /// Property Name: "AlphaDisable"
        /// Property Type: BOOL
        D2D1_GAMMATRANSFER_PROP_ALPHA_DISABLE = 15,
        /// Property Name: "ClampOutput"
        /// Property Type: BOOL
        D2D1_GAMMATRANSFER_PROP_CLAMP_OUTPUT = 16,
        D2D1_GAMMATRANSFER_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_GAMMATRANSFER_PROP = ^TD2D1_GAMMATRANSFER_PROP;




    /// The enumeration of the Table Transfer effect's top level properties.
    /// Effect description: Remaps the color intensities of the input bitmap based on a
    /// transfer function generated by a user specified list of values for each RGBA
    /// channel.
    TD2D1_TABLETRANSFER_PROP = (
        /// Property Name: "RedTable"
        /// Property Type: (blob)
        D2D1_TABLETRANSFER_PROP_RED_TABLE = 0,
        /// Property Name: "RedDisable"
        /// Property Type: BOOL
        D2D1_TABLETRANSFER_PROP_RED_DISABLE = 1,
        /// Property Name: "GreenTable"
        /// Property Type: (blob)
        D2D1_TABLETRANSFER_PROP_GREEN_TABLE = 2,
        /// Property Name: "GreenDisable"
        /// Property Type: BOOL
        D2D1_TABLETRANSFER_PROP_GREEN_DISABLE = 3,
        /// Property Name: "BlueTable"
        /// Property Type: (blob)
        D2D1_TABLETRANSFER_PROP_BLUE_TABLE = 4,
        /// Property Name: "BlueDisable"
        /// Property Type: BOOL
        D2D1_TABLETRANSFER_PROP_BLUE_DISABLE = 5,
        /// Property Name: "AlphaTable"
        /// Property Type: (blob)
        D2D1_TABLETRANSFER_PROP_ALPHA_TABLE = 6,
        /// Property Name: "AlphaDisable"
        /// Property Type: BOOL
        D2D1_TABLETRANSFER_PROP_ALPHA_DISABLE = 7,
        /// Property Name: "ClampOutput"
        /// Property Type: BOOL
        D2D1_TABLETRANSFER_PROP_CLAMP_OUTPUT = 8,
        D2D1_TABLETRANSFER_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_TABLETRANSFER_PROP = ^TD2D1_TABLETRANSFER_PROP;




    /// The enumeration of the Discrete Transfer effect's top level properties.
    /// Effect description: Remaps the color intensities of the input bitmap based on a
    /// discrete function generated by a user specified list of values for each RGBA
    /// channel.
    TD2D1_DISCRETETRANSFER_PROP = (
        /// Property Name: "RedTable"
        /// Property Type: (blob)
        D2D1_DISCRETETRANSFER_PROP_RED_TABLE = 0,
        /// Property Name: "RedDisable"
        /// Property Type: BOOL
        D2D1_DISCRETETRANSFER_PROP_RED_DISABLE = 1,
        /// Property Name: "GreenTable"
        /// Property Type: (blob)
        D2D1_DISCRETETRANSFER_PROP_GREEN_TABLE = 2,
        /// Property Name: "GreenDisable"
        /// Property Type: BOOL
        D2D1_DISCRETETRANSFER_PROP_GREEN_DISABLE = 3,
        /// Property Name: "BlueTable"
        /// Property Type: (blob)
        D2D1_DISCRETETRANSFER_PROP_BLUE_TABLE = 4,
        /// Property Name: "BlueDisable"
        /// Property Type: BOOL
        D2D1_DISCRETETRANSFER_PROP_BLUE_DISABLE = 5,
        /// Property Name: "AlphaTable"
        /// Property Type: (blob)
        D2D1_DISCRETETRANSFER_PROP_ALPHA_TABLE = 6,
        /// Property Name: "AlphaDisable"
        /// Property Type: BOOL
        D2D1_DISCRETETRANSFER_PROP_ALPHA_DISABLE = 7,
        /// Property Name: "ClampOutput"
        /// Property Type: BOOL
        D2D1_DISCRETETRANSFER_PROP_CLAMP_OUTPUT = 8,
        D2D1_DISCRETETRANSFER_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_DISCRETETRANSFER_PROP = ^TD2D1_DISCRETETRANSFER_PROP;




    /// The enumeration of the Convolve Matrix effect's top level properties.
    /// Effect description: Applies a user specified convolution kernel to a bitmap.
    TD2D1_CONVOLVEMATRIX_PROP = (
        /// Property Name: "KernelUnitLength"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_CONVOLVEMATRIX_PROP_KERNEL_UNIT_LENGTH = 0,
        /// Property Name: "ScaleMode"
        /// Property Type: D2D1_CONVOLVEMATRIX_SCALE_MODE
        D2D1_CONVOLVEMATRIX_PROP_SCALE_MODE = 1,
        /// Property Name: "KernelSizeX"
        /// Property Type: UINT32
        D2D1_CONVOLVEMATRIX_PROP_KERNEL_SIZE_X = 2,
        /// Property Name: "KernelSizeY"
        /// Property Type: UINT32
        D2D1_CONVOLVEMATRIX_PROP_KERNEL_SIZE_Y = 3,
        /// Property Name: "KernelMatrix"
        /// Property Type: (blob)
        D2D1_CONVOLVEMATRIX_PROP_KERNEL_MATRIX = 4,
        /// Property Name: "Divisor"
        /// Property Type: FLOAT
        D2D1_CONVOLVEMATRIX_PROP_DIVISOR = 5,
        /// Property Name: "Bias"
        /// Property Type: FLOAT
        D2D1_CONVOLVEMATRIX_PROP_BIAS = 6,
        /// Property Name: "KernelOffset"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_CONVOLVEMATRIX_PROP_KERNEL_OFFSET = 7,
        /// Property Name: "PreserveAlpha"
        /// Property Type: BOOL
        D2D1_CONVOLVEMATRIX_PROP_PRESERVE_ALPHA = 8,
        /// Property Name: "BorderMode"
        /// Property Type: D2D1_BORDER_MODE
        D2D1_CONVOLVEMATRIX_PROP_BORDER_MODE = 9,
        /// Property Name: "ClampOutput"
        /// Property Type: BOOL
        D2D1_CONVOLVEMATRIX_PROP_CLAMP_OUTPUT = 10,
        D2D1_CONVOLVEMATRIX_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_CONVOLVEMATRIX_PROP = ^TD2D1_CONVOLVEMATRIX_PROP;




    TD2D1_CONVOLVEMATRIX_SCALE_MODE = (
        D2D1_CONVOLVEMATRIX_SCALE_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_CONVOLVEMATRIX_SCALE_MODE_LINEAR = 1,
        D2D1_CONVOLVEMATRIX_SCALE_MODE_CUBIC = 2,
        D2D1_CONVOLVEMATRIX_SCALE_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_CONVOLVEMATRIX_SCALE_MODE_ANISOTROPIC = 4,
        D2D1_CONVOLVEMATRIX_SCALE_MODE_HIGH_QUALITY_CUBIC = 5,
        D2D1_CONVOLVEMATRIX_SCALE_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_CONVOLVEMATRIX_SCALE_MODE = ^TD2D1_CONVOLVEMATRIX_SCALE_MODE;



    /// The enumeration of the Brightness effect's top level properties.
    /// Effect description: Adjusts the brightness of the image based on the specified
    /// white and black point.
    TD2D1_BRIGHTNESS_PROP = (
        /// Property Name: "WhitePoint"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_BRIGHTNESS_PROP_WHITE_POINT = 0,
        /// Property Name: "BlackPoint"
        /// Property Type: D2D1_VECTOR_2F
        D2D1_BRIGHTNESS_PROP_BLACK_POINT = 1,
        D2D1_BRIGHTNESS_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_BRIGHTNESS_PROP = ^TD2D1_BRIGHTNESS_PROP;




    /// The enumeration of the Arithmetic Composite effect's top level properties.
    /// Effect description: Composites two bitmaps based on the following algorithm:
    /// Output = Coefficients_1 * Source * Destination + Coefficients_2 * Source+
    /// Coefficients_3 * Destination + Coefficients_4.
    TD2D1_ARITHMETICCOMPOSITE_PROP = (
        /// Property Name: "Coefficients"
        /// Property Type: D2D1_VECTOR_4F
        D2D1_ARITHMETICCOMPOSITE_PROP_COEFFICIENTS = 0,
        /// Property Name: "ClampOutput"
        /// Property Type: BOOL
        D2D1_ARITHMETICCOMPOSITE_PROP_CLAMP_OUTPUT = 1,
        D2D1_ARITHMETICCOMPOSITE_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_ARITHMETICCOMPOSITE_PROP = ^TD2D1_ARITHMETICCOMPOSITE_PROP;




    /// The enumeration of the Crop effect's top level properties.
    /// Effect description: Crops the input bitmap according to the specified
    /// parameters.
    TD2D1_CROP_PROP = (
        /// Property Name: "Rect"
        /// Property Type: D2D1_VECTOR_4F
        D2D1_CROP_PROP_RECT = 0,
        /// Property Name: "BorderMode"
        /// Property Type: D2D1_BORDER_MODE
        D2D1_CROP_PROP_BORDER_MODE = 1,
        D2D1_CROP_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_CROP_PROP = ^TD2D1_CROP_PROP;




    /// The enumeration of the Border effect's top level properties.
    /// Effect description: Extends the region of the bitmap based on the selected
    /// border mode.
    TD2D1_BORDER_PROP = (
        /// Property Name: "EdgeModeX"
        /// Property Type: D2D1_BORDER_EDGE_MODE
        D2D1_BORDER_PROP_EDGE_MODE_X = 0,
        /// Property Name: "EdgeModeY"
        /// Property Type: D2D1_BORDER_EDGE_MODE
        D2D1_BORDER_PROP_EDGE_MODE_Y = 1,
        D2D1_BORDER_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_BORDER_PROP = ^TD2D1_BORDER_PROP;




    /// The edge mode for the Border effect.
    TD2D1_BORDER_EDGE_MODE = (
        D2D1_BORDER_EDGE_MODE_CLAMP = 0,
        D2D1_BORDER_EDGE_MODE_WRAP = 1,
        D2D1_BORDER_EDGE_MODE_MIRROR = 2,
        D2D1_BORDER_EDGE_MODE_FORCE_DWORD = $ffffffff);

    PD2D1_BORDER_EDGE_MODE = ^TD2D1_BORDER_EDGE_MODE;



    /// The enumeration of the Morphology effect's top level properties.
    /// Effect description: Erodes or dilates a bitmap by the given radius.
    TD2D1_MORPHOLOGY_PROP = (
        /// Property Name: "Mode"
        /// Property Type: D2D1_MORPHOLOGY_MODE
        D2D1_MORPHOLOGY_PROP_MODE = 0,
        /// Property Name: "Width"
        /// Property Type: UINT32
        D2D1_MORPHOLOGY_PROP_WIDTH = 1,
        /// Property Name: "Height"
        /// Property Type: UINT32
        D2D1_MORPHOLOGY_PROP_HEIGHT = 2,
        D2D1_MORPHOLOGY_PROP_FORCE_DWORD = $ffffffff);

    PD2D1_MORPHOLOGY_PROP = ^TD2D1_MORPHOLOGY_PROP;




    TD2D1_MORPHOLOGY_MODE = (
        D2D1_MORPHOLOGY_MODE_ERODE = 0,
        D2D1_MORPHOLOGY_MODE_DILATE = 1,
        D2D1_MORPHOLOGY_MODE_FORCE_DWORD = longint($ffffffff));

    PD2D1_MORPHOLOGY_MODE = ^TD2D1_MORPHOLOGY_MODE;



    /// The enumeration of the Tile effect's top level properties.
    /// Effect description: Tiles the specified region of the input bitmap.
    TD2D1_TILE_PROP = (
        /// Property Name: "Rect"
        /// Property Type: D2D1_VECTOR_4F
        D2D1_TILE_PROP_RECT = 0,
        D2D1_TILE_PROP_FORCE_DWORD = longint($ffffffff));

    PD2D1_TILE_PROP = ^TD2D1_TILE_PROP;




    /// The enumeration of the Atlas effect's top level properties.
    /// Effect description: Changes the available area of the input to the specified
    /// rectangle. Provides an optimization for scenarios where a bitmap is used as an
    /// atlas.
    TD2D1_ATLAS_PROP = (
        /// Property Name: "InputRect"
        /// Property Type: D2D1_VECTOR_4F
        D2D1_ATLAS_PROP_INPUT_RECT = 0,
        /// Property Name: "InputPaddingRect"
        /// Property Type: D2D1_VECTOR_4F
        D2D1_ATLAS_PROP_INPUT_PADDING_RECT = 1,
        D2D1_ATLAS_PROP_FORCE_DWORD = longint($ffffffff));

    PD2D1_ATLAS_PROP = ^TD2D1_ATLAS_PROP;




    /// The enumeration of the Opacity Metadata effect's top level properties.
    /// Effect description: Changes the rectangle which is assumed to be opaque.
    /// Provides optimizations in certain scenarios.
    TD2D1_OPACITYMETADATA_PROP = (
        /// Property Name: "InputOpaqueRect"
        /// Property Type: D2D1_VECTOR_4F
        D2D1_OPACITYMETADATA_PROP_INPUT_OPAQUE_RECT = 0,
        D2D1_OPACITYMETADATA_PROP_FORCE_DWORD = longint($ffffffff));

    PD2D1_OPACITYMETADATA_PROP = ^TD2D1_OPACITYMETADATA_PROP;


implementation

end.
