{ **************************************************************************
    FreePascal/Delphi DirectX 12 Header Files

    Copyright (C) 2013-2025 Norbert Sonnleitner

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
************************************************************************** }

{ **************************************************************************
   Additional Copyright (C) for this modul:

   Copyright (c) Microsoft Corporation.  All rights reserved.
   This file is automatically generated.  Please do not edit it directly.

   This unit consists of the following header files
   File name: d2d1_2.h

   Header version: 10.0.26100.6584

  ************************************************************************** }
unit DX12.D2D1_2;

{$mode ObjFPC}{$H+}

interface

uses
    Windows, Classes, SysUtils,
    DX12.DXGI,
    DX12.D2D1,
    DX12.D2D1_1;

    {$Z4}

const
    IID_ID2D1GeometryRealization: TGUID = '{a16907d7-bc02-4801-99e8-8cf7f485f774}';
    IID_ID2D1DeviceContext1: TGUID = '{d37f57e4-6908-459f-a199-e72f24f79987}';
    IID_ID2D1Device1: TGUID = '{d21768e1-23a4-4823-a14b-7c3eba85d658}';
    IID_ID2D1Factory2: TGUID = '{94f81a73-9212-4376-9c58-b16a3a0d3992}';
    IID_ID2D1CommandSink1: TGUID = '{9eb767fd-4269-4467-b8c2-eb30cb305743}';

type
    /// Specifies the extent to which D2D will throttle work sent to the GPU.
    TD2D1_RENDERING_PRIORITY = (
        D2D1_RENDERING_PRIORITY_NORMAL = 0,
        D2D1_RENDERING_PRIORITY_LOW = 1,
        D2D1_RENDERING_PRIORITY_FORCE_DWORD = longint($ffffffff)
        );

    PD2D1_RENDERING_PRIORITY = ^TD2D1_RENDERING_PRIORITY;


    /// Encapsulates a device- and transform-dependent representation of a filled or
    /// stroked geometry.
    ID2D1GeometryRealization = interface(ID2D1Resource)
        ['{a16907d7-bc02-4801-99e8-8cf7f485f774}']
    end;

    /// Enables creation and drawing of geometry realization objects.
    ID2D1DeviceContext1 = interface(ID2D1DeviceContext)
        ['{d37f57e4-6908-459f-a199-e72f24f79987}']
        function CreateFilledGeometryRealization(
        {_In_ } geometry: ID2D1Geometry; flatteningTolerance: single;
        {_COM_Outptr_ }  out geometryRealization: ID2D1GeometryRealization): HRESULT; stdcall;

        function CreateStrokedGeometryRealization(
        {_In_ } geometry: ID2D1Geometry; flatteningTolerance: single; strokeWidth: single;
        {_In_opt_ } strokeStyle: ID2D1StrokeStyle;
        {_COM_Outptr_ }  out geometryRealization: ID2D1GeometryRealization): HRESULT; stdcall;

        procedure DrawGeometryRealization(
        {_In_ } geometryRealization: ID2D1GeometryRealization;
        {_In_ } brush: ID2D1Brush); stdcall;

    end;

    /// Represents a resource domain whose objects and device contexts can be used
    /// together.
    ID2D1Device1 = interface(ID2D1Device)
        ['{d21768e1-23a4-4823-a14b-7c3eba85d658}']
        /// Retrieves the rendering priority currently set on the device.
        function GetRenderingPriority(): TD2D1_RENDERING_PRIORITY; stdcall;

        /// Sets the rendering priority of the device.
        procedure SetRenderingPriority(renderingPriority: TD2D1_RENDERING_PRIORITY); stdcall;

        /// Creates a new device context with no initially assigned target.
        function CreateDeviceContext(options: TD2D1_DEVICE_CONTEXT_OPTIONS;
        {_COM_Outptr_ }  out deviceContext1: ID2D1DeviceContext1): HRESULT; stdcall;

    end;

    /// Creates Direct2D resources. This interface also enables the creation of
    /// ID2D1Device1 objects.
    ID2D1Factory2 = interface(ID2D1Factory1)
        ['{94f81a73-9212-4376-9c58-b16a3a0d3992}']
        /// This creates a new Direct2D device from the given IDXGIDevice.
        function CreateDevice(
        {_In_ } dxgiDevice: IDXGIDevice;
        {_COM_Outptr_ }  out d2dDevice1: ID2D1Device1): HRESULT; stdcall;

    end;

    /// This interface performs all the same functions as the existing ID2D1CommandSink
    /// interface. It also enables access to the new primitive blend modes, MIN and ADD,
    /// through its SetPrimitiveBlend1 method.
    ID2D1CommandSink1 = interface(ID2D1CommandSink)
        ['{9eb767fd-4269-4467-b8c2-eb30cb305743}']
        /// This method is called if primitiveBlend value was added after Windows 8.
        /// SetPrimitiveBlend method is used for Win8 values (_SOURCE_OVER and _COPY).
        function SetPrimitiveBlend1(primitiveBlend: TD2D1_PRIMITIVE_BLEND): HRESULT; stdcall;

    end;


function D2D1ComputeMaximumScaleFactor(
    {_In_} matrix: PD2D1_MATRIX_3X2_F): single; stdcall; external D2D1_DLL;


implementation

end.
