{ **************************************************************************
    FreePascal/Delphi DirectX 12 Header Files

    Copyright (C) 2013-2025 Norbert Sonnleitner

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
************************************************************************** }

{ **************************************************************************
   Additional Copyright (C) for this modul:

   Copyright (c) Microsoft Corporation.  All rights reserved.
   This file is automatically generated.  Please do not edit it directly.

   This unit consists of the following header files
   File name: wincode.h
   Some defines are found also in DX12.WinCodecD2D1 to avoid circular reference for DX12.D2D1
   Header version: 10.0.26100.6584

  ************************************************************************** }
unit DX12.WinCodec;


{$IFDEF FPC}
{$mode delphiunicode}{$H+}
{$modeswitch ADVANCEDRECORDS}
{$modeswitch TypeHelpers}
{$ENDIF}

interface

uses
    Windows, Classes, SysUtils,
    ActiveX,
    Win32.OCIdl,
    Win32.ObjIdl,
    DX12.DXGIFormat,
    DX12.DXGIType,
    DX12.DCommon;

    {$Z4}

const
    WINCODEC_SDK_VERSION1 = $0236;
    WINCODEC_SDK_VERSION2 = $0237;
    CLSID_WICImagingFactory: TGUID = '{CACAF262-9370-4615-A13B-9F5539DA4C0A}';
    CLSID_WICImagingFactory1: TGUID = '{CACAF262-9370-4615-A13B-9F5539DA4C0A}';
    CLSID_WICImagingFactory2: TGUID = '{317D06E8-5F24-433D-BDF7-79CE68D8ABC2}';

    WINCODEC_SDK_VERSION = WINCODEC_SDK_VERSION2;


    GUID_VendorMicrosoft: TGUID = '{F0E749CA-EDEF-4589-A73A-EE0E626A2A2B}';
    GUID_VendorMicrosoftBuiltIn: TGUID = '{257A30FD-06B6-462B-AEA4-63F70B86E533}';
    CLSID_WICPngDecoder: TGUID = '{389EA17B-5078-4CDE-B6EF-25C15175C751}';
    CLSID_WICPngDecoder1: TGUID = '{389EA17B-5078-4CDE-B6EF-25C15175C751}';
    CLSID_WICPngDecoder2: TGUID = '{E018945B-AA86-4008-9BD4-6777A1E40C11}';


    CLSID_WICBmpDecoder: TGUID = '{6B462062-7CBF-400D-9FDB-813DD10F2778}';
    CLSID_WICIcoDecoder: TGUID = '{C61BFCDF-2E0F-4AAD-A8D7-E06BAFEBCDFE}';
    CLSID_WICJpegDecoder: TGUID = '{9456A480-E88B-43EA-9E73-0B2D9B71B1CA}';
    CLSID_WICGifDecoder: TGUID = '{381DDA3C-9CE9-4834-A23E-1F98F8FC52BE}';
    CLSID_WICTiffDecoder: TGUID = '{B54E85D9-FE23-499F-8B88-6ACEA713752B}';
    CLSID_WICWmpDecoder: TGUID = '{A26CEC36-234C-4950-AE16-E34AACE71D0D}';
    CLSID_WICDdsDecoder: TGUID = '{9053699F-A341-429D-9E90-EE437CF80C73}';
    CLSID_WICBmpEncoder: TGUID = '{69BE8BB4-D66D-47C8-865A-ED1589433782}';
    CLSID_WICPngEncoder: TGUID = '{27949969-876A-41D7-9447-568F6A35A4DC}';
    CLSID_WICJpegEncoder: TGUID = '{1A34F5C1-4A5A-46DC-B644-1F4567E7A676}';
    CLSID_WICGifEncoder: TGUID = '{114F5598-0B22-40A0-86A1-C83EA495ADBD}';
    CLSID_WICTiffEncoder: TGUID = '{0131BE10-2001-4C5F-A9B0-CC88FAB64CE8}';
    CLSID_WICWmpEncoder: TGUID = '{AC4CE3CB-E1C1-44CD-8215-5A1665509EC2}';
    CLSID_WICDdsEncoder: TGUID = '{A61DDE94-66CE-4AC1-881B-71680588895E}';
    CLSID_WICAdngDecoder: TGUID = '{981D9411-909E-42A7-8F5D-A747FF052EDB}';
    CLSID_WICJpegQualcommPhoneEncoder: TGUID = '{68ED5C62-F534-4979-B2B3-686A12B2B34C}';
    CLSID_WICHeifDecoder: TGUID = '{E9A4A80A-44FE-4DE4-8971-7150B10A5199}';
    CLSID_WICHeifEncoder: TGUID = '{0DBECEC1-9EB3-4860-9C6F-DDBE86634575}';
    CLSID_WICWebpDecoder: TGUID = '{7693E886-51C9-4070-8419-9F70738EC8FA}';
    CLSID_WICRAWDecoder: TGUID = '{41945702-8302-44A6-9445-AC98E8AFA086}';
    CLSID_WICJpegXLDecoder: TGUID = '{FC6CEECE-AEF5-4A23-96EC-5984FFB486D9}';
    CLSID_WICJpegXLEncoder: TGUID = '{0E4ECD3B-1BA6-4636-8198-56C73040964A}';
    GUID_ContainerFormatBmp: TGUID = '{0AF1D87E-FCFE-4188-BDEB-A7906471CBE3}';
    GUID_ContainerFormatPng: TGUID = '{1B7CFAF4-713F-473C-BBCD-6137425FAEAF}';
    GUID_ContainerFormatIco: TGUID = '{A3A860C4-338F-4C17-919A-FBA4B5628F21}';
    GUID_ContainerFormatJpeg: TGUID = '{19E4A5AA-5662-4FC5-A0C0-1758028E1057}';
    GUID_ContainerFormatTiff: TGUID = '{163BCC30-E2E9-4F0B-961D-A3E9FDB788A3}';
    GUID_ContainerFormatGif: TGUID = '{1F8A5601-7D4D-4CBD-9C82-1BC8D4EEB9A5}';
    GUID_ContainerFormatWmp: TGUID = '{57A37CAA-367A-4540-916B-F183C5093A4B}';
    GUID_ContainerFormatDds: TGUID = '{9967CB95-2E85-4AC8-8CA2-83D7CCD425C9}';
    GUID_ContainerFormatAdng: TGUID = '{F3FF6D0D-38C0-41C4-B1FE-1F3824F17B84}';
    GUID_ContainerFormatHeif: TGUID = '{E1E62521-6787-405B-A339-500715B5763F}';
    GUID_ContainerFormatWebp: TGUID = '{E094B0E2-67F2-45B3-B0EA-115337CA7CF3}';
    GUID_ContainerFormatRaw: TGUID = '{FE99CE60-F19C-433C-A3AE-00ACEFA9CA21}';
    GUID_ContainerFormatJpegXL: TGUID = '{FEC14E3F-427A-4736-AAE6-27ED84F69322}';
    CLSID_WICImagingCategories: TGUID = '{FAE3D380-FEA4-4623-8C75-C6B61110B681}';
    CATID_WICBitmapDecoders: TGUID = '{7ED96837-96F0-4812-B211-F13C24117ED3}';
    CATID_WICBitmapEncoders: TGUID = '{AC757296-3522-4E11-9862-C17BE5A1767E}';
    CATID_WICPixelFormats: TGUID = '{2B46E70F-CDA7-473E-89F6-DC9630A2390B}';
    CATID_WICFormatConverters: TGUID = '{7835EAE8-BF14-49D1-93CE-533A407B2248}';
    CATID_WICMetadataReader: TGUID = '{05AF94D8-7174-4CD2-BE4A-4124B80EE4B8}';
    CATID_WICMetadataWriter: TGUID = '{ABE3B9A4-257D-4B97-BD1A-294AF496222E}';
    CLSID_WICDefaultFormatConverter: TGUID = '{1A3F11DC-B514-4B17-8C5F-2154513852F1}';
    CLSID_WICFormatConverterHighColor: TGUID = '{AC75D454-9F37-48F8-B972-4E19BC856011}';
    CLSID_WICFormatConverterNChannel: TGUID = '{C17CABB2-D4A3-47D7-A557-339B2EFBD4F1}';
    CLSID_WICFormatConverterWMPhoto: TGUID = '{9CB5172B-D600-46BA-AB77-77BB7E3A00D9}';
    CLSID_WICPlanarFormatConverter: TGUID = '{184132B8-32F8-4784-9131-DD7224B23438}';


    WIC_JPEG_MAX_COMPONENT_COUNT = (4);

    WIC_JPEG_MAX_TABLE_INDEX = (3);

    WIC_JPEG_SAMPLE_FACTORS_ONE = ($11);

    WIC_JPEG_SAMPLE_FACTORS_THREE_420 = ($111122);

    WIC_JPEG_SAMPLE_FACTORS_THREE_422 = ($111121);

    WIC_JPEG_SAMPLE_FACTORS_THREE_440 = ($111112);

    WIC_JPEG_SAMPLE_FACTORS_THREE_444 = ($111111);

    WIC_JPEG_QUANTIZATION_BASELINE_ONE = (0);

    WIC_JPEG_QUANTIZATION_BASELINE_THREE = ($10100);

    WIC_JPEG_HUFFMAN_BASELINE_ONE = (0);

    WIC_JPEG_HUFFMAN_BASELINE_THREE = ($111100);


    GUID_WICPixelFormatDontCare: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC900}';
    GUID_WICPixelFormatUndefined: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC900}';// GUID_WICPixelFormatDontCare;
    GUID_WICPixelFormat1bppIndexed: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC901}';
    GUID_WICPixelFormat2bppIndexed: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC902}';
    GUID_WICPixelFormat4bppIndexed: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC903}';
    GUID_WICPixelFormat8bppIndexed: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC904}';
    GUID_WICPixelFormatBlackWhite: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC905}';
    GUID_WICPixelFormat2bppGray: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC906}';
    GUID_WICPixelFormat4bppGray: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC907}';
    GUID_WICPixelFormat8bppGray: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC908}';
    GUID_WICPixelFormat8bppAlpha: TGUID = '{E6CD0116-EEBA-4161-AA85-27DD9FB3A895}';
    GUID_WICPixelFormat8bppDepth: TGUID = '{4C9C9F45-1D89-4E31-9BC7-69343A0DCA69}';
    GUID_WICPixelFormat8bppGain: TGUID = '{A884022A-AF13-4C16-B746-619BF618B878}';
    GUID_WICPixelFormat24bppRGBGain: TGUID = '{A5022B24-7109-443B-9948-25B6ED8F39FD}';
    GUID_WICPixelFormat32bppBGRGain: TGUID = '{837D6738-208A-43E0-8995-79AB74407402}';
    GUID_WICPixelFormat16bppBGR555: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC909}';
    GUID_WICPixelFormat16bppBGR565: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC90A}';
    GUID_WICPixelFormat16bppBGRA5551: TGUID = '{05EC7C2B-F1E6-4961-AD46-E1CC810A87D2}';
    GUID_WICPixelFormat16bppGray: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC90B}';
    GUID_WICPixelFormat24bppBGR: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC90C}';
    GUID_WICPixelFormat24bppRGB: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC90D}';
    GUID_WICPixelFormat32bppBGR: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC90E}';
    GUID_WICPixelFormat32bppBGRA: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC90F}';
    GUID_WICPixelFormat32bppPBGRA: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC910}';
    GUID_WICPixelFormat32bppGrayFloat: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC911}';
    //    {$IF (_WIN32_WINNT>=_WIN32_WINNT_WIN8) OR defined(_WIN7_PLATFORM_UPDATE)}
    GUID_WICPixelFormat32bppRGB: TGUID = '{D98C6B95-3EFE-47D6-BB25-EB1748AB0CF1}';
    //    {$ENDIF}

    GUID_WICPixelFormat32bppRGBA: TGUID = '{F5C7AD2D-6A8D-43DD-A7A8-A29935261AE9}';
    GUID_WICPixelFormat32bppPRGBA: TGUID = '{3CC4A650-A527-4D37-A916-3142C7EBEDBA}';
    GUID_WICPixelFormat48bppRGB: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC915}';
    GUID_WICPixelFormat48bppBGR: TGUID = '{E605A384-B468-46CE-BB2E-36F180E64313}';
    //    {$IF (_WIN32_WINNT>=_WIN32_WINNT_WIN8) OR defined(_WIN7_PLATFORM_UPDATE)}
    GUID_WICPixelFormat64bppRGB: TGUID = '{A1182111-186D-4D42-BC6A-9C8303A8DFF9}';
    //    {$ENDIF}

    GUID_WICPixelFormat64bppRGBA: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC916}';
    GUID_WICPixelFormat64bppBGRA: TGUID = '{1562FF7C-D352-46F9-979E-42976B792246}';
    GUID_WICPixelFormat64bppPRGBA: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC917}';
    GUID_WICPixelFormat64bppPBGRA: TGUID = '{8C518E8E-A4EC-468B-AE70-C9A35A9C5530}';
    GUID_WICPixelFormat16bppGrayFixedPoint: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC913}';
    GUID_WICPixelFormat32bppBGR101010: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC914}';
    GUID_WICPixelFormat48bppRGBFixedPoint: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC912}';
    GUID_WICPixelFormat48bppBGRFixedPoint: TGUID = '{49CA140E-CAB6-493B-9DDF-60187C37532A}';
    GUID_WICPixelFormat96bppRGBFixedPoint: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC918}';
 //   {$IF (_WIN32_WINNT>=_WIN32_WINNT_WIN8) OR defined(_WIN7_PLATFORM_UPDATE)}
    GUID_WICPixelFormat96bppRGBFloat: TGUID = '{E3FED78F-E8DB-4ACF-84C1-E97F6136B327}';
//    {$ENDIF}

    GUID_WICPixelFormat128bppRGBAFloat: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC919}';
    GUID_WICPixelFormat128bppPRGBAFloat: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC91A}';
    GUID_WICPixelFormat128bppRGBFloat: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC91B}';
    GUID_WICPixelFormat32bppCMYK: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC91C}';
    GUID_WICPixelFormat64bppRGBAFixedPoint: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC91D}';
    GUID_WICPixelFormat64bppBGRAFixedPoint: TGUID = '{356DE33C-54D2-4A23-BB04-9B7BF9B1D42D}';
    GUID_WICPixelFormat64bppRGBFixedPoint: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC940}';
    GUID_WICPixelFormat128bppRGBAFixedPoint: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC91E}';
    GUID_WICPixelFormat128bppRGBFixedPoint: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC941}';
    GUID_WICPixelFormat64bppRGBAHalf: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC93A}';
//    {$IF (_WIN32_WINNT>=_WIN32_WINNT_WIN8) OR defined(_WIN7_PLATFORM_UPDATE)}
    GUID_WICPixelFormat64bppPRGBAHalf: TGUID = '{58AD26C2-C623-4D9D-B320-387E49F8C442}';
    //    {$ENDIF}

    GUID_WICPixelFormat64bppRGBHalf: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC942}';
    GUID_WICPixelFormat48bppRGBHalf: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC93B}';
    GUID_WICPixelFormat32bppRGBE: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC93D}';
    GUID_WICPixelFormat16bppGrayHalf: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC93E}';
    GUID_WICPixelFormat32bppGrayFixedPoint: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC93F}';
    GUID_WICPixelFormat32bppRGBA1010102: TGUID = '{25238D72-FCF9-4522-B514-5578E5AD55E0}';
    GUID_WICPixelFormat32bppRGBA1010102XR: TGUID = '{00DE6B9A-C101-434B-B502-D0165EE1122C}';
    GUID_WICPixelFormat32bppR10G10B10A2: TGUID = '{604E1BB5-8A3C-4B65-B11C-BC0B8DD75B7F}';
    GUID_WICPixelFormat32bppR10G10B10A2HDR10: TGUID = '{9C215C5D-1ACC-4F0E-A4BC-70FB3AE8FD28}';
    GUID_WICPixelFormat64bppCMYK: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC91F}';
    GUID_WICPixelFormat24bpp3Channels: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC920}';
    GUID_WICPixelFormat32bpp4Channels: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC921}';
    GUID_WICPixelFormat40bpp5Channels: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC922}';
    GUID_WICPixelFormat48bpp6Channels: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC923}';
    GUID_WICPixelFormat56bpp7Channels: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC924}';
    GUID_WICPixelFormat64bpp8Channels: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC925}';
    GUID_WICPixelFormat48bpp3Channels: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC926}';
    GUID_WICPixelFormat64bpp4Channels: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC927}';
    GUID_WICPixelFormat80bpp5Channels: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC928}';
    GUID_WICPixelFormat96bpp6Channels: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC929}';
    GUID_WICPixelFormat112bpp7Channels: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC92A}';
    GUID_WICPixelFormat128bpp8Channels: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC92B}';
    GUID_WICPixelFormat40bppCMYKAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC92C}';
    GUID_WICPixelFormat80bppCMYKAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC92D}';
    GUID_WICPixelFormat32bpp3ChannelsAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC92E}';
    GUID_WICPixelFormat40bpp4ChannelsAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC92F}';
    GUID_WICPixelFormat48bpp5ChannelsAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC930}';
    GUID_WICPixelFormat56bpp6ChannelsAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC931}';
    GUID_WICPixelFormat64bpp7ChannelsAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC932}';
    GUID_WICPixelFormat72bpp8ChannelsAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC933}';
    GUID_WICPixelFormat64bpp3ChannelsAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC934}';
    GUID_WICPixelFormat80bpp4ChannelsAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC935}';
    GUID_WICPixelFormat96bpp5ChannelsAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC936}';
    GUID_WICPixelFormat112bpp6ChannelsAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC937}';
    GUID_WICPixelFormat128bpp7ChannelsAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC938}';
    GUID_WICPixelFormat144bpp8ChannelsAlpha: TGUID = '{6FDDC324-4E03-4BFE-B185-3D77768DC939}';
    GUID_WICPixelFormat8bppY: TGUID = '{91B4DB54-2DF9-42F0-B449-2909BB3DF88E}';
    GUID_WICPixelFormat8bppCb: TGUID = '{1339F224-6BFE-4C3E-9302-E4F3A6D0CA2A}';
    GUID_WICPixelFormat8bppCr: TGUID = '{B8145053-2116-49F0-8835-ED844B205C51}';
    GUID_WICPixelFormat16bppCbCr: TGUID = '{FF95BA6E-11E0-4263-BB45-01721F3460A4}';
    GUID_WICPixelFormat16bppYQuantizedDctCoefficients: TGUID = '{A355F433-48E8-4A42-84D8-E2AA26CA80A4}';
    GUID_WICPixelFormat16bppCbQuantizedDctCoefficients: TGUID = '{D2C4FF61-56A5-49C2-8B5C-4C1925964837}';
    GUID_WICPixelFormat16bppCrQuantizedDctCoefficients: TGUID = '{2FE354F0-1680-42D8-9231-E73C0565BFC1}';


    IID_IWICPalette: TGUID = '{00000040-a8f2-4877-ba0a-fd2b6645fb94}';
    IID_IWICBitmapSource: TGUID = '{00000120-a8f2-4877-ba0a-fd2b6645fb94}';
    IID_IWICFormatConverter: TGUID = '{00000301-a8f2-4877-ba0a-fd2b6645fb94}';
    IID_IWICPlanarFormatConverter: TGUID = '{BEBEE9CB-83B0-4DCC-8132-B0AAA55EAC96}';
    IID_IWICBitmapScaler: TGUID = '{00000302-a8f2-4877-ba0a-fd2b6645fb94}';
    IID_IWICBitmapClipper: TGUID = '{E4FBCF03-223D-4e81-9333-D635556DD1B5}';
    IID_IWICBitmapFlipRotator: TGUID = '{5009834F-2D6A-41ce-9E1B-17C5AFF7A782}';
    IID_IWICBitmapToneMapper: TGUID = '{44728ded-1edf-4fe9-b50b-c89a264c9439}';
    IID_IWICBitmapLock: TGUID = '{00000123-a8f2-4877-ba0a-fd2b6645fb94}';
    IID_IWICBitmap: TGUID = '{00000121-a8f2-4877-ba0a-fd2b6645fb94}';
    IID_IWICColorContext: TGUID = '{3C613A02-34B2-44ea-9A7C-45AEA9C6FD6D}';
    IID_IWICColorTransform: TGUID = '{B66F034F-D0E2-40ab-B436-6DE39E321A94}';
    IID_IWICFastMetadataEncoder: TGUID = '{B84E2C09-78C9-4AC4-8BD3-524AE1663A2F}';
    IID_IWICStream: TGUID = '{135FF860-22B7-4ddf-B0F6-218F4F299A43}';
    IID_IWICEnumMetadataItem: TGUID = '{DC2BB46D-3F07-481E-8625-220C4AEDBB33}';
    IID_IWICMetadataQueryReader: TGUID = '{30989668-E1C9-4597-B395-458EEDB808DF}';
    IID_IWICMetadataQueryWriter: TGUID = '{A721791A-0DEF-4d06-BD91-2118BF1DB10B}';
    IID_IWICBitmapEncoder: TGUID = '{00000103-a8f2-4877-ba0a-fd2b6645fb94}';

    IID_IWICBitmapFrameEncode: TGUID = '{00000105-a8f2-4877-ba0a-fd2b6645fb94}';
    IID_IWICPlanarBitmapFrameEncode: TGUID = '{F928B7B8-2221-40C1-B72E-7E82F1974D1A}';
    IID_IWICImageEncoder: TGUID = '{04C75BF8-3CE1-473B-ACC5-3CC4F5E94999}';
    IID_IWICBitmapDecoder: TGUID = '{9EDDE9E7-8DEE-47ea-99DF-E6FAF2ED44BF}';


    IID_IWICBitmapSourceTransform: TGUID = '{3B16811B-6A43-4ec9-B713-3D5A0C13B940}';
    IID_IWICBitmapSourceTransform2: TGUID = '{c3373fdf-6d39-4e5f-8e79-bf40c0b7ed77}';
    IID_IWICPlanarBitmapSourceTransform: TGUID = '{3AFF9CCE-BE95-4303-B927-E7D16FF4A613}';
    IID_IWICBitmapFrameDecode: TGUID = '{3B16811B-6A43-4ec9-A813-3D930C13B940}';
    IID_IWICBitmapFrameChainReader: TGUID = '{0c599495-a120-4222-9130-a8c29410bd0b}';
    IID_IWICBitmapFrameChainWriter: TGUID = '{40d9ea28-4768-47b3-8c12-558a48e98e38}';
    IID_IWICProgressiveLevelControl: TGUID = '{DAAC296F-7AA5-4dbf-8D15-225C5976F891}';
    IID_IWICDisplayAdaptationControl: TGUID = '{de9d91d2-70b4-4f41-836c-25fcd39626d3}';
    IID_IWICDisplayAdaptationControl2: TGUID = '{d7508d29-3ab7-447e-a676-4d80d7de726b}';
    IID_IWICD3DTextureSource: TGUID = '{caf65cc4-8ebe-4718-a21f-8dbf40bb7e25}';
    IID_IWICProgressCallback: TGUID = '{4776F9CD-9517-45FA-BF24-E89C5EC5C60C}';


    IID_IWICBitmapCodecProgressNotification: TGUID = '{64C1024E-C3CF-4462-8078-88C2B11C46D9}';
    IID_IWICComponentInfo: TGUID = '{23BC3F0A-698B-4357-886B-F24D50671334}';
    IID_IWICFormatConverterInfo: TGUID = '{9F34FB65-13F4-4f15-BC57-3726B5E53D9F}';
    IID_IWICBitmapCodecInfo: TGUID = '{E87A44C4-B76E-4c47-8B09-298EB12A2714}';
    IID_IWICBitmapEncoderInfo: TGUID = '{94C9B4EE-A09F-4f92-8A1E-4A9BCE7E76FB}';
    IID_IWICBitmapDecoderInfo: TGUID = '{D8CD007F-D08F-4191-9BFC-236EA7F0E4B5}';


    IID_IWICPixelFormatInfo: TGUID = '{E8EDA601-3D48-431a-AB44-69059BE88BBE}';
    IID_IWICPixelFormatInfo2: TGUID = '{A9DB33A2-AF5F-43C7-B679-74F5984B5AA4}';
    IID_IWICImagingFactory: TGUID = '{ec5ec8a9-c395-4314-9c77-54d7a935ff70}';
    IID_IWICImagingFactory2: TGUID = '{7B816B45-1996-4476-B132-DE9E247C8AF0}';
    IID_IWICImagingFactory3: TGUID = '{489b3d8b-624a-4258-b678-7eece70f299d}';


    IID_IWICDevelopRawNotificationCallback: TGUID = '{95c75a6e-3e8c-4ec2-85a8-aebcc551e59b}';
    IID_IWICDevelopRaw: TGUID = '{fbec5e44-f7be-4b65-b7f8-c0c81fef026d}';
    IID_IWICDdsDecoder: TGUID = '{409cd537-8532-40cb-9774-e2feb2df4e9c}';
    IID_IWICDdsEncoder: TGUID = '{5cacdb4c-407e-41b3-b936-d0f010cd6732}';
    IID_IWICDdsFrameDecode: TGUID = '{3d4c0c61-18a4-41e4-bd80-481a4fc9f464}';
    IID_IWICJpegFrameDecode: TGUID = '{8939F66E-C46A-4c21-A9D1-98B327CE1679}';
    IID_IWICJpegFrameEncode: TGUID = '{2F0C601F-D2C6-468C-ABFA-49495D983ED1}';


    FACILITY_WINCODEC_ERR = $898;
    WINCODEC_ERR_BASE = $2000;
    INTSAFE_E_ARITHMETIC_OVERFLOW = HRESULT($80070216);  // 0x216 = 534 = ERROR_ARITHMETIC_OVERFLOW

    WINCODEC_ERR_GENERIC_ERROR = E_FAIL;
    WINCODEC_ERR_INVALIDPARAMETER = E_INVALIDARG;
    WINCODEC_ERR_OUTOFMEMORY = E_OUTOFMEMORY;
    WINCODEC_ERR_NOTIMPLEMENTED = E_NOTIMPL;
    WINCODEC_ERR_ABORTED = E_ABORT;
    WINCODEC_ERR_ACCESSDENIED = E_ACCESSDENIED;
    WINCODEC_ERR_VALUEOVERFLOW = INTSAFE_E_ARITHMETIC_OVERFLOW;


    WICRawChangeNotification_ExposureCompensation = $00000001;
    WICRawChangeNotification_NamedWhitePoint = $00000002;
    WICRawChangeNotification_KelvinWhitePoint = $00000004;
    WICRawChangeNotification_RGBWhitePoint = $00000008;
    WICRawChangeNotification_Contrast = $00000010;
    WICRawChangeNotification_Gamma = $00000020;
    WICRawChangeNotification_Sharpness = $00000040;
    WICRawChangeNotification_Saturation = $00000080;
    WICRawChangeNotification_Tint = $00000100;
    WICRawChangeNotification_NoiseReduction = $00000200;
    WICRawChangeNotification_DestinationColorContext = $00000400;
    WICRawChangeNotification_ToneCurve = $00000800;
    WICRawChangeNotification_Rotation = $00001000;
    WICRawChangeNotification_RenderMode = $00002000;


type


    REFGUID = ^TGUID;
    REFIID = ^TGUID;
    REFCLSID = ^CLSID;

    (* Forward Declarations *)

    IWICPalette = interface;
    IWICBitmapSource = interface;
    IWICFormatConverter = interface;
    IWICPlanarFormatConverter = interface;
    IWICBitmapScaler = interface;
    IWICBitmapClipper = interface;
    IWICBitmapFlipRotator = interface;
    IWICBitmapToneMapper = interface;
    IWICBitmapLock = interface;
    IWICBitmap = interface;
    IWICColorContext = interface;
    IWICColorTransform = interface;
    IWICFastMetadataEncoder = interface;
    IWICStream = interface;
    IWICEnumMetadataItem = interface;
    IWICMetadataQueryReader = interface;
    IWICMetadataQueryWriter = interface;
    IWICBitmapEncoder = interface;
    IWICBitmapFrameEncode = interface;
    IWICPlanarBitmapFrameEncode = interface;

    IWICBitmapDecoder = interface;
    IWICBitmapSourceTransform = interface;
    IWICBitmapSourceTransform2 = interface;
    IWICPlanarBitmapSourceTransform = interface;
    IWICBitmapFrameDecode = interface;
    IWICBitmapFrameChainReader = interface;
    IWICBitmapFrameChainWriter = interface;
    IWICProgressiveLevelControl = interface;
    IWICDisplayAdaptationControl = interface;
    IWICDisplayAdaptationControl2 = interface;
    IWICD3DTextureSource = interface;
    IWICProgressCallback = interface;
    IWICBitmapCodecProgressNotification = interface;
    IWICComponentInfo = interface;
    IWICFormatConverterInfo = interface;
    IWICBitmapCodecInfo = interface;
    IWICBitmapEncoderInfo = interface;
    IWICBitmapDecoderInfo = interface;
    IWICPixelFormatInfo = interface;
    IWICPixelFormatInfo2 = interface;
    IWICImagingFactory = interface;

    IWICDevelopRawNotificationCallback = interface;
    IWICDevelopRaw = interface;
    IWICDdsDecoder = interface;
    IWICDdsEncoder = interface;
    IWICDdsFrameDecode = interface;
    IWICJpegFrameDecode = interface;
    IWICJpegFrameEncode = interface;


    TWICColor = uint32;
    PWICColor = ^TWICColor;

    { TWICRect }

    TWICRect = record
        X: int32;
        Y: int32;
        Width: int32;
        Height: int32;
        procedure Init(x,y,w,h: int32);
    end;
    PWICRect = ^TWICRect;


    TWICInProcPointer = pbyte;
    PWICInProcPointer = ^TWICInProcPointer;

    TWICColorContextType = (
        WICColorContextUninitialized = 0,
        WICColorContextProfile = $1,
        WICColorContextExifColorSpace = $2);

    PWICColorContextType = ^TWICColorContextType;


    TREFWICPixelFormatGUID = REFGUID;

    TWICPixelFormatGUID = TGUID;
    PWICPixelFormatGUID = ^TWICPixelFormatGUID;


    TWICBitmapCreateCacheOption = (
        WICBitmapNoCache = 0,
        WICBitmapCacheOnDemand = $1,
        WICBitmapCacheOnLoad = $2,
        WICBITMAPCREATECACHEOPTION_FORCE_DWORD = $7fffffff);

    PWICBitmapCreateCacheOption = ^TWICBitmapCreateCacheOption;


    TWICDecodeOptions = (
        WICDecodeMetadataCacheOnDemand = 0,
        WICDecodeMetadataCacheOnLoad = $1,
        WICMETADATACACHEOPTION_FORCE_DWORD = $7fffffff);

    PWICDecodeOptions = ^TWICDecodeOptions;


    TWICBitmapEncoderCacheOption = (
        WICBitmapEncoderCacheInMemory = 0,
        WICBitmapEncoderCacheTempFile = $1,
        WICBitmapEncoderNoCache = $2,
        WICBITMAPENCODERCACHEOPTION_FORCE_DWORD = $7fffffff);

    PWICBitmapEncoderCacheOption = ^TWICBitmapEncoderCacheOption;


    TWICComponentType = (
        WICDecoder = $1,
        WICEncoder = $2,
        WICPixelFormatConverter = $4,
        WICMetadataReader = $8,
        WICMetadataWriter = $10,
        WICPixelFormat = $20,
        WICAllComponents = $3f,
        WICCOMPONENTTYPE_FORCE_DWORD = $7fffffff);

    PWICComponentType = ^TWICComponentType;


    TWICComponentEnumerateOptions = (
        WICComponentEnumerateDefault = 0,
        WICComponentEnumerateRefresh = $1,
        WICComponentEnumerateDisabled = $80000000,
        WICComponentEnumerateUnsigned = $40000000,
        WICComponentEnumerateBuiltInOnly = $20000000,
        WICCOMPONENTENUMERATEOPTIONS_FORCE_DWORD = $7fffffff);

    PWICComponentEnumerateOptions = ^TWICComponentEnumerateOptions;


    TWICBitmapPattern = record
        Position: ULARGE_INTEGER;
        Length: ULONG; (* [size_is] *)
        Pattern: pbyte; (* [size_is] *)
        Mask: pbyte;
        EndOfStream: winbool;
    end;
    PWICBitmapPattern = ^TWICBitmapPattern;


    TWICBitmapInterpolationMode = (
        WICBitmapInterpolationModeNearestNeighbor = 0,
        WICBitmapInterpolationModeLinear = $1,
        WICBitmapInterpolationModeCubic = $2,
        WICBitmapInterpolationModeFant = $3,
        WICBitmapInterpolationModeHighQualityCubic = $4,
        WICBITMAPINTERPOLATIONMODE_FORCE_DWORD = $7fffffff);

    PWICBitmapInterpolationMode = ^TWICBitmapInterpolationMode;


    TWICBitmapPaletteType = (
        WICBitmapPaletteTypeCustom = 0,
        WICBitmapPaletteTypeMedianCut = $1,
        WICBitmapPaletteTypeFixedBW = $2,
        WICBitmapPaletteTypeFixedHalftone8 = $3,
        WICBitmapPaletteTypeFixedHalftone27 = $4,
        WICBitmapPaletteTypeFixedHalftone64 = $5,
        WICBitmapPaletteTypeFixedHalftone125 = $6,
        WICBitmapPaletteTypeFixedHalftone216 = $7,
        WICBitmapPaletteTypeFixedWebPalette = WICBitmapPaletteTypeFixedHalftone216,
        WICBitmapPaletteTypeFixedHalftone252 = $8,
        WICBitmapPaletteTypeFixedHalftone256 = $9,
        WICBitmapPaletteTypeFixedGray4 = $a,
        WICBitmapPaletteTypeFixedGray16 = $b,
        WICBitmapPaletteTypeFixedGray256 = $c,
        WICBITMAPPALETTETYPE_FORCE_DWORD = $7fffffff);

    PWICBitmapPaletteType = ^TWICBitmapPaletteType;


    TWICBitmapDitherType = (
        WICBitmapDitherTypeNone = 0,
        WICBitmapDitherTypeSolid = 0,
        WICBitmapDitherTypeOrdered4x4 = $1,
        WICBitmapDitherTypeOrdered8x8 = $2,
        WICBitmapDitherTypeOrdered16x16 = $3,
        WICBitmapDitherTypeSpiral4x4 = $4,
        WICBitmapDitherTypeSpiral8x8 = $5,
        WICBitmapDitherTypeDualSpiral4x4 = $6,
        WICBitmapDitherTypeDualSpiral8x8 = $7,
        WICBitmapDitherTypeErrorDiffusion = $8,
        WICBITMAPDITHERTYPE_FORCE_DWORD = $7fffffff);

    PWICBitmapDitherType = ^TWICBitmapDitherType;


    TWICBitmapAlphaChannelOption = (
        WICBitmapUseAlpha = 0,
        WICBitmapUsePremultipliedAlpha = $1,
        WICBitmapIgnoreAlpha = $2,
        WICBITMAPALPHACHANNELOPTIONS_FORCE_DWORD = $7fffffff);

    PWICBitmapAlphaChannelOption = ^TWICBitmapAlphaChannelOption;


    TWICBitmapTransformOptions = (
        WICBitmapTransformRotate0 = 0,
        WICBitmapTransformRotate90 = $1,
        WICBitmapTransformRotate180 = $2,
        WICBitmapTransformRotate270 = $3,
        WICBitmapTransformFlipHorizontal = $8,
        WICBitmapTransformFlipVertical = $10,
        WICBITMAPTRANSFORMOPTIONS_FORCE_DWORD = $7fffffff);

    PWICBitmapTransformOptions = ^TWICBitmapTransformOptions;


    TWICBitmapLockFlags = (
        WICBitmapLockRead = $1,
        WICBitmapLockWrite = $2,
        WICBITMAPLOCKFLAGS_FORCE_DWORD = $7fffffff);

    PWICBitmapLockFlags = ^TWICBitmapLockFlags;


    TWICBitmapDecoderCapabilities = (
        WICBitmapDecoderCapabilitySameEncoder = $1,
        WICBitmapDecoderCapabilityCanDecodeAllImages = $2,
        WICBitmapDecoderCapabilityCanDecodeSomeImages = $4,
        WICBitmapDecoderCapabilityCanEnumerateMetadata = $8,
        WICBitmapDecoderCapabilityCanDecodeThumbnail = $10,
        WICBITMAPDECODERCAPABILITIES_FORCE_DWORD = $7fffffff);

    PWICBitmapDecoderCapabilities = ^TWICBitmapDecoderCapabilities;


    TWICProgressOperation = (
        WICProgressOperationCopyPixels = $1,
        WICProgressOperationWritePixels = $2,
        WICProgressOperationAll = $ffff,
        WICPROGRESSOPERATION_FORCE_DWORD = $7fffffff);

    PWICProgressOperation = ^TWICProgressOperation;


    TWICProgressNotification = (
        WICProgressNotificationBegin = $10000,
        WICProgressNotificationEnd = $20000,
        WICProgressNotificationFrequent = $40000,
        WICProgressNotificationAll = $ffff0000,
        WICPROGRESSNOTIFICATION_FORCE_DWORD = $7fffffff);

    PWICProgressNotification = ^TWICProgressNotification;


    TWICComponentSigning = (
        WICComponentSigned = $1,
        WICComponentUnsigned = $2,
        WICComponentSafe = $4,
        WICComponentDisabled = $80000000,
        WICCOMPONENTSIGNING_FORCE_DWORD = $7fffffff);

    PWICComponentSigning = ^TWICComponentSigning;


    TWICBitmapToneMappingMode = (
        WICBitmapToneMappingMode_None = 0,
        WICBitmapToneMappingMode_Default = $1,
        WICBitmapToneMappingMode_D2D = $2,
        WICBitmapToneMappingMode_GainMap = $3,
        WICBITMAPTONEMAPPINGMODE_FORCE_DWORD = $7fffffff);

    PWICBitmapToneMappingMode = ^TWICBitmapToneMappingMode;


    TWICBitmapChainType = (
        WICBitmapChainType_Alternate = $1,
        WICBitmapChainType_Layer = $2,
        WICBitmapChainType_Preview = $3,
        WICBitmapChainType_Thumbnail = $4,
        WICBitmapChainType_AlphaMap = $5,
        WICBitmapChainType_DepthMap = $6,
        WICBitmapChainType_GainMap = $7,
        WICBITMAPCHAINTYPE_FORCE_DWORD = $7fffffff);

    PWICBitmapChainType = ^TWICBitmapChainType;


    TWICGifLogicalScreenDescriptorProperties = (
        WICGifLogicalScreenSignature = $1,
        WICGifLogicalScreenDescriptorWidth = $2,
        WICGifLogicalScreenDescriptorHeight = $3,
        WICGifLogicalScreenDescriptorGlobalColorTableFlag = $4,
        WICGifLogicalScreenDescriptorColorResolution = $5,
        WICGifLogicalScreenDescriptorSortFlag = $6,
        WICGifLogicalScreenDescriptorGlobalColorTableSize = $7,
        WICGifLogicalScreenDescriptorBackgroundColorIndex = $8,
        WICGifLogicalScreenDescriptorPixelAspectRatio = $9,
        WICGifLogicalScreenDescriptorProperties_FORCE_DWORD = $7fffffff);

    PWICGifLogicalScreenDescriptorProperties = ^TWICGifLogicalScreenDescriptorProperties;


    TWICGifImageDescriptorProperties = (
        WICGifImageDescriptorLeft = $1,
        WICGifImageDescriptorTop = $2,
        WICGifImageDescriptorWidth = $3,
        WICGifImageDescriptorHeight = $4,
        WICGifImageDescriptorLocalColorTableFlag = $5,
        WICGifImageDescriptorInterlaceFlag = $6,
        WICGifImageDescriptorSortFlag = $7,
        WICGifImageDescriptorLocalColorTableSize = $8,
        WICGifImageDescriptorProperties_FORCE_DWORD = $7fffffff);

    PWICGifImageDescriptorProperties = ^TWICGifImageDescriptorProperties;


    TWICGifGraphicControlExtensionProperties = (
        WICGifGraphicControlExtensionDisposal = $1,
        WICGifGraphicControlExtensionUserInputFlag = $2,
        WICGifGraphicControlExtensionTransparencyFlag = $3,
        WICGifGraphicControlExtensionDelay = $4,
        WICGifGraphicControlExtensionTransparentColorIndex = $5,
        WICGifGraphicControlExtensionProperties_FORCE_DWORD = $7fffffff);

    PWICGifGraphicControlExtensionProperties = ^TWICGifGraphicControlExtensionProperties;


    TWICGifApplicationExtensionProperties = (
        WICGifApplicationExtensionApplication = $1,
        WICGifApplicationExtensionData = $2,
        WICGifApplicationExtensionProperties_FORCE_DWORD = $7fffffff);

    PWICGifApplicationExtensionProperties = ^TWICGifApplicationExtensionProperties;


    TWICGifCommentExtensionProperties = (
        WICGifCommentExtensionText = $1,
        WICGifCommentExtensionProperties_FORCE_DWORD = $7fffffff);

    PWICGifCommentExtensionProperties = ^TWICGifCommentExtensionProperties;


    TWICJpegCommentProperties = (
        WICJpegCommentText = $1,
        WICJpegCommentProperties_FORCE_DWORD = $7fffffff);

    PWICJpegCommentProperties = ^TWICJpegCommentProperties;


    TWICJpegLuminanceProperties = (
        WICJpegLuminanceTable = $1,
        WICJpegLuminanceProperties_FORCE_DWORD = $7fffffff);

    PWICJpegLuminanceProperties = ^TWICJpegLuminanceProperties;


    TWICJpegChrominanceProperties = (
        WICJpegChrominanceTable = $1,
        WICJpegChrominanceProperties_FORCE_DWORD = $7fffffff);

    PWICJpegChrominanceProperties = ^TWICJpegChrominanceProperties;


    TWIC8BIMIptcProperties = (
        WIC8BIMIptcPString = 0,
        WIC8BIMIptcEmbeddedIPTC = $1,
        WIC8BIMIptcProperties_FORCE_DWORD = $7fffffff);

    PWIC8BIMIptcProperties = ^TWIC8BIMIptcProperties;


    TWIC8BIMResolutionInfoProperties = (
        WIC8BIMResolutionInfoPString = $1,
        WIC8BIMResolutionInfoHResolution = $2,
        WIC8BIMResolutionInfoHResolutionUnit = $3,
        WIC8BIMResolutionInfoWidthUnit = $4,
        WIC8BIMResolutionInfoVResolution = $5,
        WIC8BIMResolutionInfoVResolutionUnit = $6,
        WIC8BIMResolutionInfoHeightUnit = $7,
        WIC8BIMResolutionInfoProperties_FORCE_DWORD = $7fffffff);

    PWIC8BIMResolutionInfoProperties = ^TWIC8BIMResolutionInfoProperties;


    TWIC8BIMIptcDigestProperties = (
        WIC8BIMIptcDigestPString = $1,
        WIC8BIMIptcDigestIptcDigest = $2,
        WIC8BIMIptcDigestProperties_FORCE_DWORD = $7fffffff);

    PWIC8BIMIptcDigestProperties = ^TWIC8BIMIptcDigestProperties;


    TWICPngGamaProperties = (
        WICPngGamaGamma = $1,
        WICPngGamaProperties_FORCE_DWORD = $7fffffff);

    PWICPngGamaProperties = ^TWICPngGamaProperties;


    TWICPngBkgdProperties = (
        WICPngBkgdBackgroundColor = $1,
        WICPngBkgdProperties_FORCE_DWORD = $7fffffff);

    PWICPngBkgdProperties = ^TWICPngBkgdProperties;


    TWICPngItxtProperties = (
        WICPngItxtKeyword = $1,
        WICPngItxtCompressionFlag = $2,
        WICPngItxtLanguageTag = $3,
        WICPngItxtTranslatedKeyword = $4,
        WICPngItxtText = $5,
        WICPngItxtProperties_FORCE_DWORD = $7fffffff);

    PWICPngItxtProperties = ^TWICPngItxtProperties;


    TWICPngChrmProperties = (
        WICPngChrmWhitePointX = $1,
        WICPngChrmWhitePointY = $2,
        WICPngChrmRedX = $3,
        WICPngChrmRedY = $4,
        WICPngChrmGreenX = $5,
        WICPngChrmGreenY = $6,
        WICPngChrmBlueX = $7,
        WICPngChrmBlueY = $8,
        WICPngChrmProperties_FORCE_DWORD = $7fffffff);

    PWICPngChrmProperties = ^TWICPngChrmProperties;


    TWICPngHistProperties = (
        WICPngHistFrequencies = $1,
        WICPngHistProperties_FORCE_DWORD = $7fffffff);

    PWICPngHistProperties = ^TWICPngHistProperties;


    TWICPngIccpProperties = (
        WICPngIccpProfileName = $1,
        WICPngIccpProfileData = $2,
        WICPngIccpProperties_FORCE_DWORD = $7fffffff);

    PWICPngIccpProperties = ^TWICPngIccpProperties;


    TWICPngSrgbProperties = (
        WICPngSrgbRenderingIntent = $1,
        WICPngSrgbProperties_FORCE_DWORD = $7fffffff);

    PWICPngSrgbProperties = ^TWICPngSrgbProperties;


    TWICPngTimeProperties = (
        WICPngTimeYear = $1,
        WICPngTimeMonth = $2,
        WICPngTimeDay = $3,
        WICPngTimeHour = $4,
        WICPngTimeMinute = $5,
        WICPngTimeSecond = $6,
        WICPngTimeProperties_FORCE_DWORD = $7fffffff);

    PWICPngTimeProperties = ^TWICPngTimeProperties;


    TWICHeifProperties = (
        WICHeifOrientation = $1,
        WICHeifLayeredImageCanvasColor = $2,
        WICHeifLayeredImageLayerPositions = $3,
        WICHeifProperties_FORCE_DWORD = $7fffffff);

    PWICHeifProperties = ^TWICHeifProperties;


    TWICHeifHdrProperties = (
        WICHeifHdrMaximumLuminanceLevel = $1,
        WICHeifHdrMaximumFrameAverageLuminanceLevel = $2,
        WICHeifHdrMinimumMasteringDisplayLuminanceLevel = $3,
        WICHeifHdrMaximumMasteringDisplayLuminanceLevel = $4,
        WICHeifHdrCustomVideoPrimaries = $5,
        WICHeifHdrProperties_FORCE_DWORD = $7fffffff);

    PWICHeifHdrProperties = ^TWICHeifHdrProperties;


    TWICWebpAnimProperties = (
        WICWebpAnimLoopCount = $1,
        WICWebpAnimProperties_FORCE_DWORD = $7fffffff);

    PWICWebpAnimProperties = ^TWICWebpAnimProperties;


    TWICWebpAnmfProperties = (
        WICWebpAnmfFrameDuration = $1,
        WICWebpAnmfProperties_FORCE_DWORD = $7fffffff);

    PWICWebpAnmfProperties = ^TWICWebpAnmfProperties;


    TWICJpegXLAnimProperties = (
        WICJpegXLAnimLoopCount = $1,
        WICJpegXLAnimFrameTicksPerSecondNumerator = $2,
        WICJpegXLAnimFrameTicksPerSecondDenominator = $3,
        WICJpegXLAnimProperties_FORCE_DWORD = $7fffffff);

    PWICJpegXLAnimProperties = ^TWICJpegXLAnimProperties;


    TWICJpegXLAnimFrameProperties = (
        WICJpegXLAnimFrameDurationInTicks = $1,
        WICJpegXLAnimFrameName = $2,
        WICJpegXLAnimFrameProperties_FORCE_DWORD = $7fffffff);

    PWICJpegXLAnimFrameProperties = ^TWICJpegXLAnimFrameProperties;


    TWICGainMapProperties = (
        WICGainMapMetadata = $1,
        WICGainMapProperties_FORCE_DWORD = $7fffffff);

    PWICGainMapProperties = ^TWICGainMapProperties;


    TWICSectionAccessLevel = (
        WICSectionAccessLevelRead = $1,
        WICSectionAccessLevelReadWrite = $3,
        WICSectionAccessLevel_FORCE_DWORD = $7fffffff);

    PWICSectionAccessLevel = ^TWICSectionAccessLevel;


    TWICPixelFormatNumericRepresentation = (
        WICPixelFormatNumericRepresentationUnspecified = 0,
        WICPixelFormatNumericRepresentationIndexed = $1,
        WICPixelFormatNumericRepresentationUnsignedInteger = $2,
        WICPixelFormatNumericRepresentationSignedInteger = $3,
        WICPixelFormatNumericRepresentationFixed = $4,
        WICPixelFormatNumericRepresentationFloat = $5,
        WICPixelFormatNumericRepresentation_FORCE_DWORD = $7fffffff);

    PWICPixelFormatNumericRepresentation = ^TWICPixelFormatNumericRepresentation;


    TWICPlanarOptions = (
        WICPlanarOptionsDefault = 0,
        WICPlanarOptionsPreserveSubsampling = $1,
        WICPLANAROPTIONS_FORCE_DWORD = $7fffffff);

    PWICPlanarOptions = ^TWICPlanarOptions;


    TWICJpegIndexingOptions = (
        WICJpegIndexingOptionsGenerateOnDemand = 0,
        WICJpegIndexingOptionsGenerateOnLoad = $1,
        WICJpegIndexingOptions_FORCE_DWORD = $7fffffff);

    PWICJpegIndexingOptions = ^TWICJpegIndexingOptions;


    TWICJpegTransferMatrix = (
        WICJpegTransferMatrixIdentity = 0,
        WICJpegTransferMatrixBT601 = $1,
        WICJpegTransferMatrix_FORCE_DWORD = $7fffffff);

    PWICJpegTransferMatrix = ^TWICJpegTransferMatrix;


    TWICJpegScanType = (
        WICJpegScanTypeInterleaved = 0,
        WICJpegScanTypePlanarComponents = $1,
        WICJpegScanTypeProgressive = $2,
        WICJpegScanType_FORCE_DWORD = $7fffffff);

    PWICJpegScanType = ^TWICJpegScanType;


    TWICImageParameters = record
        PixelFormat: TD2D1_PIXEL_FORMAT;
        DpiX: single;
        DpiY: single;
        Top: single;
        Left: single;
        PixelWidth: uint32;
        PixelHeight: uint32;
    end;
    PWICImageParameters = ^TWICImageParameters;


    TWICBitmapPlaneDescription = record
        Format: TWICPixelFormatGUID;
        Width: UINT;
        Height: UINT;
    end;
    PWICBitmapPlaneDescription = ^TWICBitmapPlaneDescription;


    TWICBitmapPlane = record
        Format: TWICPixelFormatGUID;
        pbBuffer: pbyte;             (* [size_is] *)
        cbStride: UINT;
        cbBufferSize: UINT;
    end;
    PWICBitmapPlane = ^TWICBitmapPlane;


    TWICJpegFrameHeader = record
        Width: UINT;
        Height: UINT;
        TransferMatrix: TWICJpegTransferMatrix;
        ScanType: TWICJpegScanType;
        cComponents: UINT; (* [range] *)
        ComponentIdentifiers: DWORD;
        SampleFactors: DWORD;
        QuantizationTableIndices: DWORD;
    end;
    PWICJpegFrameHeader = ^TWICJpegFrameHeader;


    TWICJpegScanHeader = record
        cComponents: UINT; (* [range] *)
        RestartInterval: UINT;
        ComponentSelectors: DWORD;
        HuffmanTableIndices: DWORD;
        StartSpectralSelection: TBYTE;
        EndSpectralSelection: TBYTE;
        SuccessiveApproximationHigh: TBYTE;
        SuccessiveApproximationLow: TBYTE;
    end;
    PWICJpegScanHeader = ^TWICJpegScanHeader;


    IWICPalette = interface(IUnknown)
        ['{00000040-a8f2-4877-ba0a-fd2b6645fb94}']
        function InitializePredefined(ePaletteType: TWICBitmapPaletteType; fAddTransparentColor: winbool): HRESULT; stdcall;
        function InitializeCustom(
        {__RPC__in_ecount_full(cCount) } pColors: PWICColor; cCount: UINT): HRESULT; stdcall;
        function InitializeFromBitmap(
        {__RPC__in_opt } pISurface: IWICBitmapSource; cCount: UINT; fAddTransparentColor: winbool): HRESULT; stdcall;
        function InitializeFromPalette(
        {__RPC__in_opt } pIPalette: IWICPalette): HRESULT; stdcall;
        function GetType(
        {__RPC__out } pePaletteType: PWICBitmapPaletteType): HRESULT; stdcall;
        function GetColorCount(
        {__RPC__out } pcCount: PUINT): HRESULT; stdcall;
        function GetColors(cCount: UINT;
        {__RPC__out_ecount_full(cCount) } pColors: PWICColor;
        {__RPC__out } pcActualColors: PUINT): HRESULT; stdcall;
        function IsBlackWhite(
        {__RPC__out } pfIsBlackWhite: Pwinbool): HRESULT; stdcall;
        function IsGrayscale(
        {__RPC__out } pfIsGrayscale: Pwinbool): HRESULT; stdcall;
        function HasAlpha(
        {__RPC__out } pfHasAlpha: Pwinbool): HRESULT; stdcall;
    end;


    IWICBitmapSource = interface(IUnknown)
        ['{00000120-a8f2-4877-ba0a-fd2b6645fb94}']
        function GetSize(
        {__RPC__out } puiWidth: PUINT;
        {__RPC__out } puiHeight: PUINT): HRESULT; stdcall;
        function GetPixelFormat(
        {__RPC__out } pPixelFormat: PWICPixelFormatGUID): HRESULT; stdcall;
        function GetResolution(
        {__RPC__out } pDpiX: Pdouble;
        {__RPC__out } pDpiY: Pdouble): HRESULT; stdcall;
        function CopyPalette(
        {__RPC__in_opt } pIPalette: IWICPalette): HRESULT; stdcall;
        function CopyPixels(
        {__RPC__in_opt } prc: PWICRect; cbStride: UINT; cbBufferSize: UINT;
        {__RPC__out_ecount_full(cbBufferSize) } pbBuffer: pbyte): HRESULT; stdcall;

    end;

    PIWICBitmapSource = ^IWICBitmapSource;


    IWICFormatConverter = interface(IWICBitmapSource)
        ['{00000301-a8f2-4877-ba0a-fd2b6645fb94}']
        function Initialize(
        {__RPC__in_opt } pISource: IWICBitmapSource;
        {__RPC__in } dstFormat: TREFWICPixelFormatGUID; dither: TWICBitmapDitherType;
        {__RPC__in_opt } pIPalette: IWICPalette; alphaThresholdPercent: double; paletteTranslate: TWICBitmapPaletteType): HRESULT; stdcall;

        function CanConvert(
        {__RPC__in } srcPixelFormat: TREFWICPixelFormatGUID;
        {__RPC__in } dstPixelFormat: TREFWICPixelFormatGUID;
        {__RPC__out } pfCanConvert: Pwinbool): HRESULT; stdcall;

    end;


    IWICPlanarFormatConverter = interface(IWICBitmapSource)
        ['{BEBEE9CB-83B0-4DCC-8132-B0AAA55EAC96}']
        function Initialize(
        {__RPC__in_ecount_full(cPlanes) } ppPlanes: PIWICBitmapSource; cPlanes: UINT;
        {__RPC__in } dstFormat: TREFWICPixelFormatGUID; dither: TWICBitmapDitherType;
        {__RPC__in_opt } pIPalette: IWICPalette; alphaThresholdPercent: double; paletteTranslate: TWICBitmapPaletteType): HRESULT; stdcall;

        function CanConvert(
        {__RPC__in_ecount_full(cSrcPlanes) } pSrcPixelFormats: PWICPixelFormatGUID; cSrcPlanes: UINT;
        {__RPC__in } dstPixelFormat: TREFWICPixelFormatGUID;
        {__RPC__out } pfCanConvert: Pwinbool): HRESULT; stdcall;

    end;


    IWICBitmapScaler = interface(IWICBitmapSource)
        ['{00000302-a8f2-4877-ba0a-fd2b6645fb94}']
        function Initialize(
        {__RPC__in_opt } pISource: IWICBitmapSource; uiWidth: UINT; uiHeight: UINT; mode: TWICBitmapInterpolationMode): HRESULT; stdcall;

    end;


    IWICBitmapClipper = interface(IWICBitmapSource)
        ['{E4FBCF03-223D-4e81-9333-D635556DD1B5}']
        function Initialize(
        {__RPC__in_opt } pISource: IWICBitmapSource;
        {__RPC__in } prc: PWICRect): HRESULT; stdcall;

    end;


    IWICBitmapFlipRotator = interface(IWICBitmapSource)
        ['{5009834F-2D6A-41ce-9E1B-17C5AFF7A782}']
        function Initialize(
        {__RPC__in_opt } pISource: IWICBitmapSource; options: TWICBitmapTransformOptions): HRESULT; stdcall;

    end;


    IWICBitmapToneMapper = interface(IWICBitmapSource)
        ['{44728ded-1edf-4fe9-b50b-c89a264c9439}']
        function InitializeForHdrTarget(
        {__RPC__in_opt } pISource: IWICBitmapSource;
        {__RPC__in } guidDstFormat: TREFWICPixelFormatGUID; fLuminanceInNits: single; fWhiteLevelInNits: single; mode: TWICBitmapToneMappingMode): HRESULT; stdcall;

        function InitializeForSdrTarget(
        {__RPC__in_opt } pISource: IWICBitmapSource;
        {__RPC__in } guidDstFormat: TREFWICPixelFormatGUID; mode: TWICBitmapToneMappingMode): HRESULT; stdcall;

    end;


    IWICBitmapLock = interface(IUnknown)
        ['{00000123-a8f2-4877-ba0a-fd2b6645fb94}']
        function GetSize(
        {__RPC__out } puiWidth: PUINT;
        {__RPC__out } puiHeight: PUINT): HRESULT; stdcall;

        function GetStride(
        {__RPC__out } pcbStride: PUINT): HRESULT; stdcall;

        function GetDataPointer(
        {__RPC__out } pcbBufferSize: PUINT;
        { __RPC__deref_out_ecount_full_opt(*pcbBufferSize)}  ppbData: PWICInProcPointer): HRESULT; stdcall;

        function GetPixelFormat(
        {__RPC__out } pPixelFormat: PWICPixelFormatGUID): HRESULT; stdcall;

    end;


    IWICBitmap = interface(IWICBitmapSource)
        ['{00000121-a8f2-4877-ba0a-fd2b6645fb94}']
        function Lock(
        {__RPC__in_opt } prcLock: PWICRect; flags: DWORD;{__RPC__deref_out_opt} out ppILock: IWICBitmapLock): HRESULT; stdcall;

        function SetPalette(
        {__RPC__in_opt } pIPalette: IWICPalette): HRESULT; stdcall;

        function SetResolution(dpiX: double; dpiY: double): HRESULT; stdcall;

    end;


    IWICColorContext = interface(IUnknown)
        ['{3C613A02-34B2-44ea-9A7C-45AEA9C6FD6D}']
        function InitializeFromFilename(
        {__RPC__in } wzFilename: LPCWSTR): HRESULT; stdcall;

        function InitializeFromMemory(
        {__RPC__in_ecount_full(cbBufferSize) } pbBuffer: pbyte; cbBufferSize: UINT): HRESULT; stdcall;

        function InitializeFromExifColorSpace(Value: UINT): HRESULT; stdcall;

        function GetType(
        {__RPC__out } pType: PWICColorContextType): HRESULT; stdcall;

        function GetProfileBytes(cbBuffer: UINT;
        {__RPC__inout_ecount_full_opt(cbBuffer) } pbBuffer: pbyte;
        {__RPC__out } pcbActual: PUINT): HRESULT; stdcall;

        function GetExifColorSpace(
        {__RPC__out } pValue: PUINT): HRESULT; stdcall;

    end;

    PIWICColorContext = ^IWICColorContext;


    IWICColorTransform = interface(IWICBitmapSource)
        ['{B66F034F-D0E2-40ab-B436-6DE39E321A94}']
        function Initialize(
        {__RPC__in_opt } pIBitmapSource: IWICBitmapSource;
        {__RPC__in_opt } pIContextSource: IWICColorContext;
        {__RPC__in_opt } pIContextDest: IWICColorContext;
        {__RPC__in } pixelFmtDest: TREFWICPixelFormatGUID): HRESULT; stdcall;

    end;


    IWICFastMetadataEncoder = interface(IUnknown)
        ['{B84E2C09-78C9-4AC4-8BD3-524AE1663A2F}']
        function Commit(): HRESULT; stdcall;

        function GetMetadataQueryWriter({__RPC__deref_out_opt} out ppIMetadataQueryWriter: IWICMetadataQueryWriter): HRESULT; stdcall;

    end;


    IWICStream = interface(IStream)
        ['{135FF860-22B7-4ddf-B0F6-218F4F299A43}']
        function InitializeFromIStream(
        {__RPC__in_opt } pIStream: IStream): HRESULT; stdcall;

        function InitializeFromFilename(
        {__RPC__in } wzFileName: LPCWSTR; dwDesiredAccess: DWORD): HRESULT; stdcall;

        function InitializeFromMemory(
        {__RPC__in_ecount_full(cbBufferSize) } pbBuffer: TWICInProcPointer; cbBufferSize: DWORD): HRESULT; stdcall;

        function InitializeFromIStreamRegion(
        {__RPC__in_opt } pIStream: IStream; ulOffset: ULARGE_INTEGER; ulMaxSize: ULARGE_INTEGER): HRESULT; stdcall;

    end;


    IWICEnumMetadataItem = interface(IUnknown)
        ['{DC2BB46D-3F07-481E-8625-220C4AEDBB33}']
        function Next(celt: ULONG;
        {__RPC__inout_ecount_full_opt(celt) } rgeltSchema: PPROPVARIANT;
        {__RPC__inout_ecount_full(celt) } rgeltId: PPROPVARIANT;
        {__RPC__inout_ecount_full(celt) } rgeltValue: PPROPVARIANT;
        {__RPC__out } pceltFetched: PULONG): HRESULT; stdcall;

        function Skip(celt: ULONG): HRESULT; stdcall;

        function Reset(): HRESULT; stdcall;

        function Clone({__RPC__deref_out_opt} out ppIEnumMetadataItem: IWICEnumMetadataItem): HRESULT; stdcall;

    end;


    IWICMetadataQueryReader = interface(IUnknown)
        ['{30989668-E1C9-4597-B395-458EEDB808DF}']
        function GetContainerFormat(
        {__RPC__out } pguidContainerFormat: PGUID): HRESULT; stdcall;

        function GetLocation(cchMaxLength: UINT;
        {__RPC__inout_ecount_full_opt(cchMaxLength) } wzNamespace: PWCHAR;
        {__RPC__out } pcchActualLength: PUINT): HRESULT; stdcall;

        function GetMetadataByName(
        {__RPC__in } wzName: LPCWSTR;
        {__RPC__inout_opt } pvarValue: PPROPVARIANT): HRESULT; stdcall;

        function GetEnumerator({__RPC__deref_out_opt} out ppIEnumString: IEnumString): HRESULT; stdcall;

    end;


    IWICMetadataQueryWriter = interface(IWICMetadataQueryReader)
        ['{A721791A-0DEF-4d06-BD91-2118BF1DB10B}']
        function SetMetadataByName(
        {__RPC__in } wzName: LPCWSTR;
        {__RPC__in } pvarValue: PPROPVARIANT): HRESULT; stdcall;

        function RemoveMetadataByName(
        {__RPC__in } wzName: LPCWSTR): HRESULT; stdcall;

    end;


    IWICBitmapEncoder = interface(IUnknown)
        ['{00000103-a8f2-4877-ba0a-fd2b6645fb94}']
        function Initialize(
        {__RPC__in_opt } pIStream: IStream; cacheOption: TWICBitmapEncoderCacheOption): HRESULT; stdcall;

        function GetContainerFormat(
        {__RPC__out } pguidContainerFormat: PGUID): HRESULT; stdcall;

        function GetEncoderInfo( {__RPC__deref_out_opt} out ppIEncoderInfo: IWICBitmapEncoderInfo): HRESULT; stdcall;

        function SetColorContexts(cCount: UINT;
        {__RPC__in_ecount_full(cCount) } ppIColorContext: PIWICColorContext): HRESULT; stdcall;

        function SetPalette(
        {__RPC__in_opt } pIPalette: IWICPalette): HRESULT; stdcall;

        function SetThumbnail(
        {__RPC__in_opt } pIThumbnail: IWICBitmapSource): HRESULT; stdcall;

        function SetPreview(
        {__RPC__in_opt } pIPreview: IWICBitmapSource): HRESULT; stdcall;

        function CreateNewFrame({__RPC__deref_out_opt} out ppIFrameEncode: IWICBitmapFrameEncode;
        {__RPC__deref_opt_inout_opt} ppIEncoderOptions: IPropertyBag2): HRESULT; stdcall;

        function Commit(): HRESULT; stdcall;

        function GetMetadataQueryWriter({__RPC__deref_out_opt} out ppIMetadataQueryWriter: IWICMetadataQueryWriter): HRESULT; stdcall;

    end;


    IWICBitmapFrameEncode = interface(IUnknown)
        ['{00000105-a8f2-4877-ba0a-fd2b6645fb94}']
        function Initialize(
        {__RPC__in_opt } pIEncoderOptions: IPropertyBag2): HRESULT; stdcall;

        function SetSize(uiWidth: UINT; uiHeight: UINT): HRESULT; stdcall;

        function SetResolution(dpiX: double; dpiY: double): HRESULT; stdcall;

        function SetPixelFormat(
        {__RPC__inout } pPixelFormat: PWICPixelFormatGUID): HRESULT; stdcall;

        function SetColorContexts(cCount: UINT;
        {__RPC__in_ecount_full(cCount) } ppIColorContext: PIWICColorContext): HRESULT; stdcall;

        function SetPalette(
        {__RPC__in_opt } pIPalette: IWICPalette): HRESULT; stdcall;

        function SetThumbnail(
        {__RPC__in_opt } pIThumbnail: IWICBitmapSource): HRESULT; stdcall;

        function WritePixels(lineCount: UINT; cbStride: UINT; cbBufferSize: UINT;
        {__RPC__in_ecount_full(cbBufferSize) } pbPixels: pbyte): HRESULT; stdcall;

        function WriteSource(
        {__RPC__in_opt } pIBitmapSource: IWICBitmapSource;
        {__RPC__in_opt } prc: PWICRect): HRESULT; stdcall;

        function Commit(): HRESULT; stdcall;

        function GetMetadataQueryWriter({__RPC__deref_out_opt}out ppIMetadataQueryWriter: IWICMetadataQueryWriter): HRESULT; stdcall;

    end;

    IWICPlanarBitmapFrameEncode = interface(IUnknown)
        ['{F928B7B8-2221-40C1-B72E-7E82F1974D1A}']
        function WritePixels(lineCount: UINT;
        {__RPC__in_ecount_full(cPlanes) } pPlanes: PWICBitmapPlane; cPlanes: UINT): HRESULT; stdcall;

        function WriteSource(
        {__RPC__in_ecount_full(cPlanes) } ppPlanes: PIWICBitmapSource; cPlanes: UINT;
        {__RPC__in_opt } prcSource: PWICRect): HRESULT; stdcall;

    end;

    // IWICImageEncoder is in DX12.WinCodecD2D1


    IWICBitmapDecoder = interface(IUnknown)
        ['{9EDDE9E7-8DEE-47ea-99DF-E6FAF2ED44BF}']
        function QueryCapability(
        {__RPC__in_opt } pIStream: IStream;
        {__RPC__out } pdwCapability: PDWORD): HRESULT; stdcall;

        function Initialize(
        {__RPC__in_opt } pIStream: IStream; cacheOptions: TWICDecodeOptions): HRESULT; stdcall;

        function GetContainerFormat(
        {__RPC__out } pguidContainerFormat: PGUID): HRESULT; stdcall;

        function GetDecoderInfo(
        {__RPC__deref_out_opt }  out ppIDecoderInfo: IWICBitmapDecoderInfo): HRESULT; stdcall;

        function CopyPalette(
        {__RPC__in_opt } pIPalette: IWICPalette): HRESULT; stdcall;

        function GetMetadataQueryReader(
        {__RPC__deref_out_opt }  out ppIMetadataQueryReader: IWICMetadataQueryReader): HRESULT; stdcall;

        function GetPreview(
        {__RPC__deref_out_opt }  out ppIBitmapSource: IWICBitmapSource): HRESULT; stdcall;

        function GetColorContexts(cCount: UINT;
        {__RPC__inout_ecount_full_opt(cCount) } ppIColorContexts: PIWICColorContext;
        {__RPC__out } pcActualCount: PUINT): HRESULT; stdcall;

        function GetThumbnail(
        {__RPC__deref_out_opt }  out ppIThumbnail: IWICBitmapSource): HRESULT; stdcall;

        function GetFrameCount(
        {__RPC__out } pCount: PUINT): HRESULT; stdcall;

        function GetFrame(index: UINT;
        {__RPC__deref_out_opt }  out ppIBitmapFrame: IWICBitmapFrameDecode): HRESULT; stdcall;

    end;

    IWICBitmapSourceTransform = interface(IUnknown)
        ['{3B16811B-6A43-4ec9-B713-3D5A0C13B940}']
        function CopyPixels(
        {__RPC__in_opt } prc: PWICRect; uiWidth: UINT; uiHeight: UINT;
        {__RPC__in_opt } pguidDstFormat: PWICPixelFormatGUID; dstTransform: TWICBitmapTransformOptions; nStride: UINT; cbBufferSize: UINT;
        {__RPC__out_ecount_full(cbBufferSize) } pbBuffer: pbyte): HRESULT; stdcall;

        function GetClosestSize(
        {__RPC__inout } puiWidth: PUINT;
        {__RPC__inout } puiHeight: PUINT): HRESULT; stdcall;

        function GetClosestPixelFormat(
        {__RPC__inout } pguidDstFormat: PWICPixelFormatGUID): HRESULT; stdcall;

        function DoesSupportTransform(dstTransform: TWICBitmapTransformOptions;
        {__RPC__out } pfIsSupported: Pwinbool): HRESULT; stdcall;

    end;

    IWICBitmapSourceTransform2 = interface(IWICBitmapSourceTransform)
        ['{c3373fdf-6d39-4e5f-8e79-bf40c0b7ed77}']
        function GetColorContextsForPixelFormat(
        {__RPC__in_opt } pPixelFormat: PWICPixelFormatGUID; cCount: UINT;
        {__RPC__in_ecount_full_opt(cCount) } ppIColorContexts: PIWICColorContext;
        {__RPC__out } pcActualCount: PUINT): HRESULT; stdcall;

    end;

    IWICPlanarBitmapSourceTransform = interface(IUnknown)
        ['{3AFF9CCE-BE95-4303-B927-E7D16FF4A613}']
        function DoesSupportTransform(
        {__RPC__inout } puiWidth: PUINT;
        {__RPC__inout } puiHeight: PUINT; dstTransform: TWICBitmapTransformOptions; dstPlanarOptions: TWICPlanarOptions;
        {__RPC__in_ecount_full(cPlanes) } pguidDstFormats: PWICPixelFormatGUID;
        {__RPC__out_ecount_full(cPlanes) } pPlaneDescriptions: PWICBitmapPlaneDescription; cPlanes: UINT;
        {__RPC__out } pfIsSupported: Pwinbool): HRESULT; stdcall;

        function CopyPixels(
        {__RPC__in_opt } prcSource: PWICRect; uiWidth: UINT; uiHeight: UINT; dstTransform: TWICBitmapTransformOptions; dstPlanarOptions: TWICPlanarOptions;
        {__RPC__in_ecount_full(cPlanes) } pDstPlanes: PWICBitmapPlane; cPlanes: UINT): HRESULT; stdcall;

    end;

    IWICBitmapFrameDecode = interface(IWICBitmapSource)
        ['{3B16811B-6A43-4ec9-A813-3D930C13B940}']
        function GetMetadataQueryReader(
        {__RPC__deref_out_opt }  out ppIMetadataQueryReader: IWICMetadataQueryReader): HRESULT; stdcall;

        function GetColorContexts(cCount: UINT;
        {__RPC__inout_ecount_full_opt(cCount) } ppIColorContexts: PIWICColorContext;
        {__RPC__out } pcActualCount: PUINT): HRESULT; stdcall;

        function GetThumbnail(
        {__RPC__deref_out_opt }  out ppIThumbnail: IWICBitmapSource): HRESULT; stdcall;

    end;

    IWICBitmapFrameChainReader = interface(IUnknown)
        ['{0c599495-a120-4222-9130-a8c29410bd0b}']
        function GetChainedFrameCount(chainType: TWICBitmapChainType;
        {__RPC__out } pCount: PUINT): HRESULT; stdcall;

        function GetChainedFrame(chainType: TWICBitmapChainType; index: UINT;
        {__RPC__deref_out_opt }  out ppIBitmapFrame: IWICBitmapFrameDecode): HRESULT; stdcall;

    end;

    IWICBitmapFrameChainWriter = interface(IUnknown)
        ['{40d9ea28-4768-47b3-8c12-558a48e98e38}']
        function AppendFrameToChain(chainType: TWICBitmapChainType;
        {__RPC__deref_out_opt }  out ppIFrameEncode: IWICBitmapFrameEncode;
        {__RPC__deref_opt_inout_opt } ppIEncoderOptions: PIPropertyBag2): HRESULT; stdcall;

        function DoesSupportChainType(chainType: TWICBitmapChainType;
        {__RPC__out } pfIsSupported: Pwinbool): HRESULT; stdcall;

    end;

    IWICProgressiveLevelControl = interface(IUnknown)
        ['{DAAC296F-7AA5-4dbf-8D15-225C5976F891}']
        function GetLevelCount(
        {__RPC__out } pcLevels: PUINT): HRESULT; stdcall;

        function GetCurrentLevel(
        {__RPC__out } pnLevel: PUINT): HRESULT; stdcall;

        function SetCurrentLevel(nLevel: UINT): HRESULT; stdcall;

    end;

    IWICDisplayAdaptationControl = interface(IUnknown)
        ['{de9d91d2-70b4-4f41-836c-25fcd39626d3}']
        function DoesSupportChangingMaxLuminance(
        {__RPC__in_opt } pguidDstFormat: PWICPixelFormatGUID;
        {__RPC__out } pfIsSupported: Pwinbool): HRESULT; stdcall;

        function SetDisplayMaxLuminance(fLuminanceInNits: single): HRESULT; stdcall;

        function GetDisplayMaxLuminance(
        {__RPC__out } pfLuminanceInNits: Psingle): HRESULT; stdcall;

    end;

    IWICDisplayAdaptationControl2 = interface(IWICDisplayAdaptationControl)
        ['{d7508d29-3ab7-447e-a676-4d80d7de726b}']
        function SetSdrWhiteLevel(fWhiteLevelInNits: single): HRESULT; stdcall;

        function GetSdrWhiteLevel(
        {__RPC__out } pfWhiteLevelInNits: Psingle): HRESULT; stdcall;

        function SetToneMappingMode(mode: TWICBitmapToneMappingMode): HRESULT; stdcall;

        function GetToneMappingMode(
        {__RPC__out } mode: PWICBitmapToneMappingMode): HRESULT; stdcall;

        function DoesSupportToneMappingMode(mode: TWICBitmapToneMappingMode;
        {__RPC__out } pfIsSupported: Pwinbool): HRESULT; stdcall;

    end;

    IWICD3DTextureSource = interface(IUnknown)
        ['{caf65cc4-8ebe-4718-a21f-8dbf40bb7e25}']
        function GetTexture(
        {_In_  } pD3DDevice: IUnknown;
        {_In_opt_  } pID3DTextureOptions: IPropertyBag2; riid: REFIID;
        {_Outptr_  }  out ppTexture): HRESULT; stdcall;

        function GetTransformedTexture(
        {_In_opt_  } prc: PWICRect; uiWidth: UINT; uiHeight: UINT;
        {_In_opt_  } pguidDstFormat: PWICPixelFormatGUID; dstTransform: TWICBitmapTransformOptions;
        {_In_  } pD3DDevice: IUnknown;
        {_In_opt_  } pID3DTextureOptions: IPropertyBag2; riid: REFIID;
        {_Outptr_  }  out ppTexture): HRESULT; stdcall;

        function DoesSupportD3DDeviceType(riid: REFIID;
        {_Out_  } pfIsSupported: Pwinbool): HRESULT; stdcall;

        function GetD3DTextureOptions(
        {_COM_Outptr_  }  out ppID3DTextureOptions: IPropertyBag2): HRESULT; stdcall;

    end;

    IWICProgressCallback = interface(IUnknown)
        ['{4776F9CD-9517-45FA-BF24-E89C5EC5C60C}']
        function Notify(uFrameNum: ULONG; operation: TWICProgressOperation; dblProgress: double): HRESULT; stdcall;

    end;

    PFNProgressNotification = function({__RPC__in } pvData: LPVOID; uFrameNum: ULONG; operation: TWICProgressOperation; dblProgress: double): HRESULT; stdcall;


    IWICBitmapCodecProgressNotification = interface(IUnknown)
        ['{64C1024E-C3CF-4462-8078-88C2B11C46D9}']
        function RegisterProgressNotification(
        {_In_opt_  } pfnProgressNotification: PFNProgressNotification;
        {_In_opt_  } pvData: LPVOID; dwProgressFlags: DWORD): HRESULT; stdcall;

    end;

    IWICComponentInfo = interface(IUnknown)
        ['{23BC3F0A-698B-4357-886B-F24D50671334}']
        function GetComponentType(
        {__RPC__out } pType: PWICComponentType): HRESULT; stdcall;

        function GetCLSID(
        {__RPC__out } pclsid: PCLSID): HRESULT; stdcall;

        function GetSigningStatus(
        {__RPC__out } pStatus: PDWORD): HRESULT; stdcall;

        function GetAuthor(cchAuthor: UINT;
        {__RPC__inout_ecount_full_opt(cchAuthor) } wzAuthor: PWCHAR;
        {__RPC__out } pcchActual: PUINT): HRESULT; stdcall;

        function GetVendorGUID(
        {__RPC__out } pguidVendor: PGUID): HRESULT; stdcall;

        function GetVersion(cchVersion: UINT;
        {__RPC__inout_ecount_full_opt(cchVersion) } wzVersion: PWCHAR;
        {__RPC__out } pcchActual: PUINT): HRESULT; stdcall;

        function GetSpecVersion(cchSpecVersion: UINT;
        {__RPC__inout_ecount_full_opt(cchSpecVersion) } wzSpecVersion: PWCHAR;
        {__RPC__out } pcchActual: PUINT): HRESULT; stdcall;

        function GetFriendlyName(cchFriendlyName: UINT;
        {__RPC__inout_ecount_full_opt(cchFriendlyName) } wzFriendlyName: PWCHAR;
        {__RPC__out } pcchActual: PUINT): HRESULT; stdcall;

    end;

    IWICFormatConverterInfo = interface(IWICComponentInfo)
        ['{9F34FB65-13F4-4f15-BC57-3726B5E53D9F}']
        function GetPixelFormats(cFormats: UINT;
        {__RPC__inout_ecount_full_opt(cFormats) } pPixelFormatGUIDs: PWICPixelFormatGUID;
        {__RPC__out } pcActual: PUINT): HRESULT; stdcall;

        function CreateInstance(
        {__RPC__deref_out_opt }  out ppIConverter: IWICFormatConverter): HRESULT; stdcall;

    end;

    IWICBitmapCodecInfo = interface(IWICComponentInfo)
        ['{E87A44C4-B76E-4c47-8B09-298EB12A2714}']
        function GetContainerFormat(
        {__RPC__out } pguidContainerFormat: PGUID): HRESULT; stdcall;

        function GetPixelFormats(cFormats: UINT;
        {__RPC__inout_ecount_full_opt(cFormats) } pguidPixelFormats: PGUID;
        {__RPC__out } pcActual: PUINT): HRESULT; stdcall;

        function GetColorManagementVersion(cchColorManagementVersion: UINT;
        {__RPC__inout_ecount_full_opt(cchColorManagementVersion) } wzColorManagementVersion: PWCHAR;
        {__RPC__out } pcchActual: PUINT): HRESULT; stdcall;

        function GetDeviceManufacturer(cchDeviceManufacturer: UINT;
        {__RPC__inout_ecount_full_opt(cchDeviceManufacturer) } wzDeviceManufacturer: PWCHAR;
        {__RPC__out } pcchActual: PUINT): HRESULT; stdcall;

        function GetDeviceModels(cchDeviceModels: UINT;
        {__RPC__inout_ecount_full_opt(cchDeviceModels) } wzDeviceModels: PWCHAR;
        {__RPC__out } pcchActual: PUINT): HRESULT; stdcall;

        function GetMimeTypes(cchMimeTypes: UINT;
        {__RPC__inout_ecount_full_opt(cchMimeTypes) } wzMimeTypes: PWCHAR;
        {__RPC__out } pcchActual: PUINT): HRESULT; stdcall;

        function GetFileExtensions(cchFileExtensions: UINT;
        {__RPC__inout_ecount_full_opt(cchFileExtensions) } wzFileExtensions: PWCHAR;
        {__RPC__out } pcchActual: PUINT): HRESULT; stdcall;

        function DoesSupportAnimation(
        {__RPC__out } pfSupportAnimation: Pwinbool): HRESULT; stdcall;

        function DoesSupportChromakey(
        {__RPC__out } pfSupportChromakey: Pwinbool): HRESULT; stdcall;

        function DoesSupportLossless(
        {__RPC__out } pfSupportLossless: Pwinbool): HRESULT; stdcall;

        function DoesSupportMultiframe(
        {__RPC__out } pfSupportMultiframe: Pwinbool): HRESULT; stdcall;

        function MatchesMimeType(
        {__RPC__in } wzMimeType: LPCWSTR;
        {__RPC__out } pfMatches: Pwinbool): HRESULT; stdcall;

    end;

    IWICBitmapEncoderInfo = interface(IWICBitmapCodecInfo)
        ['{94C9B4EE-A09F-4f92-8A1E-4A9BCE7E76FB}']
        function CreateInstance(
        {__RPC__deref_out_opt }  out ppIBitmapEncoder: IWICBitmapEncoder): HRESULT; stdcall;

    end;

    IWICBitmapDecoderInfo = interface(IWICBitmapCodecInfo)
        ['{D8CD007F-D08F-4191-9BFC-236EA7F0E4B5}']
        function GetPatterns(cbSizePatterns: UINT;
        {_Out_writes_bytes_to_opt_(cbSizePatterns, *pcbPatternsActual)  } pPatterns: PWICBitmapPattern;
        {_Out_opt_  } pcPatterns: PUINT;
        {_Out_  } pcbPatternsActual: PUINT): HRESULT; stdcall;

        function MatchesPattern(
        {__RPC__in_opt } pIStream: IStream;
        {__RPC__out } pfMatches: Pwinbool): HRESULT; stdcall;

        function CreateInstance(
        {__RPC__deref_out_opt }  out ppIBitmapDecoder: IWICBitmapDecoder): HRESULT; stdcall;

    end;

    IWICPixelFormatInfo = interface(IWICComponentInfo)
        ['{E8EDA601-3D48-431a-AB44-69059BE88BBE}']
        function GetFormatGUID(
        {__RPC__out } pFormat: PGUID): HRESULT; stdcall;

        function GetColorContext(
        {__RPC__deref_out_opt }  out ppIColorContext: IWICColorContext): HRESULT; stdcall;

        function GetBitsPerPixel(
        {__RPC__out } puiBitsPerPixel: PUINT): HRESULT; stdcall;

        function GetChannelCount(
        {__RPC__out } puiChannelCount: PUINT): HRESULT; stdcall;

        function GetChannelMask(uiChannelIndex: UINT; cbMaskBuffer: UINT;
        {__RPC__inout_ecount_full_opt(cbMaskBuffer) } pbMaskBuffer: pbyte;
        {__RPC__out } pcbActual: PUINT): HRESULT; stdcall;

    end;

    IWICPixelFormatInfo2 = interface(IWICPixelFormatInfo)
        ['{A9DB33A2-AF5F-43C7-B679-74F5984B5AA4}']
        function SupportsTransparency(
        {__RPC__out } pfSupportsTransparency: Pwinbool): HRESULT; stdcall;

        function GetNumericRepresentation(
        {__RPC__out } pNumericRepresentation: PWICPixelFormatNumericRepresentation): HRESULT; stdcall;

    end;

    IWICImagingFactory = interface(IUnknown)
        ['{ec5ec8a9-c395-4314-9c77-54d7a935ff70}']
        function CreateDecoderFromFilename(
        {__RPC__in } wzFilename: LPCWSTR;
        {__RPC__in_opt } pguidVendor: PGUID; dwDesiredAccess: DWORD; metadataOptions: TWICDecodeOptions;
        {__RPC__deref_out_opt }  out ppIDecoder: IWICBitmapDecoder): HRESULT; stdcall;

        function CreateDecoderFromStream(
        {__RPC__in_opt } pIStream: IStream;
        {__RPC__in_opt } pguidVendor: PGUID; metadataOptions: TWICDecodeOptions;
        {__RPC__deref_out_opt }  out ppIDecoder: IWICBitmapDecoder): HRESULT; stdcall;

        function CreateDecoderFromFileHandle(hFile: ULONG_PTR;
        {__RPC__in_opt } pguidVendor: PGUID; metadataOptions: TWICDecodeOptions;
        {__RPC__deref_out_opt }  out ppIDecoder: IWICBitmapDecoder): HRESULT; stdcall;

        function CreateComponentInfo(
        {__RPC__in } clsidComponent: REFCLSID;
        {__RPC__deref_out_opt }  out ppIInfo: IWICComponentInfo): HRESULT; stdcall;

        function CreateDecoder(
        {__RPC__in } guidContainerFormat: REFGUID;
        {__RPC__in_opt } pguidVendor: PGUID;
        {__RPC__deref_out_opt }  out ppIDecoder: IWICBitmapDecoder): HRESULT; stdcall;

        function CreateEncoder(
        {__RPC__in } guidContainerFormat: REFGUID;
        {__RPC__in_opt } pguidVendor: PGUID;
        {__RPC__deref_out_opt }  out ppIEncoder: IWICBitmapEncoder): HRESULT; stdcall;

        function CreatePalette(
        {__RPC__deref_out_opt }  out ppIPalette: IWICPalette): HRESULT; stdcall;

        function CreateFormatConverter(
        {__RPC__deref_out_opt }  out ppIFormatConverter: IWICFormatConverter): HRESULT; stdcall;

        function CreateBitmapScaler(
        {__RPC__deref_out_opt }  out ppIBitmapScaler: IWICBitmapScaler): HRESULT; stdcall;

        function CreateBitmapClipper(
        {__RPC__deref_out_opt }  out ppIBitmapClipper: IWICBitmapClipper): HRESULT; stdcall;

        function CreateBitmapFlipRotator(
        {__RPC__deref_out_opt }  out ppIBitmapFlipRotator: IWICBitmapFlipRotator): HRESULT; stdcall;

        function CreateStream(
        {__RPC__deref_out_opt }  out ppIWICStream: IWICStream): HRESULT; stdcall;

        function CreateColorContext(
        {__RPC__deref_out_opt }  out ppIWICColorContext: IWICColorContext): HRESULT; stdcall;

        function CreateColorTransformer(
        {__RPC__deref_out_opt }  out ppIWICColorTransform: IWICColorTransform): HRESULT; stdcall;

        function CreateBitmap(uiWidth: UINT; uiHeight: UINT;
        {__RPC__in } pixelFormat: TREFWICPixelFormatGUID; option: TWICBitmapCreateCacheOption;
        {__RPC__deref_out_opt }  out ppIBitmap: IWICBitmap): HRESULT; stdcall;

        function CreateBitmapFromSource(
        {__RPC__in_opt } pIBitmapSource: IWICBitmapSource; option: TWICBitmapCreateCacheOption;
        {__RPC__deref_out_opt }  out ppIBitmap: IWICBitmap): HRESULT; stdcall;

        function CreateBitmapFromSourceRect(
        {__RPC__in_opt } pIBitmapSource: IWICBitmapSource; x: UINT; y: UINT; Width: UINT; Height: UINT;
        {__RPC__deref_out_opt }  out ppIBitmap: IWICBitmap): HRESULT; stdcall;

        function CreateBitmapFromMemory(uiWidth: UINT; uiHeight: UINT;
        {__RPC__in } pixelFormat: TREFWICPixelFormatGUID; cbStride: UINT; cbBufferSize: UINT;
        {__RPC__in_ecount_full(cbBufferSize) } pbBuffer: pbyte;
        {__RPC__deref_out_opt }  out ppIBitmap: IWICBitmap): HRESULT; stdcall;

        function CreateBitmapFromHBITMAP(
        {__RPC__in } hBitmap: HBITMAP;
        {__RPC__in_opt } hPalette: HPALETTE; options: TWICBitmapAlphaChannelOption;
        {__RPC__deref_out_opt }  out ppIBitmap: IWICBitmap): HRESULT; stdcall;

        function CreateBitmapFromHICON(
        {__RPC__in } hIcon: HICON;
        {__RPC__deref_out_opt }  out ppIBitmap: IWICBitmap): HRESULT; stdcall;

        function CreateComponentEnumerator(componentTypes: DWORD; options: DWORD;
        {__RPC__deref_out_opt }  out ppIEnumUnknown: IEnumUnknown): HRESULT; stdcall;

        function CreateFastMetadataEncoderFromDecoder(
        {__RPC__in_opt } pIDecoder: IWICBitmapDecoder;
        {__RPC__deref_out_opt }  out ppIFastEncoder: IWICFastMetadataEncoder): HRESULT; stdcall;

        function CreateFastMetadataEncoderFromFrameDecode(
        {__RPC__in_opt } pIFrameDecoder: IWICBitmapFrameDecode;
        {__RPC__deref_out_opt }  out ppIFastEncoder: IWICFastMetadataEncoder): HRESULT; stdcall;

        function CreateQueryWriter(
        {__RPC__in } guidMetadataFormat: REFGUID;
        {__RPC__in_opt } pguidVendor: PGUID;
        {__RPC__deref_out_opt }  out ppIQueryWriter: IWICMetadataQueryWriter): HRESULT; stdcall;

        function CreateQueryWriterFromReader(
        {__RPC__in_opt } pIQueryReader: IWICMetadataQueryReader;
        {__RPC__in_opt } pguidVendor: PGUID;
        {__RPC__deref_out_opt }  out ppIQueryWriter: IWICMetadataQueryWriter): HRESULT; stdcall;

    end;


    // IWICImagingFactory2 is in DX12.WinCodecD2D1 to avoid circular reference

    // IWICImagingFactory3 is in DX12.WinCodecD2D1 to avoid circular reference


    TWICTiffCompressionOption = (
        WICTiffCompressionDontCare = 0,
        WICTiffCompressionNone = $1,
        WICTiffCompressionCCITT3 = $2,
        WICTiffCompressionCCITT4 = $3,
        WICTiffCompressionLZW = $4,
        WICTiffCompressionRLE = $5,
        WICTiffCompressionZIP = $6,
        WICTiffCompressionLZWHDifferencing = $7,
        WICTIFFCOMPRESSIONOPTION_FORCE_DWORD = $7fffffff);

    PWICTiffCompressionOption = ^TWICTiffCompressionOption;


    TWICJpegYCrCbSubsamplingOption = (
        WICJpegYCrCbSubsamplingDefault = 0,
        WICJpegYCrCbSubsampling420 = $1,
        WICJpegYCrCbSubsampling422 = $2,
        WICJpegYCrCbSubsampling444 = $3,
        WICJpegYCrCbSubsampling440 = $4,
        WICJPEGYCRCBSUBSAMPLING_FORCE_DWORD = $7fffffff);

    PWICJpegYCrCbSubsamplingOption = ^TWICJpegYCrCbSubsamplingOption;


    TWICPngFilterOption = (
        WICPngFilterUnspecified = 0,
        WICPngFilterNone = $1,
        WICPngFilterSub = $2,
        WICPngFilterUp = $3,
        WICPngFilterAverage = $4,
        WICPngFilterPaeth = $5,
        WICPngFilterAdaptive = $6,
        WICPNGFILTEROPTION_FORCE_DWORD = $7fffffff);

    PWICPngFilterOption = ^TWICPngFilterOption;


    TWICHeifCompressionOption = (
        WICHeifCompressionDontCare = 0,
        WICHeifCompressionNone = $1,
        WICHeifCompressionHEVC = $2,
        WICHeifCompressionAV1 = $3,
        WICHeifCompressionJpegXL = $4,
        WICHeifCompressionBrotli = $5,
        WICHeifCompressionDeflate = $6,
        WICHEIFCOMPRESSIONOPTION_FORCE_DWORD = $7fffffff);

    PWICHeifCompressionOption = ^TWICHeifCompressionOption;


    TWICNamedWhitePoint = (
        WICWhitePointDefault = $1,
        WICWhitePointDaylight = $2,
        WICWhitePointCloudy = $4,
        WICWhitePointShade = $8,
        WICWhitePointTungsten = $10,
        WICWhitePointFluorescent = $20,
        WICWhitePointFlash = $40,
        WICWhitePointUnderwater = $80,
        WICWhitePointCustom = $100,
        WICWhitePointAutoWhiteBalance = $200,
        WICWhitePointAsShot = WICWhitePointDefault,
        WICNAMEDWHITEPOINT_FORCE_DWORD = $7fffffff);

    PWICNamedWhitePoint = ^TWICNamedWhitePoint;


    TWICRawCapabilities = (
        WICRawCapabilityNotSupported = 0,
        WICRawCapabilityGetSupported = $1,
        WICRawCapabilityFullySupported = $2,
        WICRAWCAPABILITIES_FORCE_DWORD = $7fffffff);

    PWICRawCapabilities = ^TWICRawCapabilities;


    TWICRawRotationCapabilities = (
        WICRawRotationCapabilityNotSupported = 0,
        WICRawRotationCapabilityGetSupported = $1,
        WICRawRotationCapabilityNinetyDegreesSupported = $2,
        WICRawRotationCapabilityFullySupported = $3,
        WICRAWROTATIONCAPABILITIES_FORCE_DWORD = $7fffffff);

    PWICRawRotationCapabilities = ^TWICRawRotationCapabilities;


    TWICRawCapabilitiesInfo = record
        cbSize: UINT;
        CodecMajorVersion: UINT;
        CodecMinorVersion: UINT;
        ExposureCompensationSupport: TWICRawCapabilities;
        ContrastSupport: TWICRawCapabilities;
        RGBWhitePointSupport: TWICRawCapabilities;
        NamedWhitePointSupport: TWICRawCapabilities;
        NamedWhitePointSupportMask: UINT;
        KelvinWhitePointSupport: TWICRawCapabilities;
        GammaSupport: TWICRawCapabilities;
        TintSupport: TWICRawCapabilities;
        SaturationSupport: TWICRawCapabilities;
        SharpnessSupport: TWICRawCapabilities;
        NoiseReductionSupport: TWICRawCapabilities;
        DestinationColorProfileSupport: TWICRawCapabilities;
        ToneCurveSupport: TWICRawCapabilities;
        RotationSupport: TWICRawRotationCapabilities;
        RenderModeSupport: TWICRawCapabilities;
    end;
    PWICRawCapabilitiesInfo = ^TWICRawCapabilitiesInfo;


    TWICRawParameterSet = (
        WICAsShotParameterSet = $1,
        WICUserAdjustedParameterSet = $2,
        WICAutoAdjustedParameterSet = $3,
        WICRAWPARAMETERSET_FORCE_DWORD = $7fffffff);

    PWICRawParameterSet = ^TWICRawParameterSet;


    TWICRawRenderMode = (
        WICRawRenderModeDraft = $1,
        WICRawRenderModeNormal = $2,
        WICRawRenderModeBestQuality = $3,
        WICRAWRENDERMODE_FORCE_DWORD = $7fffffff);

    PWICRawRenderMode = ^TWICRawRenderMode;


    TWICRawToneCurvePoint = record
        Input: double;
        Output: double;
    end;
    PWICRawToneCurvePoint = ^TWICRawToneCurvePoint;

    TWICRawToneCurve = record
        cPoints: UINT;
        aPoints: PWICRawToneCurvePoint;
    end;
    PWICRawToneCurve = ^TWICRawToneCurve;


    IWICDevelopRawNotificationCallback = interface(IUnknown)
        ['{95c75a6e-3e8c-4ec2-85a8-aebcc551e59b}']
        function Notify(NotificationMask: UINT): HRESULT; stdcall;

    end;

    IWICDevelopRaw = interface(IWICBitmapFrameDecode)
        ['{fbec5e44-f7be-4b65-b7f8-c0c81fef026d}']
        function QueryRawCapabilitiesInfo(pInfo: PWICRawCapabilitiesInfo): HRESULT; stdcall;

        function LoadParameterSet(ParameterSet: TWICRawParameterSet): HRESULT; stdcall;

        function GetCurrentParameterSet(
        {__RPC__deref_out_opt }  out ppCurrentParameterSet: IPropertyBag2): HRESULT; stdcall;

        function SetExposureCompensation(ev: double): HRESULT; stdcall;

        function GetExposureCompensation(
        {__RPC__out } pEV: Pdouble): HRESULT; stdcall;

        function SetWhitePointRGB(Red: UINT; Green: UINT; Blue: UINT): HRESULT; stdcall;

        function GetWhitePointRGB(
        {__RPC__out } pRed: PUINT;
        {__RPC__out } pGreen: PUINT;
        {__RPC__out } pBlue: PUINT): HRESULT; stdcall;

        function SetNamedWhitePoint(WhitePoint: TWICNamedWhitePoint): HRESULT; stdcall;

        function GetNamedWhitePoint(
        {__RPC__out } pWhitePoint: PWICNamedWhitePoint): HRESULT; stdcall;

        function SetWhitePointKelvin(WhitePointKelvin: UINT): HRESULT; stdcall;

        function GetWhitePointKelvin(
        {__RPC__out } pWhitePointKelvin: PUINT): HRESULT; stdcall;

        function GetKelvinRangeInfo(
        {__RPC__out } pMinKelvinTemp: PUINT;
        {__RPC__out } pMaxKelvinTemp: PUINT;
        {__RPC__out } pKelvinTempStepValue: PUINT): HRESULT; stdcall;

        function SetContrast(Contrast: double): HRESULT; stdcall;

        function GetContrast(
        {__RPC__out } pContrast: Pdouble): HRESULT; stdcall;

        function SetGamma(Gamma: double): HRESULT; stdcall;

        function GetGamma(
        {__RPC__out } pGamma: Pdouble): HRESULT; stdcall;

        function SetSharpness(Sharpness: double): HRESULT; stdcall;

        function GetSharpness(
        {__RPC__out } pSharpness: Pdouble): HRESULT; stdcall;

        function SetSaturation(Saturation: double): HRESULT; stdcall;

        function GetSaturation(
        {__RPC__out } pSaturation: Pdouble): HRESULT; stdcall;

        function SetTint(Tint: double): HRESULT; stdcall;

        function GetTint(
        {__RPC__out } pTint: Pdouble): HRESULT; stdcall;

        function SetNoiseReduction(NoiseReduction: double): HRESULT; stdcall;

        function GetNoiseReduction(
        {__RPC__out } pNoiseReduction: Pdouble): HRESULT; stdcall;

        function SetDestinationColorContext(
        {__RPC__in_opt } pColorContext: IWICColorContext): HRESULT; stdcall;

        function SetToneCurve(cbToneCurveSize: UINT;
        {_In_reads_bytes_(cbToneCurveSize)  } pToneCurve: PWICRawToneCurve): HRESULT; stdcall;

        function GetToneCurve(cbToneCurveBufferSize: UINT;
        {_Out_writes_bytes_to_opt_(cbToneCurveBufferSize, *pcbActualToneCurveBufferSize)  } pToneCurve: PWICRawToneCurve;
        {_Inout_opt_  } pcbActualToneCurveBufferSize: PUINT): HRESULT; stdcall;

        function SetRotation(Rotation: double): HRESULT; stdcall;

        function GetRotation(
        {__RPC__out } pRotation: Pdouble): HRESULT; stdcall;

        function SetRenderMode(RenderMode: TWICRawRenderMode): HRESULT; stdcall;

        function GetRenderMode(
        {__RPC__out } pRenderMode: PWICRawRenderMode): HRESULT; stdcall;

        function SetNotificationCallback(
        {__RPC__in_opt } pCallback: IWICDevelopRawNotificationCallback): HRESULT; stdcall;

    end;

    TWICDdsDimension = (
        WICDdsTexture1D = 0,
        WICDdsTexture2D = $1,
        WICDdsTexture3D = $2,
        WICDdsTextureCube = $3,
        WICDDSTEXTURE_FORCE_DWORD = $7fffffff
        );

    PWICDdsDimension = ^TWICDdsDimension;

    TWICDdsAlphaMode = (
        WICDdsAlphaModeUnknown = 0,
        WICDdsAlphaModeStraight = $1,
        WICDdsAlphaModePremultiplied = $2,
        WICDdsAlphaModeOpaque = $3,
        WICDdsAlphaModeCustom = $4,
        WICDDSALPHAMODE_FORCE_DWORD = $7fffffff
        );

    PWICDdsAlphaMode = ^TWICDdsAlphaMode;

    TWICDdsParameters = record
        Width: UINT;
        Height: UINT;
        Depth: UINT;
        MipLevels: UINT;
        ArraySize: UINT;
        DxgiFormat: TDXGI_FORMAT;
        Dimension: TWICDdsDimension;
        AlphaMode: TWICDdsAlphaMode;
    end;
    PWICDdsParameters = ^TWICDdsParameters;

    IWICDdsDecoder = interface(IUnknown)
        ['{409cd537-8532-40cb-9774-e2feb2df4e9c}']
        function GetParameters(
        {__RPC__out } pParameters: PWICDdsParameters): HRESULT; stdcall;

        function GetFrame(arrayIndex: UINT; mipLevel: UINT; sliceIndex: UINT;
        {__RPC__deref_out_opt }  out ppIBitmapFrame: IWICBitmapFrameDecode): HRESULT; stdcall;

    end;

    IWICDdsEncoder = interface(IUnknown)
        ['{5cacdb4c-407e-41b3-b936-d0f010cd6732}']
        function SetParameters(
        {__RPC__in } pParameters: PWICDdsParameters): HRESULT; stdcall;

        function GetParameters(
        {__RPC__out } pParameters: PWICDdsParameters): HRESULT; stdcall;

        function CreateNewFrame(
        {__RPC__deref_out_opt }  out ppIFrameEncode: IWICBitmapFrameEncode;
        {__RPC__out } pArrayIndex: PUINT;
        {__RPC__out } pMipLevel: PUINT;
        {__RPC__out } pSliceIndex: PUINT): HRESULT; stdcall;

    end;

    TWICDdsFormatInfo = record
        DxgiFormat: TDXGI_FORMAT;
        BytesPerBlock: UINT;
        BlockWidth: UINT;
        BlockHeight: UINT;
    end;
    PWICDdsFormatInfo = ^TWICDdsFormatInfo;

    IWICDdsFrameDecode = interface(IUnknown)
        ['{3d4c0c61-18a4-41e4-bd80-481a4fc9f464}']
        function GetSizeInBlocks(
        {__RPC__out } pWidthInBlocks: PUINT;
        {__RPC__out } pHeightInBlocks: PUINT): HRESULT; stdcall;

        function GetFormatInfo(
        {__RPC__out } pFormatInfo: PWICDdsFormatInfo): HRESULT; stdcall;

        function CopyBlocks(
        {__RPC__in_opt } prcBoundsInBlocks: PWICRect; cbStride: UINT; cbBufferSize: UINT;
        {__RPC__out_ecount_full(cbBufferSize) } pbBuffer: pbyte): HRESULT; stdcall;

    end;

    IWICJpegFrameDecode = interface(IUnknown)
        ['{8939F66E-C46A-4c21-A9D1-98B327CE1679}']
        function DoesSupportIndexing(
        {__RPC__out } pfIndexingSupported: Pwinbool): HRESULT; stdcall;

        function SetIndexing(options: TWICJpegIndexingOptions; horizontalIntervalSize: UINT): HRESULT; stdcall;

        function ClearIndexing(): HRESULT; stdcall;

        function GetAcHuffmanTable(scanIndex: UINT;
        (* [range] *)
        {__RPC__in_range(0,WIC_JPEG_MAX_TABLE_INDEX) } tableIndex: UINT;
        {__RPC__out } pAcHuffmanTable: PDXGI_JPEG_AC_HUFFMAN_TABLE): HRESULT; stdcall;

        function GetDcHuffmanTable(scanIndex: UINT;
        (* [range] *)
        {__RPC__in_range(0,WIC_JPEG_MAX_TABLE_INDEX) } tableIndex: UINT;
        {__RPC__out } pDcHuffmanTable: PDXGI_JPEG_DC_HUFFMAN_TABLE): HRESULT; stdcall;

        function GetQuantizationTable(scanIndex: UINT;
        (* [range] *)
        {__RPC__in_range(0,WIC_JPEG_MAX_TABLE_INDEX) } tableIndex: UINT;
        {__RPC__out } pQuantizationTable: PDXGI_JPEG_QUANTIZATION_TABLE): HRESULT; stdcall;

        function GetFrameHeader(
        {__RPC__out } pFrameHeader: PWICJpegFrameHeader): HRESULT; stdcall;

        function GetScanHeader(scanIndex: UINT;
        {__RPC__out } pScanHeader: PWICJpegScanHeader): HRESULT; stdcall;

        function CopyScan(scanIndex: UINT; scanOffset: UINT; cbScanData: UINT;
        {__RPC__out_ecount_part(cbScanData, *pcbScanDataActual) } pbScanData: pbyte;
        {__RPC__out } pcbScanDataActual: PUINT): HRESULT; stdcall;

        function CopyMinimalStream(streamOffset: UINT; cbStreamData: UINT;
        {__RPC__out_ecount_part(cbStreamData, *pcbStreamDataActual) } pbStreamData: pbyte;
        {__RPC__out } pcbStreamDataActual: PUINT): HRESULT; stdcall;

    end;

    IWICJpegFrameEncode = interface(IUnknown)
        ['{2F0C601F-D2C6-468C-ABFA-49495D983ED1}']
        function GetAcHuffmanTable(scanIndex: UINT;
        (* [range] *)
        {__RPC__in_range(0,WIC_JPEG_MAX_TABLE_INDEX) } tableIndex: UINT;
        {__RPC__out } pAcHuffmanTable: PDXGI_JPEG_AC_HUFFMAN_TABLE): HRESULT; stdcall;

        function GetDcHuffmanTable(scanIndex: UINT;
        (* [range] *)
        {__RPC__in_range(0,WIC_JPEG_MAX_TABLE_INDEX) } tableIndex: UINT;
        {__RPC__out } pDcHuffmanTable: PDXGI_JPEG_DC_HUFFMAN_TABLE): HRESULT; stdcall;

        function GetQuantizationTable(scanIndex: UINT;
        (* [range] *)
        {__RPC__in_range(0,WIC_JPEG_MAX_TABLE_INDEX) } tableIndex: UINT;
        {__RPC__out } pQuantizationTable: PDXGI_JPEG_QUANTIZATION_TABLE): HRESULT; stdcall;

        function WriteScan(cbScanData: UINT;
        {__RPC__in_ecount_full(cbScanData) } pbScanData: pbyte): HRESULT; stdcall;

    end;


function WICConvertBitmapSource(
    // Destination pixel format
    {_In_ } dstFormat: TREFWICPixelFormatGUID;
    // Source bitmap
    {_In_ } pISrc: IWICBitmapSource;
    // Destination bitmap, a copy or addrefed source
    {_Outptr_ }  out ppIDst: IWICBitmapSource): HRESULT; stdcall; external 'Windowscodecs.dll';

function WICCreateBitmapFromSection(
    {_In_ } Width: UINT;
    {_In_ } Height: UINT;
    {_In_ } pixelFormat: TREFWICPixelFormatGUID;
    {_In_ } hSection: HANDLE;
    {_In_ } stride: UINT;
    {_In_ } offset: UINT;
    {_Outptr_ }  out ppIBitmap: IWICBitmap): HRESULT; stdcall; external 'WindowsCodecs.dll';

function WICCreateBitmapFromSectionEx(
    {_In_ } Width: UINT;
    {_In_ } Height: UINT;
    {_In_ } pixelFormat: TREFWICPixelFormatGUID;
    {_In_ } hSection: HANDLE;
    {_In_ } stride: UINT;
    {_In_ } offset: UINT;
    {_In_ } desiredAccessLevel: TWICSectionAccessLevel;
    {_Outptr_ }  out ppIBitmap: IWICBitmap): HRESULT; stdcall; external 'WindowsCodecs.dll';

function WICMapGuidToShortName(
    {_In_ } guid: REFGUID;
    {_In_ } cchName: UINT;
    {_Inout_updates_opt_(cchName) } wzName: PWCHAR;
    {_Out_ } pcchActual: PUINT): HRESULT; stdcall; external 'WindowsCodecs.dll';

function WICMapShortNameToGuid(
    {_In_ } wzName: PCWSTR;
    {_Out_ } pguid: PGUID): HRESULT; stdcall; external 'WindowsCodecs.dll';

function WICMapSchemaToName(
    {_In_ } guidMetadataFormat: REFGUID;
    {_In_ } pwzSchema: LPWSTR;
    {_In_ } cchName: UINT;
    {_Inout_updates_opt_(cchName) } wzName: PWCHAR;
    {_Out_ } pcchActual: PUINT): HRESULT; stdcall; external 'WindowsCodecs.dll';


function MAKE_WINCODECHR(sev, code: longword): HRESULT;

function MAKE_WINCODECHR_ERR(code: longword): HRESULT;


implementation

uses
    Windows.Macros;



function MAKE_WINCODECHR(sev, code: longword): HRESULT;
begin
    Result := MAKE_HRESULT(sev, FACILITY_WINCODEC_ERR, (WINCODEC_ERR_BASE + code));
end;



function MAKE_WINCODECHR_ERR(code: longword): HRESULT;
begin
    Result := MAKE_WINCODECHR(1, code);
end;

{ TWICRect }

procedure TWICRect.Init(x, y, w, h: int32);
begin
  self.x:=x;
  self.y:=y;
  self.Width:=w;
  self.Height:=h;
end;

end.
