{ **************************************************************************
    FreePascal/Delphi DirectX 12 Header Files

    Copyright (C) 2013-2025 Norbert Sonnleitner

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
************************************************************************** }

{ **************************************************************************
   Additional Copyright (C) for this modul:

   Copyright (c) Microsoft Corporation
   this ALWAYS GENERATED file contains the definitions for the interfaces

   This unit consists of the following header files
   File name: d3d10sdklayers.h
   Header version: 10.0.26100.6584

  ************************************************************************** }

unit DX12.D3D10SDKLayers;

{$mode ObjFPC}{$H+}

interface

uses
    Windows, Classes, SysUtils,
    DX12.DXGI;

    {$Z4}

const
    D3D10_SDK_LAYERS_VERSION = (11);

    D3D10_DEBUG_FEATURE_FLUSH_PER_RENDER_OP = ($1);

    D3D10_DEBUG_FEATURE_FINISH_PER_RENDER_OP = ($2);

    D3D10_DEBUG_FEATURE_PRESENT_PER_RENDER_OP = ($4);


    D3D10_REGKEY_PATH = ('Software\\Microsoft\\Direct3D');
    D3D10_MUTE_DEBUG_OUTPUT = ('MuteDebugOutput');
    D3D10_ENABLE_BREAK_ON_MESSAGE = ('EnableBreakOnMessage');
    D3D10_INFOQUEUE_STORAGE_FILTER_OVERRIDE = ('InfoQueueStorageFilterOverride');
    D3D10_MUTE_CATEGORY = ('Mute_CATEGORY_%s');
    D3D10_MUTE_SEVERITY = ('Mute_SEVERITY_%s');
    D3D10_MUTE_ID_STRING = ('Mute_ID_%s');
    D3D10_MUTE_ID_DECIMAL = ('Mute_ID_%d');
    D3D10_UNMUTE_SEVERITY_INFO = ('Unmute_SEVERITY_INFO');
    D3D10_BREAKON_CATEGORY = ('BreakOn_CATEGORY_%s');
    D3D10_BREAKON_SEVERITY = ('BreakOn_SEVERITY_%s');
    D3D10_BREAKON_ID_STRING = ('BreakOn_ID_%s');
    D3D10_BREAKON_ID_DECIMAL = ('BreakOn_ID_%d');
    D3D10_APPSIZE_STRING = ('Size');
    D3D10_APPNAME_STRING = ('Name');

    DXGI_DEBUG_D3D10: TGUID = '{243B4C52-3606-4D3A-99D7-A7E7B33ED706}';
    IID_ID3D10Debug: TGUID = '{9B7E4E01-342C-4106-A19F-4F2704F689F0}';
    IID_ID3D10SwitchToRef: TGUID = '{9B7E4E02-342C-4106-A19F-4F2704F689F0}';
    IID_ID3D10InfoQueue: TGUID = '{1B940B17-2642-4D1F-AB1F-B99BAD0C395F}';

    D3D10_INFO_QUEUE_DEFAULT_MESSAGE_COUNT_LIMIT = 1024;

type

    (* Forward Declarations *)


    ID3D10Debug = interface;


    ID3D10SwitchToRef = interface;


    ID3D10InfoQueue = interface;


    ID3D10Debug = interface(IUnknown)
        ['{9B7E4E01-342C-4106-A19F-4F2704F689F0}']
        function SetFeatureMask(Mask: UINT): HRESULT; stdcall;

        function GetFeatureMask(): UINT; stdcall;

        function SetPresentPerRenderOpDelay(Milliseconds: UINT): HRESULT; stdcall;

        function GetPresentPerRenderOpDelay(): UINT; stdcall;

        function SetSwapChain(
        {_In_opt_  } pSwapChain: IDXGISwapChain): HRESULT; stdcall;

        function GetSwapChain(
        {_Out_  }  out ppSwapChain: IDXGISwapChain): HRESULT; stdcall;

        function Validate(): HRESULT; stdcall;

    end;


    ID3D10SwitchToRef = interface(IUnknown)
        ['{9B7E4E02-342C-4106-A19F-4F2704F689F0}']
        function SetUseRef(UseRef: boolean): boolean; stdcall;

        function GetUseRef(): boolean; stdcall;

    end;


    TD3D10_MESSAGE_CATEGORY = (
        D3D10_MESSAGE_CATEGORY_APPLICATION_DEFINED = 0,
        D3D10_MESSAGE_CATEGORY_MISCELLANEOUS = Ord(D3D10_MESSAGE_CATEGORY_APPLICATION_DEFINED) + 1,
        D3D10_MESSAGE_CATEGORY_INITIALIZATION = Ord(D3D10_MESSAGE_CATEGORY_MISCELLANEOUS) + 1,
        D3D10_MESSAGE_CATEGORY_CLEANUP = Ord(D3D10_MESSAGE_CATEGORY_INITIALIZATION) + 1,
        D3D10_MESSAGE_CATEGORY_COMPILATION = Ord(D3D10_MESSAGE_CATEGORY_CLEANUP) + 1,
        D3D10_MESSAGE_CATEGORY_STATE_CREATION = Ord(D3D10_MESSAGE_CATEGORY_COMPILATION) + 1,
        D3D10_MESSAGE_CATEGORY_STATE_SETTING = Ord(D3D10_MESSAGE_CATEGORY_STATE_CREATION) + 1,
        D3D10_MESSAGE_CATEGORY_STATE_GETTING = Ord(D3D10_MESSAGE_CATEGORY_STATE_SETTING) + 1,
        D3D10_MESSAGE_CATEGORY_RESOURCE_MANIPULATION = Ord(D3D10_MESSAGE_CATEGORY_STATE_GETTING) + 1,
        D3D10_MESSAGE_CATEGORY_EXECUTION = Ord(D3D10_MESSAGE_CATEGORY_RESOURCE_MANIPULATION) + 1,
        D3D10_MESSAGE_CATEGORY_SHADER = Ord(D3D10_MESSAGE_CATEGORY_EXECUTION) + 1);

    PD3D10_MESSAGE_CATEGORY = ^TD3D10_MESSAGE_CATEGORY;


    TD3D10_MESSAGE_SEVERITY = (
        D3D10_MESSAGE_SEVERITY_CORRUPTION = 0,
        D3D10_MESSAGE_SEVERITY_ERROR = Ord(D3D10_MESSAGE_SEVERITY_CORRUPTION) + 1,
        D3D10_MESSAGE_SEVERITY_WARNING = Ord(D3D10_MESSAGE_SEVERITY_ERROR) + 1,
        D3D10_MESSAGE_SEVERITY_INFO = Ord(D3D10_MESSAGE_SEVERITY_WARNING) + 1,
        D3D10_MESSAGE_SEVERITY_MESSAGE = Ord(D3D10_MESSAGE_SEVERITY_INFO) + 1);

    PD3D10_MESSAGE_SEVERITY = ^TD3D10_MESSAGE_SEVERITY;


    TD3D10_MESSAGE_ID = (
        D3D10_MESSAGE_ID_UNKNOWN = 0,
        D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_HAZARD = Ord(D3D10_MESSAGE_ID_UNKNOWN) + 1,
        D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_HAZARD = Ord(D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_HAZARD) + 1,
        D3D10_MESSAGE_ID_DEVICE_VSSETSHADERRESOURCES_HAZARD = Ord(D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_HAZARD) + 1,
        D3D10_MESSAGE_ID_DEVICE_VSSETCONSTANTBUFFERS_HAZARD = Ord(D3D10_MESSAGE_ID_DEVICE_VSSETSHADERRESOURCES_HAZARD) + 1,
        D3D10_MESSAGE_ID_DEVICE_GSSETSHADERRESOURCES_HAZARD = Ord(D3D10_MESSAGE_ID_DEVICE_VSSETCONSTANTBUFFERS_HAZARD) + 1,
        D3D10_MESSAGE_ID_DEVICE_GSSETCONSTANTBUFFERS_HAZARD = Ord(D3D10_MESSAGE_ID_DEVICE_GSSETSHADERRESOURCES_HAZARD) + 1,
        D3D10_MESSAGE_ID_DEVICE_PSSETSHADERRESOURCES_HAZARD = Ord(D3D10_MESSAGE_ID_DEVICE_GSSETCONSTANTBUFFERS_HAZARD) + 1,
        D3D10_MESSAGE_ID_DEVICE_PSSETCONSTANTBUFFERS_HAZARD = Ord(D3D10_MESSAGE_ID_DEVICE_PSSETSHADERRESOURCES_HAZARD) + 1,
        D3D10_MESSAGE_ID_DEVICE_OMSETRENDERTARGETS_HAZARD = Ord(D3D10_MESSAGE_ID_DEVICE_PSSETCONSTANTBUFFERS_HAZARD) + 1,
        D3D10_MESSAGE_ID_DEVICE_SOSETTARGETS_HAZARD = Ord(D3D10_MESSAGE_ID_DEVICE_OMSETRENDERTARGETS_HAZARD) + 1,
        D3D10_MESSAGE_ID_STRING_FROM_APPLICATION = Ord(D3D10_MESSAGE_ID_DEVICE_SOSETTARGETS_HAZARD) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_THIS = Ord(D3D10_MESSAGE_ID_STRING_FROM_APPLICATION) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER1 = Ord(D3D10_MESSAGE_ID_CORRUPTED_THIS) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER2 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER1) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER3 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER2) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER4 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER3) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER5 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER4) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER6 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER5) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER7 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER6) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER8 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER7) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER9 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER8) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER10 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER9) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER11 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER10) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER12 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER11) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER13 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER12) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER14 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER13) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_PARAMETER15 = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER14) + 1,
        D3D10_MESSAGE_ID_CORRUPTED_MULTITHREADING = Ord(D3D10_MESSAGE_ID_CORRUPTED_PARAMETER15) + 1,
        D3D10_MESSAGE_ID_MESSAGE_REPORTING_OUTOFMEMORY = Ord(D3D10_MESSAGE_ID_CORRUPTED_MULTITHREADING) + 1,
        D3D10_MESSAGE_ID_IASETINPUTLAYOUT_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_MESSAGE_REPORTING_OUTOFMEMORY) + 1,
        D3D10_MESSAGE_ID_IASETVERTEXBUFFERS_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_IASETINPUTLAYOUT_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_IASETINDEXBUFFER_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_IASETVERTEXBUFFERS_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_VSSETSHADER_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_IASETINDEXBUFFER_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_VSSETSHADERRESOURCES_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_VSSETSHADER_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_VSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_VSSETSHADERRESOURCES_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_VSSETSAMPLERS_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_VSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_GSSETSHADER_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_VSSETSAMPLERS_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_GSSETSHADERRESOURCES_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_GSSETSHADER_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_GSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_GSSETSHADERRESOURCES_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_GSSETSAMPLERS_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_GSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_SOSETTARGETS_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_GSSETSAMPLERS_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_PSSETSHADER_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_SOSETTARGETS_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_PSSETSHADERRESOURCES_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_PSSETSHADER_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_PSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_PSSETSHADERRESOURCES_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_PSSETSAMPLERS_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_PSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_RSSETSTATE_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_PSSETSAMPLERS_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_OMSETBLENDSTATE_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_RSSETSTATE_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_OMSETDEPTHSTENCILSTATE_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_OMSETBLENDSTATE_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_OMSETRENDERTARGETS_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_OMSETDEPTHSTENCILSTATE_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_SETPREDICATION_UNBINDDELETINGOBJECT = Ord(D3D10_MESSAGE_ID_OMSETRENDERTARGETS_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_GETPRIVATEDATA_MOREDATA = Ord(D3D10_MESSAGE_ID_SETPREDICATION_UNBINDDELETINGOBJECT) + 1,
        D3D10_MESSAGE_ID_SETPRIVATEDATA_INVALIDFREEDATA = Ord(D3D10_MESSAGE_ID_GETPRIVATEDATA_MOREDATA) + 1,
        D3D10_MESSAGE_ID_SETPRIVATEDATA_INVALIDIUNKNOWN = Ord(D3D10_MESSAGE_ID_SETPRIVATEDATA_INVALIDFREEDATA) + 1,
        D3D10_MESSAGE_ID_SETPRIVATEDATA_INVALIDFLAGS = Ord(D3D10_MESSAGE_ID_SETPRIVATEDATA_INVALIDIUNKNOWN) + 1,
        D3D10_MESSAGE_ID_SETPRIVATEDATA_CHANGINGPARAMS = Ord(D3D10_MESSAGE_ID_SETPRIVATEDATA_INVALIDFLAGS) + 1,
        D3D10_MESSAGE_ID_SETPRIVATEDATA_OUTOFMEMORY = Ord(D3D10_MESSAGE_ID_SETPRIVATEDATA_CHANGINGPARAMS) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDFORMAT = Ord(D3D10_MESSAGE_ID_SETPRIVATEDATA_OUTOFMEMORY) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDSAMPLES = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDUSAGE = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDSAMPLES) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDBINDFLAGS = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDUSAGE) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDCPUACCESSFLAGS = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDBINDFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDMISCFLAGS = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDCPUACCESSFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDCPUACCESSFLAGS = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDMISCFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDBINDFLAGS = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDCPUACCESSFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDINITIALDATA = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDBINDFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDDIMENSIONS = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDINITIALDATA) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDMIPLEVELS = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDDIMENSIONS) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDMISCFLAGS = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDMIPLEVELS) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDARG_RETURN = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDMISCFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_OUTOFMEMORY_RETURN = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDARG_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_NULLDESC = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_OUTOFMEMORY_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDCONSTANTBUFFERBINDINGS = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_NULLDESC) + 1,
        D3D10_MESSAGE_ID_CREATEBUFFER_LARGEALLOCATION = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDCONSTANTBUFFERBINDINGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDFORMAT = Ord(D3D10_MESSAGE_ID_CREATEBUFFER_LARGEALLOCATION) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_UNSUPPORTEDFORMAT = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDSAMPLES = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_UNSUPPORTEDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDUSAGE = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDSAMPLES) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDBINDFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDUSAGE) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDCPUACCESSFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDBINDFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDMISCFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDCPUACCESSFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDCPUACCESSFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDMISCFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDBINDFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDCPUACCESSFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDINITIALDATA = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDBINDFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDDIMENSIONS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDINITIALDATA) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDMIPLEVELS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDDIMENSIONS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDMISCFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDMIPLEVELS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDARG_RETURN = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDMISCFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_OUTOFMEMORY_RETURN = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDARG_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_NULLDESC = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_OUTOFMEMORY_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE1D_LARGEALLOCATION = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_NULLDESC) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDFORMAT = Ord(D3D10_MESSAGE_ID_CREATETEXTURE1D_LARGEALLOCATION) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_UNSUPPORTEDFORMAT = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDSAMPLES = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_UNSUPPORTEDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDUSAGE = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDSAMPLES) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDBINDFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDUSAGE) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDCPUACCESSFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDBINDFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDMISCFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDCPUACCESSFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDCPUACCESSFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDMISCFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDBINDFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDCPUACCESSFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDINITIALDATA = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDBINDFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDDIMENSIONS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDINITIALDATA) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDMIPLEVELS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDDIMENSIONS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDMISCFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDMIPLEVELS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDARG_RETURN = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDMISCFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_OUTOFMEMORY_RETURN = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDARG_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_NULLDESC = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_OUTOFMEMORY_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE2D_LARGEALLOCATION = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_NULLDESC) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDFORMAT = Ord(D3D10_MESSAGE_ID_CREATETEXTURE2D_LARGEALLOCATION) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_UNSUPPORTEDFORMAT = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDSAMPLES = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_UNSUPPORTEDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDUSAGE = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDSAMPLES) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDBINDFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDUSAGE) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDCPUACCESSFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDBINDFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDMISCFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDCPUACCESSFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDCPUACCESSFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDMISCFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDBINDFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDCPUACCESSFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDINITIALDATA = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDBINDFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDDIMENSIONS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDINITIALDATA) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDMIPLEVELS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDDIMENSIONS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDMISCFLAGS = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDMIPLEVELS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDARG_RETURN = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDMISCFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_OUTOFMEMORY_RETURN = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDARG_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_NULLDESC = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_OUTOFMEMORY_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATETEXTURE3D_LARGEALLOCATION = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_NULLDESC) + 1,
        D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_UNRECOGNIZEDFORMAT = Ord(D3D10_MESSAGE_ID_CREATETEXTURE3D_LARGEALLOCATION) + 1,
        D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDDESC = Ord(D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_UNRECOGNIZEDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDFORMAT = Ord(D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDDESC) + 1,
        D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDDIMENSIONS = Ord(D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDRESOURCE = Ord(D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDDIMENSIONS) + 1,
        D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_TOOMANYOBJECTS = Ord(D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDRESOURCE) + 1,
        D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDARG_RETURN = Ord(D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_TOOMANYOBJECTS) + 1,
        D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_OUTOFMEMORY_RETURN = Ord(D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDARG_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_UNRECOGNIZEDFORMAT = Ord(D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_OUTOFMEMORY_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_UNSUPPORTEDFORMAT = Ord(D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_UNRECOGNIZEDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDDESC = Ord(D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_UNSUPPORTEDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDFORMAT = Ord(D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDDESC) + 1,
        D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDDIMENSIONS = Ord(D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDRESOURCE = Ord(D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDDIMENSIONS) + 1,
        D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_TOOMANYOBJECTS = Ord(D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDRESOURCE) + 1,
        D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDARG_RETURN = Ord(D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_TOOMANYOBJECTS) + 1,
        D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_OUTOFMEMORY_RETURN = Ord(D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDARG_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_UNRECOGNIZEDFORMAT = Ord(D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_OUTOFMEMORY_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDDESC = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_UNRECOGNIZEDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDFORMAT = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDDESC) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDDIMENSIONS = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDRESOURCE = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDDIMENSIONS) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_TOOMANYOBJECTS = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDRESOURCE) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDARG_RETURN = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_TOOMANYOBJECTS) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_OUTOFMEMORY_RETURN = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDARG_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_OUTOFMEMORY = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_OUTOFMEMORY_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_TOOMANYELEMENTS = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_OUTOFMEMORY) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDFORMAT = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_TOOMANYELEMENTS) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INCOMPATIBLEFORMAT = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSLOT = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INCOMPATIBLEFORMAT) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDINPUTSLOTCLASS = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSLOT) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_STEPRATESLOTCLASSMISMATCH = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDINPUTSLOTCLASS) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSLOTCLASSCHANGE = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_STEPRATESLOTCLASSMISMATCH) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSTEPRATECHANGE = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSLOTCLASSCHANGE) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDALIGNMENT = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSTEPRATECHANGE) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_DUPLICATESEMANTIC = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDALIGNMENT) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_DUPLICATESEMANTIC) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_NULLSEMANTIC = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_MISSINGELEMENT = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_NULLSEMANTIC) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_NULLDESC = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_MISSINGELEMENT) + 1,
        D3D10_MESSAGE_ID_CREATEVERTEXSHADER_OUTOFMEMORY = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_NULLDESC) + 1,
        D3D10_MESSAGE_ID_CREATEVERTEXSHADER_INVALIDSHADERBYTECODE = Ord(D3D10_MESSAGE_ID_CREATEVERTEXSHADER_OUTOFMEMORY) + 1,
        D3D10_MESSAGE_ID_CREATEVERTEXSHADER_INVALIDSHADERTYPE = Ord(D3D10_MESSAGE_ID_CREATEVERTEXSHADER_INVALIDSHADERBYTECODE) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADER_OUTOFMEMORY = Ord(D3D10_MESSAGE_ID_CREATEVERTEXSHADER_INVALIDSHADERTYPE) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADER_INVALIDSHADERBYTECODE = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADER_OUTOFMEMORY) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADER_INVALIDSHADERTYPE = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADER_INVALIDSHADERBYTECODE) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTOFMEMORY = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADER_INVALIDSHADERTYPE) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERBYTECODE = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTOFMEMORY) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERTYPE = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERBYTECODE) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMENTRIES = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERTYPE) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSTREAMSTRIDEUNUSED = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMENTRIES) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDDECL = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSTREAMSTRIDEUNUSED) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_EXPECTEDDECL = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDDECL) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSLOT0EXPECTED = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_EXPECTEDDECL) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSLOT = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSLOT0EXPECTED) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_ONLYONEELEMENTPERSLOT = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSLOT) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDCOMPONENTCOUNT = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_ONLYONEELEMENTPERSLOT) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTARTCOMPONENTANDCOMPONENTCOUNT = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDCOMPONENTCOUNT) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDGAPDEFINITION = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTARTCOMPONENTANDCOMPONENTCOUNT) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_REPEATEDOUTPUT = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDGAPDEFINITION) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSTREAMSTRIDE = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_REPEATEDOUTPUT) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGSEMANTIC = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSTREAMSTRIDE) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MASKMISMATCH = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGSEMANTIC) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_CANTHAVEONLYGAPS = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MASKMISMATCH) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DECLTOOCOMPLEX = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_CANTHAVEONLYGAPS) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGOUTPUTSIGNATURE = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DECLTOOCOMPLEX) + 1,
        D3D10_MESSAGE_ID_CREATEPIXELSHADER_OUTOFMEMORY = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGOUTPUTSIGNATURE) + 1,
        D3D10_MESSAGE_ID_CREATEPIXELSHADER_INVALIDSHADERBYTECODE = Ord(D3D10_MESSAGE_ID_CREATEPIXELSHADER_OUTOFMEMORY) + 1,
        D3D10_MESSAGE_ID_CREATEPIXELSHADER_INVALIDSHADERTYPE = Ord(D3D10_MESSAGE_ID_CREATEPIXELSHADER_INVALIDSHADERBYTECODE) + 1,
        D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDFILLMODE = Ord(D3D10_MESSAGE_ID_CREATEPIXELSHADER_INVALIDSHADERTYPE) + 1,
        D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDCULLMODE = Ord(D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDFILLMODE) + 1,
        D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDDEPTHBIASCLAMP = Ord(D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDCULLMODE) + 1,
        D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDSLOPESCALEDDEPTHBIAS = Ord(D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDDEPTHBIASCLAMP) + 1,
        D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_TOOMANYOBJECTS = Ord(D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDSLOPESCALEDDEPTHBIAS) + 1,
        D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_NULLDESC = Ord(D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_TOOMANYOBJECTS) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDDEPTHWRITEMASK = Ord(D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_NULLDESC) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDDEPTHFUNC = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDDEPTHWRITEMASK) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFAILOP = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDDEPTHFUNC) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILZFAILOP = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFAILOP) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILPASSOP = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILZFAILOP) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFUNC = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILPASSOP) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFAILOP = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFUNC) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILZFAILOP = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFAILOP) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILPASSOP = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILZFAILOP) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFUNC = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILPASSOP) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_TOOMANYOBJECTS = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFUNC) + 1,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_NULLDESC = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_TOOMANYOBJECTS) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDSRCBLEND = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_NULLDESC) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDDESTBLEND = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDSRCBLEND) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDBLENDOP = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDDESTBLEND) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDSRCBLENDALPHA = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDBLENDOP) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDDESTBLENDALPHA = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDSRCBLENDALPHA) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDBLENDOPALPHA = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDDESTBLENDALPHA) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDRENDERTARGETWRITEMASK = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDBLENDOPALPHA) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_TOOMANYOBJECTS = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDRENDERTARGETWRITEMASK) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_NULLDESC = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_TOOMANYOBJECTS) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDFILTER = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_NULLDESC) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSU = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDFILTER) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSV = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSU) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSW = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSV) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMIPLODBIAS = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSW) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMAXANISOTROPY = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMIPLODBIAS) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDCOMPARISONFUNC = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMAXANISOTROPY) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMINLOD = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDCOMPARISONFUNC) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMAXLOD = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMINLOD) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_TOOMANYOBJECTS = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMAXLOD) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_NULLDESC = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_TOOMANYOBJECTS) + 1,
        D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_INVALIDQUERY = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_NULLDESC) + 1,
        D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_INVALIDMISCFLAGS = Ord(D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_INVALIDQUERY) + 1,
        D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_UNEXPECTEDMISCFLAG = Ord(D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_INVALIDMISCFLAGS) + 1,
        D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_NULLDESC = Ord(D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_UNEXPECTEDMISCFLAG) + 1,
        D3D10_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNRECOGNIZED = Ord(D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_NULLDESC) + 1,
        D3D10_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNDEFINED = Ord(D3D10_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNRECOGNIZED) + 1,
        D3D10_MESSAGE_ID_IASETVERTEXBUFFERS_INVALIDBUFFER = Ord(D3D10_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNDEFINED) + 1,
        D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_OFFSET_TOO_LARGE = Ord(D3D10_MESSAGE_ID_IASETVERTEXBUFFERS_INVALIDBUFFER) + 1,
        D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_BUFFERS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_OFFSET_TOO_LARGE) + 1,
        D3D10_MESSAGE_ID_IASETINDEXBUFFER_INVALIDBUFFER = Ord(D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_BUFFERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_FORMAT_INVALID = Ord(D3D10_MESSAGE_ID_IASETINDEXBUFFER_INVALIDBUFFER) + 1,
        D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_OFFSET_TOO_LARGE = Ord(D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_FORMAT_INVALID) + 1,
        D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_OFFSET_UNALIGNED = Ord(D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_OFFSET_TOO_LARGE) + 1,
        D3D10_MESSAGE_ID_DEVICE_VSSETSHADERRESOURCES_VIEWS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_OFFSET_UNALIGNED) + 1,
        D3D10_MESSAGE_ID_VSSETCONSTANTBUFFERS_INVALIDBUFFER = Ord(D3D10_MESSAGE_ID_DEVICE_VSSETSHADERRESOURCES_VIEWS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_VSSETCONSTANTBUFFERS_BUFFERS_EMPTY = Ord(D3D10_MESSAGE_ID_VSSETCONSTANTBUFFERS_INVALIDBUFFER) + 1,
        D3D10_MESSAGE_ID_DEVICE_VSSETSAMPLERS_SAMPLERS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_VSSETCONSTANTBUFFERS_BUFFERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_GSSETSHADERRESOURCES_VIEWS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_VSSETSAMPLERS_SAMPLERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_GSSETCONSTANTBUFFERS_INVALIDBUFFER = Ord(D3D10_MESSAGE_ID_DEVICE_GSSETSHADERRESOURCES_VIEWS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_GSSETCONSTANTBUFFERS_BUFFERS_EMPTY = Ord(D3D10_MESSAGE_ID_GSSETCONSTANTBUFFERS_INVALIDBUFFER) + 1,
        D3D10_MESSAGE_ID_DEVICE_GSSETSAMPLERS_SAMPLERS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_GSSETCONSTANTBUFFERS_BUFFERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_SOSETTARGETS_INVALIDBUFFER = Ord(D3D10_MESSAGE_ID_DEVICE_GSSETSAMPLERS_SAMPLERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_SOSETTARGETS_OFFSET_UNALIGNED = Ord(D3D10_MESSAGE_ID_SOSETTARGETS_INVALIDBUFFER) + 1,
        D3D10_MESSAGE_ID_DEVICE_PSSETSHADERRESOURCES_VIEWS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_SOSETTARGETS_OFFSET_UNALIGNED) + 1,
        D3D10_MESSAGE_ID_PSSETCONSTANTBUFFERS_INVALIDBUFFER = Ord(D3D10_MESSAGE_ID_DEVICE_PSSETSHADERRESOURCES_VIEWS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_PSSETCONSTANTBUFFERS_BUFFERS_EMPTY = Ord(D3D10_MESSAGE_ID_PSSETCONSTANTBUFFERS_INVALIDBUFFER) + 1,
        D3D10_MESSAGE_ID_DEVICE_PSSETSAMPLERS_SAMPLERS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_PSSETCONSTANTBUFFERS_BUFFERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_INVALIDVIEWPORT = Ord(D3D10_MESSAGE_ID_DEVICE_PSSETSAMPLERS_SAMPLERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_INVALIDSCISSOR = Ord(D3D10_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_INVALIDVIEWPORT) + 1,
        D3D10_MESSAGE_ID_CLEARRENDERTARGETVIEW_DENORMFLUSH = Ord(D3D10_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_INVALIDSCISSOR) + 1,
        D3D10_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_DENORMFLUSH = Ord(D3D10_MESSAGE_ID_CLEARRENDERTARGETVIEW_DENORMFLUSH) + 1,
        D3D10_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_INVALID = Ord(D3D10_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_DENORMFLUSH) + 1,
        D3D10_MESSAGE_ID_DEVICE_IAGETVERTEXBUFFERS_BUFFERS_EMPTY = Ord(D3D10_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_INVALID) + 1,
        D3D10_MESSAGE_ID_DEVICE_VSGETSHADERRESOURCES_VIEWS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_IAGETVERTEXBUFFERS_BUFFERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_VSGETCONSTANTBUFFERS_BUFFERS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_VSGETSHADERRESOURCES_VIEWS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_VSGETSAMPLERS_SAMPLERS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_VSGETCONSTANTBUFFERS_BUFFERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_GSGETSHADERRESOURCES_VIEWS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_VSGETSAMPLERS_SAMPLERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_GSGETCONSTANTBUFFERS_BUFFERS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_GSGETSHADERRESOURCES_VIEWS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_GSGETSAMPLERS_SAMPLERS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_GSGETCONSTANTBUFFERS_BUFFERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_SOGETTARGETS_BUFFERS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_GSGETSAMPLERS_SAMPLERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_PSGETSHADERRESOURCES_VIEWS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_SOGETTARGETS_BUFFERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_PSGETCONSTANTBUFFERS_BUFFERS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_PSGETSHADERRESOURCES_VIEWS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_PSGETSAMPLERS_SAMPLERS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_PSGETCONSTANTBUFFERS_BUFFERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_RSGETVIEWPORTS_VIEWPORTS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_PSGETSAMPLERS_SAMPLERS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_RSGETSCISSORRECTS_RECTS_EMPTY = Ord(D3D10_MESSAGE_ID_DEVICE_RSGETVIEWPORTS_VIEWPORTS_EMPTY) + 1,
        D3D10_MESSAGE_ID_DEVICE_GENERATEMIPS_RESOURCE_INVALID = Ord(D3D10_MESSAGE_ID_DEVICE_RSGETSCISSORRECTS_RECTS_EMPTY) + 1,
        D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDDESTINATIONSUBRESOURCE = Ord(D3D10_MESSAGE_ID_DEVICE_GENERATEMIPS_RESOURCE_INVALID) + 1,
        D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCESUBRESOURCE = Ord(D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDDESTINATIONSUBRESOURCE) + 1,
        D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCEBOX = Ord(D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCESUBRESOURCE) + 1,
        D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCE = Ord(D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCEBOX) + 1,
        D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDDESTINATIONSTATE = Ord(D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCE) + 1,
        D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCESTATE = Ord(D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDDESTINATIONSTATE) + 1,
        D3D10_MESSAGE_ID_COPYRESOURCE_INVALIDSOURCE = Ord(D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCESTATE) + 1,
        D3D10_MESSAGE_ID_COPYRESOURCE_INVALIDDESTINATIONSTATE = Ord(D3D10_MESSAGE_ID_COPYRESOURCE_INVALIDSOURCE) + 1,
        D3D10_MESSAGE_ID_COPYRESOURCE_INVALIDSOURCESTATE = Ord(D3D10_MESSAGE_ID_COPYRESOURCE_INVALIDDESTINATIONSTATE) + 1,
        D3D10_MESSAGE_ID_UPDATESUBRESOURCE_INVALIDDESTINATIONSUBRESOURCE = Ord(D3D10_MESSAGE_ID_COPYRESOURCE_INVALIDSOURCESTATE) + 1,
        D3D10_MESSAGE_ID_UPDATESUBRESOURCE_INVALIDDESTINATIONBOX = Ord(D3D10_MESSAGE_ID_UPDATESUBRESOURCE_INVALIDDESTINATIONSUBRESOURCE) + 1,
        D3D10_MESSAGE_ID_UPDATESUBRESOURCE_INVALIDDESTINATIONSTATE = Ord(D3D10_MESSAGE_ID_UPDATESUBRESOURCE_INVALIDDESTINATIONBOX) + 1,
        D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_DESTINATION_INVALID = Ord(D3D10_MESSAGE_ID_UPDATESUBRESOURCE_INVALIDDESTINATIONSTATE) + 1,
        D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_DESTINATION_SUBRESOURCE_INVALID = Ord(D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_DESTINATION_INVALID) + 1,
        D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_SOURCE_INVALID = Ord(D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_DESTINATION_SUBRESOURCE_INVALID) + 1,
        D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_SOURCE_SUBRESOURCE_INVALID = Ord(D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_SOURCE_INVALID) + 1,
        D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_FORMAT_INVALID = Ord(D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_SOURCE_SUBRESOURCE_INVALID) + 1,
        D3D10_MESSAGE_ID_BUFFER_MAP_INVALIDMAPTYPE = Ord(D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_FORMAT_INVALID) + 1,
        D3D10_MESSAGE_ID_BUFFER_MAP_INVALIDFLAGS = Ord(D3D10_MESSAGE_ID_BUFFER_MAP_INVALIDMAPTYPE) + 1,
        D3D10_MESSAGE_ID_BUFFER_MAP_ALREADYMAPPED = Ord(D3D10_MESSAGE_ID_BUFFER_MAP_INVALIDFLAGS) + 1,
        D3D10_MESSAGE_ID_BUFFER_MAP_DEVICEREMOVED_RETURN = Ord(D3D10_MESSAGE_ID_BUFFER_MAP_ALREADYMAPPED) + 1,
        D3D10_MESSAGE_ID_BUFFER_UNMAP_NOTMAPPED = Ord(D3D10_MESSAGE_ID_BUFFER_MAP_DEVICEREMOVED_RETURN) + 1,
        D3D10_MESSAGE_ID_TEXTURE1D_MAP_INVALIDMAPTYPE = Ord(D3D10_MESSAGE_ID_BUFFER_UNMAP_NOTMAPPED) + 1,
        D3D10_MESSAGE_ID_TEXTURE1D_MAP_INVALIDSUBRESOURCE = Ord(D3D10_MESSAGE_ID_TEXTURE1D_MAP_INVALIDMAPTYPE) + 1,
        D3D10_MESSAGE_ID_TEXTURE1D_MAP_INVALIDFLAGS = Ord(D3D10_MESSAGE_ID_TEXTURE1D_MAP_INVALIDSUBRESOURCE) + 1,
        D3D10_MESSAGE_ID_TEXTURE1D_MAP_ALREADYMAPPED = Ord(D3D10_MESSAGE_ID_TEXTURE1D_MAP_INVALIDFLAGS) + 1,
        D3D10_MESSAGE_ID_TEXTURE1D_MAP_DEVICEREMOVED_RETURN = Ord(D3D10_MESSAGE_ID_TEXTURE1D_MAP_ALREADYMAPPED) + 1,
        D3D10_MESSAGE_ID_TEXTURE1D_UNMAP_INVALIDSUBRESOURCE = Ord(D3D10_MESSAGE_ID_TEXTURE1D_MAP_DEVICEREMOVED_RETURN) + 1,
        D3D10_MESSAGE_ID_TEXTURE1D_UNMAP_NOTMAPPED = Ord(D3D10_MESSAGE_ID_TEXTURE1D_UNMAP_INVALIDSUBRESOURCE) + 1,
        D3D10_MESSAGE_ID_TEXTURE2D_MAP_INVALIDMAPTYPE = Ord(D3D10_MESSAGE_ID_TEXTURE1D_UNMAP_NOTMAPPED) + 1,
        D3D10_MESSAGE_ID_TEXTURE2D_MAP_INVALIDSUBRESOURCE = Ord(D3D10_MESSAGE_ID_TEXTURE2D_MAP_INVALIDMAPTYPE) + 1,
        D3D10_MESSAGE_ID_TEXTURE2D_MAP_INVALIDFLAGS = Ord(D3D10_MESSAGE_ID_TEXTURE2D_MAP_INVALIDSUBRESOURCE) + 1,
        D3D10_MESSAGE_ID_TEXTURE2D_MAP_ALREADYMAPPED = Ord(D3D10_MESSAGE_ID_TEXTURE2D_MAP_INVALIDFLAGS) + 1,
        D3D10_MESSAGE_ID_TEXTURE2D_MAP_DEVICEREMOVED_RETURN = Ord(D3D10_MESSAGE_ID_TEXTURE2D_MAP_ALREADYMAPPED) + 1,
        D3D10_MESSAGE_ID_TEXTURE2D_UNMAP_INVALIDSUBRESOURCE = Ord(D3D10_MESSAGE_ID_TEXTURE2D_MAP_DEVICEREMOVED_RETURN) + 1,
        D3D10_MESSAGE_ID_TEXTURE2D_UNMAP_NOTMAPPED = Ord(D3D10_MESSAGE_ID_TEXTURE2D_UNMAP_INVALIDSUBRESOURCE) + 1,
        D3D10_MESSAGE_ID_TEXTURE3D_MAP_INVALIDMAPTYPE = Ord(D3D10_MESSAGE_ID_TEXTURE2D_UNMAP_NOTMAPPED) + 1,
        D3D10_MESSAGE_ID_TEXTURE3D_MAP_INVALIDSUBRESOURCE = Ord(D3D10_MESSAGE_ID_TEXTURE3D_MAP_INVALIDMAPTYPE) + 1,
        D3D10_MESSAGE_ID_TEXTURE3D_MAP_INVALIDFLAGS = Ord(D3D10_MESSAGE_ID_TEXTURE3D_MAP_INVALIDSUBRESOURCE) + 1,
        D3D10_MESSAGE_ID_TEXTURE3D_MAP_ALREADYMAPPED = Ord(D3D10_MESSAGE_ID_TEXTURE3D_MAP_INVALIDFLAGS) + 1,
        D3D10_MESSAGE_ID_TEXTURE3D_MAP_DEVICEREMOVED_RETURN = Ord(D3D10_MESSAGE_ID_TEXTURE3D_MAP_ALREADYMAPPED) + 1,
        D3D10_MESSAGE_ID_TEXTURE3D_UNMAP_INVALIDSUBRESOURCE = Ord(D3D10_MESSAGE_ID_TEXTURE3D_MAP_DEVICEREMOVED_RETURN) + 1,
        D3D10_MESSAGE_ID_TEXTURE3D_UNMAP_NOTMAPPED = Ord(D3D10_MESSAGE_ID_TEXTURE3D_UNMAP_INVALIDSUBRESOURCE) + 1,
        D3D10_MESSAGE_ID_CHECKFORMATSUPPORT_FORMAT_DEPRECATED = Ord(D3D10_MESSAGE_ID_TEXTURE3D_UNMAP_NOTMAPPED) + 1,
        D3D10_MESSAGE_ID_CHECKMULTISAMPLEQUALITYLEVELS_FORMAT_DEPRECATED = Ord(D3D10_MESSAGE_ID_CHECKFORMATSUPPORT_FORMAT_DEPRECATED) + 1,
        D3D10_MESSAGE_ID_SETEXCEPTIONMODE_UNRECOGNIZEDFLAGS = Ord(D3D10_MESSAGE_ID_CHECKMULTISAMPLEQUALITYLEVELS_FORMAT_DEPRECATED) + 1,
        D3D10_MESSAGE_ID_SETEXCEPTIONMODE_INVALIDARG_RETURN = Ord(D3D10_MESSAGE_ID_SETEXCEPTIONMODE_UNRECOGNIZEDFLAGS) + 1,
        D3D10_MESSAGE_ID_SETEXCEPTIONMODE_DEVICEREMOVED_RETURN = Ord(D3D10_MESSAGE_ID_SETEXCEPTIONMODE_INVALIDARG_RETURN) + 1,
        D3D10_MESSAGE_ID_REF_SIMULATING_INFINITELY_FAST_HARDWARE = Ord(D3D10_MESSAGE_ID_SETEXCEPTIONMODE_DEVICEREMOVED_RETURN) + 1,
        D3D10_MESSAGE_ID_REF_THREADING_MODE = Ord(D3D10_MESSAGE_ID_REF_SIMULATING_INFINITELY_FAST_HARDWARE) + 1,
        D3D10_MESSAGE_ID_REF_UMDRIVER_EXCEPTION = Ord(D3D10_MESSAGE_ID_REF_THREADING_MODE) + 1,
        D3D10_MESSAGE_ID_REF_KMDRIVER_EXCEPTION = Ord(D3D10_MESSAGE_ID_REF_UMDRIVER_EXCEPTION) + 1,
        D3D10_MESSAGE_ID_REF_HARDWARE_EXCEPTION = Ord(D3D10_MESSAGE_ID_REF_KMDRIVER_EXCEPTION) + 1,
        D3D10_MESSAGE_ID_REF_ACCESSING_INDEXABLE_TEMP_OUT_OF_RANGE = Ord(D3D10_MESSAGE_ID_REF_HARDWARE_EXCEPTION) + 1,
        D3D10_MESSAGE_ID_REF_PROBLEM_PARSING_SHADER = Ord(D3D10_MESSAGE_ID_REF_ACCESSING_INDEXABLE_TEMP_OUT_OF_RANGE) + 1,
        D3D10_MESSAGE_ID_REF_OUT_OF_MEMORY = Ord(D3D10_MESSAGE_ID_REF_PROBLEM_PARSING_SHADER) + 1,
        D3D10_MESSAGE_ID_REF_INFO = Ord(D3D10_MESSAGE_ID_REF_OUT_OF_MEMORY) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEXPOS_OVERFLOW = Ord(D3D10_MESSAGE_ID_REF_INFO) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAWINDEXED_INDEXPOS_OVERFLOW = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEXPOS_OVERFLOW) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAWINSTANCED_VERTEXPOS_OVERFLOW = Ord(D3D10_MESSAGE_ID_DEVICE_DRAWINDEXED_INDEXPOS_OVERFLOW) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAWINSTANCED_INSTANCEPOS_OVERFLOW = Ord(D3D10_MESSAGE_ID_DEVICE_DRAWINSTANCED_VERTEXPOS_OVERFLOW) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAWINDEXEDINSTANCED_INSTANCEPOS_OVERFLOW = Ord(D3D10_MESSAGE_ID_DEVICE_DRAWINSTANCED_INSTANCEPOS_OVERFLOW) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAWINDEXEDINSTANCED_INDEXPOS_OVERFLOW = Ord(D3D10_MESSAGE_ID_DEVICE_DRAWINDEXEDINSTANCED_INSTANCEPOS_OVERFLOW) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_SHADER_NOT_SET = Ord(D3D10_MESSAGE_ID_DEVICE_DRAWINDEXEDINSTANCED_INDEXPOS_OVERFLOW) + 1,
        D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_SHADER_NOT_SET) + 1,
        D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_REGISTERINDEX = Ord(D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND) + 1,
        D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_COMPONENTTYPE = Ord(D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_REGISTERINDEX) + 1,
        D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_REGISTERMASK = Ord(D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_COMPONENTTYPE) + 1,
        D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_SYSTEMVALUE = Ord(D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_REGISTERMASK) + 1,
        D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_NEVERWRITTEN_ALWAYSREADS = Ord(D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_SYSTEMVALUE) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_BUFFER_NOT_SET = Ord(D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_NEVERWRITTEN_ALWAYSREADS) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_INPUTLAYOUT_NOT_SET = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_BUFFER_NOT_SET) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_CONSTANT_BUFFER_NOT_SET = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_INPUTLAYOUT_NOT_SET) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_CONSTANT_BUFFER_TOO_SMALL = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_CONSTANT_BUFFER_NOT_SET) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_SAMPLER_NOT_SET = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_CONSTANT_BUFFER_TOO_SMALL) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_SHADERRESOURCEVIEW_NOT_SET = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_SAMPLER_NOT_SET) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_VIEW_DIMENSION_MISMATCH = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_SHADERRESOURCEVIEW_NOT_SET) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_BUFFER_STRIDE_TOO_SMALL = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_VIEW_DIMENSION_MISMATCH) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_BUFFER_TOO_SMALL = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_BUFFER_STRIDE_TOO_SMALL) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_NOT_SET = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_BUFFER_TOO_SMALL) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_FORMAT_INVALID = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_NOT_SET) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_TOO_SMALL = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_FORMAT_INVALID) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_GS_INPUT_PRIMITIVE_MISMATCH = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_TOO_SMALL) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_RETURN_TYPE_MISMATCH = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_GS_INPUT_PRIMITIVE_MISMATCH) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_POSITION_NOT_PRESENT = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_RETURN_TYPE_MISMATCH) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_OUTPUT_STREAM_NOT_SET = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_POSITION_NOT_PRESENT) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_BOUND_RESOURCE_MAPPED = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_OUTPUT_STREAM_NOT_SET) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_INVALID_PRIMITIVETOPOLOGY = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_BOUND_RESOURCE_MAPPED) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_OFFSET_UNALIGNED = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_INVALID_PRIMITIVETOPOLOGY) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_STRIDE_UNALIGNED = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_OFFSET_UNALIGNED) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_INDEX_OFFSET_UNALIGNED = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_STRIDE_UNALIGNED) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_OUTPUT_STREAM_OFFSET_UNALIGNED = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_INDEX_OFFSET_UNALIGNED) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_LD_UNSUPPORTED = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_OUTPUT_STREAM_OFFSET_UNALIGNED) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_SAMPLE_UNSUPPORTED = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_LD_UNSUPPORTED) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_SAMPLE_C_UNSUPPORTED = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_SAMPLE_UNSUPPORTED) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_MULTISAMPLE_UNSUPPORTED = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_SAMPLE_C_UNSUPPORTED) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_SO_TARGETS_BOUND_WITHOUT_SOURCE = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_MULTISAMPLE_UNSUPPORTED) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_SO_STRIDE_LARGER_THAN_BUFFER = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_SO_TARGETS_BOUND_WITHOUT_SOURCE) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_OM_RENDER_TARGET_DOES_NOT_SUPPORT_BLENDING = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_SO_STRIDE_LARGER_THAN_BUFFER) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_OM_DUAL_SOURCE_BLENDING_CAN_ONLY_HAVE_RENDER_TARGET_0 = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_OM_RENDER_TARGET_DOES_NOT_SUPPORT_BLENDING) + 1,
        D3D10_MESSAGE_ID_DEVICE_REMOVAL_PROCESS_AT_FAULT = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_OM_DUAL_SOURCE_BLENDING_CAN_ONLY_HAVE_RENDER_TARGET_0) + 1,
        D3D10_MESSAGE_ID_DEVICE_REMOVAL_PROCESS_POSSIBLY_AT_FAULT = Ord(D3D10_MESSAGE_ID_DEVICE_REMOVAL_PROCESS_AT_FAULT) + 1,
        D3D10_MESSAGE_ID_DEVICE_REMOVAL_PROCESS_NOT_AT_FAULT = Ord(D3D10_MESSAGE_ID_DEVICE_REMOVAL_PROCESS_POSSIBLY_AT_FAULT) + 1,
        D3D10_MESSAGE_ID_DEVICE_OPEN_SHARED_RESOURCE_INVALIDARG_RETURN = Ord(D3D10_MESSAGE_ID_DEVICE_REMOVAL_PROCESS_NOT_AT_FAULT) + 1,
        D3D10_MESSAGE_ID_DEVICE_OPEN_SHARED_RESOURCE_OUTOFMEMORY_RETURN = Ord(D3D10_MESSAGE_ID_DEVICE_OPEN_SHARED_RESOURCE_INVALIDARG_RETURN) + 1,
        D3D10_MESSAGE_ID_DEVICE_OPEN_SHARED_RESOURCE_BADINTERFACE_RETURN = Ord(D3D10_MESSAGE_ID_DEVICE_OPEN_SHARED_RESOURCE_OUTOFMEMORY_RETURN) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_VIEWPORT_NOT_SET = Ord(D3D10_MESSAGE_ID_DEVICE_OPEN_SHARED_RESOURCE_BADINTERFACE_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_TRAILING_DIGIT_IN_SEMANTIC = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_VIEWPORT_NOT_SET) + 1,
        D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_TRAILING_DIGIT_IN_SEMANTIC = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_TRAILING_DIGIT_IN_SEMANTIC) + 1,
        D3D10_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_DENORMFLUSH = Ord(D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_TRAILING_DIGIT_IN_SEMANTIC) + 1,
        D3D10_MESSAGE_ID_OMSETRENDERTARGETS_INVALIDVIEW = Ord(D3D10_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_DENORMFLUSH) + 1,
        D3D10_MESSAGE_ID_DEVICE_SETTEXTFILTERSIZE_INVALIDDIMENSIONS = Ord(D3D10_MESSAGE_ID_OMSETRENDERTARGETS_INVALIDVIEW) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_SAMPLER_MISMATCH = Ord(D3D10_MESSAGE_ID_DEVICE_SETTEXTFILTERSIZE_INVALIDDIMENSIONS) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_TYPE_MISMATCH = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_SAMPLER_MISMATCH) + 1,
        D3D10_MESSAGE_ID_BLENDSTATE_GETDESC_LEGACY = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_TYPE_MISMATCH) + 1,
        D3D10_MESSAGE_ID_SHADERRESOURCEVIEW_GETDESC_LEGACY = Ord(D3D10_MESSAGE_ID_BLENDSTATE_GETDESC_LEGACY) + 1,
        D3D10_MESSAGE_ID_CREATEQUERY_OUTOFMEMORY_RETURN = Ord(D3D10_MESSAGE_ID_SHADERRESOURCEVIEW_GETDESC_LEGACY) + 1,
        D3D10_MESSAGE_ID_CREATEPREDICATE_OUTOFMEMORY_RETURN = Ord(D3D10_MESSAGE_ID_CREATEQUERY_OUTOFMEMORY_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATECOUNTER_OUTOFRANGE_COUNTER = Ord(D3D10_MESSAGE_ID_CREATEPREDICATE_OUTOFMEMORY_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATECOUNTER_SIMULTANEOUS_ACTIVE_COUNTERS_EXHAUSTED = Ord(D3D10_MESSAGE_ID_CREATECOUNTER_OUTOFRANGE_COUNTER) + 1,
        D3D10_MESSAGE_ID_CREATECOUNTER_UNSUPPORTED_WELLKNOWN_COUNTER = Ord(D3D10_MESSAGE_ID_CREATECOUNTER_SIMULTANEOUS_ACTIVE_COUNTERS_EXHAUSTED) + 1,
        D3D10_MESSAGE_ID_CREATECOUNTER_OUTOFMEMORY_RETURN = Ord(D3D10_MESSAGE_ID_CREATECOUNTER_UNSUPPORTED_WELLKNOWN_COUNTER) + 1,
        D3D10_MESSAGE_ID_CREATECOUNTER_NONEXCLUSIVE_RETURN = Ord(D3D10_MESSAGE_ID_CREATECOUNTER_OUTOFMEMORY_RETURN) + 1,
        D3D10_MESSAGE_ID_CREATECOUNTER_NULLDESC = Ord(D3D10_MESSAGE_ID_CREATECOUNTER_NONEXCLUSIVE_RETURN) + 1,
        D3D10_MESSAGE_ID_CHECKCOUNTER_OUTOFRANGE_COUNTER = Ord(D3D10_MESSAGE_ID_CREATECOUNTER_NULLDESC) + 1,
        D3D10_MESSAGE_ID_CHECKCOUNTER_UNSUPPORTED_WELLKNOWN_COUNTER = Ord(D3D10_MESSAGE_ID_CHECKCOUNTER_OUTOFRANGE_COUNTER) + 1,
        D3D10_MESSAGE_ID_SETPREDICATION_INVALID_PREDICATE_STATE = Ord(D3D10_MESSAGE_ID_CHECKCOUNTER_UNSUPPORTED_WELLKNOWN_COUNTER) + 1,
        D3D10_MESSAGE_ID_QUERY_BEGIN_UNSUPPORTED = Ord(D3D10_MESSAGE_ID_SETPREDICATION_INVALID_PREDICATE_STATE) + 1,
        D3D10_MESSAGE_ID_PREDICATE_BEGIN_DURING_PREDICATION = Ord(D3D10_MESSAGE_ID_QUERY_BEGIN_UNSUPPORTED) + 1,
        D3D10_MESSAGE_ID_QUERY_BEGIN_DUPLICATE = Ord(D3D10_MESSAGE_ID_PREDICATE_BEGIN_DURING_PREDICATION) + 1,
        D3D10_MESSAGE_ID_QUERY_BEGIN_ABANDONING_PREVIOUS_RESULTS = Ord(D3D10_MESSAGE_ID_QUERY_BEGIN_DUPLICATE) + 1,
        D3D10_MESSAGE_ID_PREDICATE_END_DURING_PREDICATION = Ord(D3D10_MESSAGE_ID_QUERY_BEGIN_ABANDONING_PREVIOUS_RESULTS) + 1,
        D3D10_MESSAGE_ID_QUERY_END_ABANDONING_PREVIOUS_RESULTS = Ord(D3D10_MESSAGE_ID_PREDICATE_END_DURING_PREDICATION) + 1,
        D3D10_MESSAGE_ID_QUERY_END_WITHOUT_BEGIN = Ord(D3D10_MESSAGE_ID_QUERY_END_ABANDONING_PREVIOUS_RESULTS) + 1,
        D3D10_MESSAGE_ID_QUERY_GETDATA_INVALID_DATASIZE = Ord(D3D10_MESSAGE_ID_QUERY_END_WITHOUT_BEGIN) + 1,
        D3D10_MESSAGE_ID_QUERY_GETDATA_INVALID_FLAGS = Ord(D3D10_MESSAGE_ID_QUERY_GETDATA_INVALID_DATASIZE) + 1,
        D3D10_MESSAGE_ID_QUERY_GETDATA_INVALID_CALL = Ord(D3D10_MESSAGE_ID_QUERY_GETDATA_INVALID_FLAGS) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_PS_OUTPUT_TYPE_MISMATCH = Ord(D3D10_MESSAGE_ID_QUERY_GETDATA_INVALID_CALL) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_GATHER_UNSUPPORTED = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_PS_OUTPUT_TYPE_MISMATCH) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_INVALID_USE_OF_CENTER_MULTISAMPLE_PATTERN = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_GATHER_UNSUPPORTED) + 1,
        D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_STRIDE_TOO_LARGE = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_INVALID_USE_OF_CENTER_MULTISAMPLE_PATTERN) + 1,
        D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_INVALIDRANGE = Ord(D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_STRIDE_TOO_LARGE) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_EMPTY_LAYOUT = Ord(D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_INVALIDRANGE) + 1,
        D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_SAMPLE_COUNT_MISMATCH = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_EMPTY_LAYOUT) + 1,
        D3D10_MESSAGE_ID_LIVE_OBJECT_SUMMARY = Ord(D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_SAMPLE_COUNT_MISMATCH) + 1,
        D3D10_MESSAGE_ID_LIVE_BUFFER = Ord(D3D10_MESSAGE_ID_LIVE_OBJECT_SUMMARY) + 1,
        D3D10_MESSAGE_ID_LIVE_TEXTURE1D = Ord(D3D10_MESSAGE_ID_LIVE_BUFFER) + 1,
        D3D10_MESSAGE_ID_LIVE_TEXTURE2D = Ord(D3D10_MESSAGE_ID_LIVE_TEXTURE1D) + 1,
        D3D10_MESSAGE_ID_LIVE_TEXTURE3D = Ord(D3D10_MESSAGE_ID_LIVE_TEXTURE2D) + 1,
        D3D10_MESSAGE_ID_LIVE_SHADERRESOURCEVIEW = Ord(D3D10_MESSAGE_ID_LIVE_TEXTURE3D) + 1,
        D3D10_MESSAGE_ID_LIVE_RENDERTARGETVIEW = Ord(D3D10_MESSAGE_ID_LIVE_SHADERRESOURCEVIEW) + 1,
        D3D10_MESSAGE_ID_LIVE_DEPTHSTENCILVIEW = Ord(D3D10_MESSAGE_ID_LIVE_RENDERTARGETVIEW) + 1,
        D3D10_MESSAGE_ID_LIVE_VERTEXSHADER = Ord(D3D10_MESSAGE_ID_LIVE_DEPTHSTENCILVIEW) + 1,
        D3D10_MESSAGE_ID_LIVE_GEOMETRYSHADER = Ord(D3D10_MESSAGE_ID_LIVE_VERTEXSHADER) + 1,
        D3D10_MESSAGE_ID_LIVE_PIXELSHADER = Ord(D3D10_MESSAGE_ID_LIVE_GEOMETRYSHADER) + 1,
        D3D10_MESSAGE_ID_LIVE_INPUTLAYOUT = Ord(D3D10_MESSAGE_ID_LIVE_PIXELSHADER) + 1,
        D3D10_MESSAGE_ID_LIVE_SAMPLER = Ord(D3D10_MESSAGE_ID_LIVE_INPUTLAYOUT) + 1,
        D3D10_MESSAGE_ID_LIVE_BLENDSTATE = Ord(D3D10_MESSAGE_ID_LIVE_SAMPLER) + 1,
        D3D10_MESSAGE_ID_LIVE_DEPTHSTENCILSTATE = Ord(D3D10_MESSAGE_ID_LIVE_BLENDSTATE) + 1,
        D3D10_MESSAGE_ID_LIVE_RASTERIZERSTATE = Ord(D3D10_MESSAGE_ID_LIVE_DEPTHSTENCILSTATE) + 1,
        D3D10_MESSAGE_ID_LIVE_QUERY = Ord(D3D10_MESSAGE_ID_LIVE_RASTERIZERSTATE) + 1,
        D3D10_MESSAGE_ID_LIVE_PREDICATE = Ord(D3D10_MESSAGE_ID_LIVE_QUERY) + 1,
        D3D10_MESSAGE_ID_LIVE_COUNTER = Ord(D3D10_MESSAGE_ID_LIVE_PREDICATE) + 1,
        D3D10_MESSAGE_ID_LIVE_DEVICE = Ord(D3D10_MESSAGE_ID_LIVE_COUNTER) + 1,
        D3D10_MESSAGE_ID_LIVE_SWAPCHAIN = Ord(D3D10_MESSAGE_ID_LIVE_DEVICE) + 1,
        D3D10_MESSAGE_ID_D3D10_MESSAGES_END = Ord(D3D10_MESSAGE_ID_LIVE_SWAPCHAIN) + 1,
        D3D10_MESSAGE_ID_D3D10L9_MESSAGES_START = $100000,
        D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_STENCIL_NO_TWO_SIDED = Ord(D3D10_MESSAGE_ID_D3D10L9_MESSAGES_START) + 1,
        D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_DepthBiasClamp_NOT_SUPPORTED = Ord(D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_STENCIL_NO_TWO_SIDED) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_NO_COMPARISON_SUPPORT = Ord(D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_DepthBiasClamp_NOT_SUPPORTED) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_EXCESSIVE_ANISOTROPY = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_NO_COMPARISON_SUPPORT) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_BORDER_OUT_OF_RANGE = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_EXCESSIVE_ANISOTROPY) + 1,
        D3D10_MESSAGE_ID_VSSETSAMPLERS_NOT_SUPPORTED = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_BORDER_OUT_OF_RANGE) + 1,
        D3D10_MESSAGE_ID_VSSETSAMPLERS_TOO_MANY_SAMPLERS = Ord(D3D10_MESSAGE_ID_VSSETSAMPLERS_NOT_SUPPORTED) + 1,
        D3D10_MESSAGE_ID_PSSETSAMPLERS_TOO_MANY_SAMPLERS = Ord(D3D10_MESSAGE_ID_VSSETSAMPLERS_TOO_MANY_SAMPLERS) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_NO_ARRAYS = Ord(D3D10_MESSAGE_ID_PSSETSAMPLERS_TOO_MANY_SAMPLERS) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_NO_VB_AND_IB_BIND = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_NO_ARRAYS) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_NO_TEXTURE_1D = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_NO_VB_AND_IB_BIND) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_DIMENSION_OUT_OF_RANGE = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_NO_TEXTURE_1D) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_NOT_BINDABLE_AS_SHADER_RESOURCE = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_DIMENSION_OUT_OF_RANGE) + 1,
        D3D10_MESSAGE_ID_OMSETRENDERTARGETS_TOO_MANY_RENDER_TARGETS = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_NOT_BINDABLE_AS_SHADER_RESOURCE) + 1,
        D3D10_MESSAGE_ID_OMSETRENDERTARGETS_NO_DIFFERING_BIT_DEPTHS = Ord(D3D10_MESSAGE_ID_OMSETRENDERTARGETS_TOO_MANY_RENDER_TARGETS) + 1,
        D3D10_MESSAGE_ID_IASETVERTEXBUFFERS_BAD_BUFFER_INDEX = Ord(D3D10_MESSAGE_ID_OMSETRENDERTARGETS_NO_DIFFERING_BIT_DEPTHS) + 1,
        D3D10_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_TOO_MANY_VIEWPORTS = Ord(D3D10_MESSAGE_ID_IASETVERTEXBUFFERS_BAD_BUFFER_INDEX) + 1,
        D3D10_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_ADJACENCY_UNSUPPORTED = Ord(D3D10_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_TOO_MANY_VIEWPORTS) + 1,
        D3D10_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_TOO_MANY_SCISSORS = Ord(D3D10_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_ADJACENCY_UNSUPPORTED) + 1,
        D3D10_MESSAGE_ID_COPYRESOURCE_ONLY_TEXTURE_2D_WITHIN_GPU_MEMORY = Ord(D3D10_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_TOO_MANY_SCISSORS) + 1,
        D3D10_MESSAGE_ID_COPYRESOURCE_NO_TEXTURE_3D_READBACK = Ord(D3D10_MESSAGE_ID_COPYRESOURCE_ONLY_TEXTURE_2D_WITHIN_GPU_MEMORY) + 1,
        D3D10_MESSAGE_ID_COPYRESOURCE_NO_TEXTURE_ONLY_READBACK = Ord(D3D10_MESSAGE_ID_COPYRESOURCE_NO_TEXTURE_3D_READBACK) + 1,
        D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_UNSUPPORTED_FORMAT = Ord(D3D10_MESSAGE_ID_COPYRESOURCE_NO_TEXTURE_ONLY_READBACK) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_ALPHA_TO_COVERAGE = Ord(D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_UNSUPPORTED_FORMAT) + 1,
        D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_DepthClipEnable_MUST_BE_TRUE = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_ALPHA_TO_COVERAGE) + 1,
        D3D10_MESSAGE_ID_DRAWINDEXED_STARTINDEXLOCATION_MUST_BE_POSITIVE = Ord(D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_DepthClipEnable_MUST_BE_TRUE) + 1,
        D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_MUST_USE_LOWEST_LOD = Ord(D3D10_MESSAGE_ID_DRAWINDEXED_STARTINDEXLOCATION_MUST_BE_POSITIVE) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_MINLOD_MUST_NOT_BE_FRACTIONAL = Ord(D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_MUST_USE_LOWEST_LOD) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_MAXLOD_MUST_BE_FLT_MAX = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_MINLOD_MUST_NOT_BE_FRACTIONAL) + 1,
        D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_FIRSTARRAYSLICE_MUST_BE_ZERO = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_MAXLOD_MUST_BE_FLT_MAX) + 1,
        D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_CUBES_MUST_HAVE_6_SIDES = Ord(D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_FIRSTARRAYSLICE_MUST_BE_ZERO) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_NOT_BINDABLE_AS_RENDER_TARGET = Ord(D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_CUBES_MUST_HAVE_6_SIDES) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_NO_DWORD_INDEX_BUFFER = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_NOT_BINDABLE_AS_RENDER_TARGET) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_MSAA_PRECLUDES_SHADER_RESOURCE = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_NO_DWORD_INDEX_BUFFER) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_PRESENTATION_PRECLUDES_SHADER_RESOURCE = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_MSAA_PRECLUDES_SHADER_RESOURCE) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_INDEPENDENT_BLEND_ENABLE = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_PRESENTATION_PRECLUDES_SHADER_RESOURCE) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_INDEPENDENT_WRITE_MASKS = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_INDEPENDENT_BLEND_ENABLE) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_NO_STREAM_OUT = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_INDEPENDENT_WRITE_MASKS) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_ONLY_VB_IB_FOR_BUFFERS = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_NO_STREAM_OUT) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_NO_AUTOGEN_FOR_VOLUMES = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_ONLY_VB_IB_FOR_BUFFERS) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_DXGI_FORMAT_R8G8B8A8_CANNOT_BE_SHARED = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_NO_AUTOGEN_FOR_VOLUMES) + 1,
        D3D10_MESSAGE_ID_VSSHADERRESOURCES_NOT_SUPPORTED = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_DXGI_FORMAT_R8G8B8A8_CANNOT_BE_SHARED) + 1,
        D3D10_MESSAGE_ID_GEOMETRY_SHADER_NOT_SUPPORTED = Ord(D3D10_MESSAGE_ID_VSSHADERRESOURCES_NOT_SUPPORTED) + 1,
        D3D10_MESSAGE_ID_STREAM_OUT_NOT_SUPPORTED = Ord(D3D10_MESSAGE_ID_GEOMETRY_SHADER_NOT_SUPPORTED) + 1,
        D3D10_MESSAGE_ID_TEXT_FILTER_NOT_SUPPORTED = Ord(D3D10_MESSAGE_ID_STREAM_OUT_NOT_SUPPORTED) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_SEPARATE_ALPHA_BLEND = Ord(D3D10_MESSAGE_ID_TEXT_FILTER_NOT_SUPPORTED) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_MRT_BLEND = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_SEPARATE_ALPHA_BLEND) + 1,
        D3D10_MESSAGE_ID_CREATEBLENDSTATE_OPERATION_NOT_SUPPORTED = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_MRT_BLEND) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_NO_MIRRORONCE = Ord(D3D10_MESSAGE_ID_CREATEBLENDSTATE_OPERATION_NOT_SUPPORTED) + 1,
        D3D10_MESSAGE_ID_DRAWINSTANCED_NOT_SUPPORTED = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_NO_MIRRORONCE) + 1,
        D3D10_MESSAGE_ID_DRAWINDEXEDINSTANCED_NOT_SUPPORTED_BELOW_9_3 = Ord(D3D10_MESSAGE_ID_DRAWINSTANCED_NOT_SUPPORTED) + 1,
        D3D10_MESSAGE_ID_DRAWINDEXED_POINTLIST_UNSUPPORTED = Ord(D3D10_MESSAGE_ID_DRAWINDEXEDINSTANCED_NOT_SUPPORTED_BELOW_9_3) + 1,
        D3D10_MESSAGE_ID_SETBLENDSTATE_SAMPLE_MASK_CANNOT_BE_ZERO = Ord(D3D10_MESSAGE_ID_DRAWINDEXED_POINTLIST_UNSUPPORTED) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_DIMENSION_EXCEEDS_FEATURE_LEVEL_DEFINITION = Ord(D3D10_MESSAGE_ID_SETBLENDSTATE_SAMPLE_MASK_CANNOT_BE_ZERO) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_ONLY_SINGLE_MIP_LEVEL_DEPTH_STENCIL_SUPPORTED = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_DIMENSION_EXCEEDS_FEATURE_LEVEL_DEFINITION) + 1,
        D3D10_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_NEGATIVESCISSOR = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_ONLY_SINGLE_MIP_LEVEL_DEPTH_STENCIL_SUPPORTED) + 1,
        D3D10_MESSAGE_ID_SLOT_ZERO_MUST_BE_D3D10_INPUT_PER_VERTEX_DATA = Ord(D3D10_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_NEGATIVESCISSOR) + 1,
        D3D10_MESSAGE_ID_CREATERESOURCE_NON_POW_2_MIPMAP = Ord(D3D10_MESSAGE_ID_SLOT_ZERO_MUST_BE_D3D10_INPUT_PER_VERTEX_DATA) + 1,
        D3D10_MESSAGE_ID_CREATESAMPLERSTATE_BORDER_NOT_SUPPORTED = Ord(D3D10_MESSAGE_ID_CREATERESOURCE_NON_POW_2_MIPMAP) + 1,
        D3D10_MESSAGE_ID_OMSETRENDERTARGETS_NO_SRGB_MRT = Ord(D3D10_MESSAGE_ID_CREATESAMPLERSTATE_BORDER_NOT_SUPPORTED) + 1,
        D3D10_MESSAGE_ID_COPYRESOURCE_NO_3D_MISMATCHED_UPDATES = Ord(D3D10_MESSAGE_ID_OMSETRENDERTARGETS_NO_SRGB_MRT) + 1,
        D3D10_MESSAGE_ID_D3D10L9_MESSAGES_END = Ord(D3D10_MESSAGE_ID_COPYRESOURCE_NO_3D_MISMATCHED_UPDATES) + 1);

    PD3D10_MESSAGE_ID = ^TD3D10_MESSAGE_ID;


    TD3D10_MESSAGE = record
        Category: TD3D10_MESSAGE_CATEGORY;
        Severity: TD3D10_MESSAGE_SEVERITY;
        ID: TD3D10_MESSAGE_ID; (* [annotation] *)
        {_Field_size_(DescriptionByteLength)  } pDescription: pchar;
        DescriptionByteLength: SIZE_T;
    end;
    PD3D10_MESSAGE = ^TD3D10_MESSAGE;


    TD3D10_INFO_QUEUE_FILTER_DESC = record
        NumCategories: UINT; (* [annotation] *)
        {_Field_size_(NumCategories)  } pCategoryList: PD3D10_MESSAGE_CATEGORY;
        NumSeverities: UINT; (* [annotation] *)
        {_Field_size_(NumSeverities)  } pSeverityList: PD3D10_MESSAGE_SEVERITY;
        NumIDs: UINT; (* [annotation] *)
        {_Field_size_(NumIDs)  } pIDList: PD3D10_MESSAGE_ID;
    end;
    PD3D10_INFO_QUEUE_FILTER_DESC = ^TD3D10_INFO_QUEUE_FILTER_DESC;


    TD3D10_INFO_QUEUE_FILTER = record
        AllowList: TD3D10_INFO_QUEUE_FILTER_DESC;
        DenyList: TD3D10_INFO_QUEUE_FILTER_DESC;
    end;
    PD3D10_INFO_QUEUE_FILTER = ^TD3D10_INFO_QUEUE_FILTER;


    ID3D10InfoQueue = interface(IUnknown)
        ['{1b940b17-2642-4d1f-ab1f-b99bad0c395f}']
        function SetMessageCountLimit(
        {_In_  } MessageCountLimit: uint64): HRESULT; stdcall;

        procedure ClearStoredMessages(); stdcall;

        function GetMessage(
        {_In_  } MessageIndex: uint64;
        {_Out_writes_bytes_opt_(*pMessageByteLength)  } pMessage: PD3D10_MESSAGE;
        {_Inout_  } pMessageByteLength: PSIZE_T): HRESULT; stdcall;

        function GetNumMessagesAllowedByStorageFilter(): uint64; stdcall;

        function GetNumMessagesDeniedByStorageFilter(): uint64; stdcall;

        function GetNumStoredMessages(): uint64; stdcall;

        function GetNumStoredMessagesAllowedByRetrievalFilter(): uint64; stdcall;

        function GetNumMessagesDiscardedByMessageCountLimit(): uint64; stdcall;

        function GetMessageCountLimit(): uint64; stdcall;

        function AddStorageFilterEntries(
        {_In_  } pFilter: PD3D10_INFO_QUEUE_FILTER): HRESULT; stdcall;

        function GetStorageFilter(
        {_Out_writes_bytes_opt_(*pFilterByteLength)  } pFilter: PD3D10_INFO_QUEUE_FILTER;
        {_Inout_  } pFilterByteLength: PSIZE_T): HRESULT; stdcall;

        procedure ClearStorageFilter(); stdcall;

        function PushEmptyStorageFilter(): HRESULT; stdcall;

        function PushCopyOfStorageFilter(): HRESULT; stdcall;

        function PushStorageFilter(
        {_In_  } pFilter: PD3D10_INFO_QUEUE_FILTER): HRESULT; stdcall;

        procedure PopStorageFilter(); stdcall;

        function GetStorageFilterStackSize(): UINT; stdcall;

        function AddRetrievalFilterEntries(
        {_In_  } pFilter: PD3D10_INFO_QUEUE_FILTER): HRESULT; stdcall;

        function GetRetrievalFilter(
        {_Out_writes_bytes_opt_(*pFilterByteLength)  } pFilter: PD3D10_INFO_QUEUE_FILTER;
        {_Inout_  } pFilterByteLength: PSIZE_T): HRESULT; stdcall;

        procedure ClearRetrievalFilter(); stdcall;

        function PushEmptyRetrievalFilter(): HRESULT; stdcall;

        function PushCopyOfRetrievalFilter(): HRESULT; stdcall;

        function PushRetrievalFilter(
        {_In_  } pFilter: PD3D10_INFO_QUEUE_FILTER): HRESULT; stdcall;

        procedure PopRetrievalFilter(); stdcall;

        function GetRetrievalFilterStackSize(): UINT; stdcall;

        function AddMessage(
        {_In_  } Category: TD3D10_MESSAGE_CATEGORY;
        {_In_  } Severity: TD3D10_MESSAGE_SEVERITY;
        {_In_  } ID: TD3D10_MESSAGE_ID;
        {_In_  } pDescription: LPCSTR): HRESULT; stdcall;

        function AddApplicationMessage(
        {_In_  } Severity: TD3D10_MESSAGE_SEVERITY;
        {_In_  } pDescription: LPCSTR): HRESULT; stdcall;

        function SetBreakOnCategory(
        {_In_  } Category: TD3D10_MESSAGE_CATEGORY;
        {_In_  } bEnable: boolean): HRESULT; stdcall;

        function SetBreakOnSeverity(
        {_In_  } Severity: TD3D10_MESSAGE_SEVERITY;
        {_In_  } bEnable: boolean): HRESULT; stdcall;

        function SetBreakOnID(
        {_In_  } ID: TD3D10_MESSAGE_ID;
        {_In_  } bEnable: boolean): HRESULT; stdcall;

        function GetBreakOnCategory(
        {_In_  } Category: TD3D10_MESSAGE_CATEGORY): boolean; stdcall;

        function GetBreakOnSeverity(
        {_In_  } Severity: TD3D10_MESSAGE_SEVERITY): boolean; stdcall;

        function GetBreakOnID(
        {_In_  } ID: TD3D10_MESSAGE_ID): boolean; stdcall;

        procedure SetMuteDebugOutput(
        {_In_  } bMute: boolean); stdcall;

        function GetMuteDebugOutput(): boolean; stdcall;

    end;


implementation

end.
