{ **************************************************************************
    FreePascal/Delphi DirectX 12 Header Files

    Copyright (C) 2013-2025 Norbert Sonnleitner

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
************************************************************************** }

{ **************************************************************************
   Additional Copyright (C) for this modul:
   
   Copyright (c) Microsoft Corporation.  All rights reserved.
   This file is automatically generated.  Please do not edit it directly.
   
   This unit consists of the following header files
   File name: D2D1Effects_1.h
   Header version: 10.0.26100.6584
   
  ************************************************************************** }
unit DX12.D2D1Effects_1;

{$IFDEF FPC}
{$mode ObjFPC}{$H+}
{$ENDIF}

interface

uses
    Windows, Classes, SysUtils, DX12.D2D1Effects;

    {$Z4}

const

    // Built in effect CLSIDs
    CLSID_D2D1YCbCr: TGUID = '{99503CC1-66C7-45C9-A875-8AD8A7914401}';

type

    /// The enumeration of the YCbCr effect's top level properties.
    /// Effect description: An effect that takes a Y plane as input 0 and a CbCr plane
    /// as input 1 and outputs RGBA.  The CbCr plane can be chroma subsampled.  Useful
    /// for JPEG color conversion.
    TD2D1_YCBCR_PROP = (
        /// Property Name: "ChromaSubsampling"
        /// Property Type: D2D1_YCBCR_CHROMA_SUBSAMPLING
        D2D1_YCBCR_PROP_CHROMA_SUBSAMPLING = 0,
        /// Property Name: "TransformMatrix"
        /// Property Type: D2D1_MATRIX_3X2_F
        D2D1_YCBCR_PROP_TRANSFORM_MATRIX = 1,
        /// Property Name: "InterpolationMode"
        /// Property Type: D2D1_YCBCR_INTERPOLATION_MODE
        D2D1_YCBCR_PROP_INTERPOLATION_MODE = 2,
        D2D1_YCBCR_PROP_FORCE_DWORD = longint($ffffffff)
        );

    PD2D1_YCBCR_PROP = ^TD2D1_YCBCR_PROP;

    TD2D1_YCBCR_CHROMA_SUBSAMPLING = (
        D2D1_YCBCR_CHROMA_SUBSAMPLING_AUTO = 0,
        D2D1_YCBCR_CHROMA_SUBSAMPLING_420 = 1,
        D2D1_YCBCR_CHROMA_SUBSAMPLING_422 = 2,
        D2D1_YCBCR_CHROMA_SUBSAMPLING_444 = 3,
        D2D1_YCBCR_CHROMA_SUBSAMPLING_440 = 4,
        D2D1_YCBCR_CHROMA_SUBSAMPLING_FORCE_DWORD = longint($ffffffff)
        );

    PD2D1_YCBCR_CHROMA_SUBSAMPLING = ^TD2D1_YCBCR_CHROMA_SUBSAMPLING;

    TD2D1_YCBCR_INTERPOLATION_MODE = (
        D2D1_YCBCR_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0,
        D2D1_YCBCR_INTERPOLATION_MODE_LINEAR = 1,
        D2D1_YCBCR_INTERPOLATION_MODE_CUBIC = 2,
        D2D1_YCBCR_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR = 3,
        D2D1_YCBCR_INTERPOLATION_MODE_ANISOTROPIC = 4,
        D2D1_YCBCR_INTERPOLATION_MODE_HIGH_QUALITY_CUBIC = 5,
        D2D1_YCBCR_INTERPOLATION_MODE_FORCE_DWORD = longint($ffffffff)
        );

    PD2D1_YCBCR_INTERPOLATION_MODE = ^TD2D1_YCBCR_INTERPOLATION_MODE;



implementation


end.
