{ **************************************************************************
    FreePascal/Delphi DirectX 12 Header Files

    Copyright (C) 2013-2025 Norbert Sonnleitner

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
************************************************************************** }

{ **************************************************************************
   Additional Copyright (C) for this modul:
   
   Copyright (c) Microsoft Corporation.  All rights reserved. 
   This file is automatically generated.  Please do not edit it directly.
   
   This unit consists of the following header files
   File name: D2D1EffectAuthor_1.h
   Header version: 10.0.26100.6584
   
  ************************************************************************** }
unit DX12.D2D1Effectauthor_1;

{$IFDEF FPC}
{$mode ObjFPC}{$H+}
{$ENDIF}

interface

uses
    Windows, Classes, SysUtils, DX12.D2D1_3, DX12.D2D1Effectauthor,
    DX12.DXGICommon,
    DX12.D2D1_1;

    {$Z4}

const

    IID_ID2D1EffectContext1: TGUID = '{84ab595a-fc81-4546-bacd-e8ef4d8abe7a}';
    IID_ID2D1EffectContext2: TGUID = '{577ad2a0-9fc7-4dda-8b18-dab810140052}';

type

    /// The internal context handed to effect authors to create transforms from effects
    /// and any other operation tied to context which is not useful to the application
    /// facing API.
    ID2D1EffectContext1 = interface(ID2D1EffectContext)
        ['{84ab595a-fc81-4546-bacd-e8ef4d8abe7a}']
        /// Creates a 3D lookup table for mapping a 3-channel input to a 3-channel output.
        /// The table data must be provided in 4-channel format.
        function CreateLookupTable3D(precision: TD2D1_BUFFER_PRECISION;
        {_In_reads_(3) } extents: PUINT32;
        {_In_reads_(dataCount) } Data: pbyte; dataCount: uint32;
        {_In_reads_(2) } strides: PUINT32;
        {_COM_Outptr_ }  out lookupTable: ID2D1LookupTable3D): HRESULT; stdcall;

    end;


    /// The internal context handed to effect authors to create transforms from effects
    /// and any other operation tied to context which is not useful to the application
    /// facing API.
    ID2D1EffectContext2 = interface(ID2D1EffectContext1)
        ['{577ad2a0-9fc7-4dda-8b18-dab810140052}']
        /// Creates a color context from a DXGI color space type. It is only valid to use
        /// this with the Color Management Effect in 'Best' mode.
        function CreateColorContextFromDxgiColorSpace(colorSpace: TDXGI_COLOR_SPACE_TYPE;
        {_COM_Outptr_ }  out colorContext: ID2D1ColorContext1): HRESULT; stdcall;

        /// Creates a color context from a simple color profile. It is only valid to use
        /// this with the Color Management Effect in 'Best' mode.
        function CreateColorContextFromSimpleColorProfile(
        {_In_ } simpleProfile: PD2D1_SIMPLE_COLOR_PROFILE;
        {_COM_Outptr_ }  out colorContext: ID2D1ColorContext1): HRESULT; stdcall;

    end;



implementation


end.
