{ **************************************************************************
    FreePascal/Delphi DirectX 12 Header Files

    Copyright (C) 2013-2025 Norbert Sonnleitner

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
************************************************************************** }

{ **************************************************************************
   Additional Copyright (C) for this modul:

   Copyright (c) Microsoft Corporation.  All rights reserved.
   This file is automatically generated.  Please do not edit it directly.

   This unit consists of the following header files
   File name: d2d1.h
   This are the defines frome D2D1 to avoid circular reference between D2D1 and DWrite
   Header version: 10.0.26100.6584

  ************************************************************************** }

unit DX12.D2D1DWrite;

{$IFDEF FPC}
{$mode delphiunicode}{$H+}
{$modeswitch ADVANCEDRECORDS}
{$modeswitch TypeHelpers}
{$ENDIF}

interface

uses
  Windows, Classes, SysUtils,
  DX12.DCommon;

  {$Z4}

type

  /// Indicates whether the given figure is filled or hollow.
    TD2D1_FIGURE_BEGIN = (
        D2D1_FIGURE_BEGIN_FILLED = 0,
        D2D1_FIGURE_BEGIN_HOLLOW = 1,
        D2D1_FIGURE_BEGIN_FORCE_DWORD = longint($ffffffff));

    PD2D1_FIGURE_BEGIN = ^TD2D1_FIGURE_BEGIN;

    /// Indicates whether the figure is open or closed on its end point.
    TD2D1_FIGURE_END = (
        D2D1_FIGURE_END_OPEN = 0,
        D2D1_FIGURE_END_CLOSED = 1,
        D2D1_FIGURE_END_FORCE_DWORD = longint($ffffffff));

    PD2D1_FIGURE_END = ^TD2D1_FIGURE_END;       
	
	 /// Describes a cubic bezier in a path.
    TD2D1_BEZIER_SEGMENT = record
        point1: TD2D1_POINT_2F;
        point2: TD2D1_POINT_2F;
        point3: TD2D1_POINT_2F;
    end;
    PD2D1_BEZIER_SEGMENT = ^TD2D1_BEZIER_SEGMENT;   
	
	 /// Indicates whether the given segment should be stroked, or, if the join between
    /// this segment and the previous one should be smooth.
    TD2D1_PATH_SEGMENT = (
        D2D1_PATH_SEGMENT_NONE = $00000000,
        D2D1_PATH_SEGMENT_FORCE_UNSTROKED = $00000001,
        D2D1_PATH_SEGMENT_FORCE_ROUND_LINE_JOIN = $00000002,
        D2D1_PATH_SEGMENT_FORCE_DWORD = longint($ffffffff));

    PD2D1_PATH_SEGMENT = ^TD2D1_PATH_SEGMENT;  

/// Specifies how the intersecting areas of geometries or figures are combined to
    /// form the area of the composite geometry.
    TD2D1_FILL_MODE = (
        D2D1_FILL_MODE_ALTERNATE = 0,
        D2D1_FILL_MODE_WINDING = 1,
        D2D1_FILL_MODE_FORCE_DWORD = longint($ffffffff));

    PD2D1_FILL_MODE = ^TD2D1_FILL_MODE;   


  /// Describes a geometric path that does not contain quadratic bezier curves or
    /// arcs.
    ID2D1SimplifiedGeometrySink = interface(IUnknown)
        ['{2cd9069e-12e2-11dc-9fed-001143a055f9}']
        procedure SetFillMode(fillMode: TD2D1_FILL_MODE); stdcall;

        procedure SetSegmentFlags(vertexFlags: TD2D1_PATH_SEGMENT); stdcall;

        procedure BeginFigure(startPoint: TD2D1_POINT_2F; figureBegin: TD2D1_FIGURE_BEGIN); stdcall;

        procedure AddLines(
        {_In_reads_(pointsCount) } points: PD2D1_POINT_2F; pointsCount: uint32); stdcall;

        procedure AddBeziers(
        {_In_reads_(beziersCount) } beziers: PD2D1_BEZIER_SEGMENT; beziersCount: uint32); stdcall;

        procedure EndFigure(figureEnd: TD2D1_FIGURE_END); stdcall;

        function Close(): HRESULT; stdcall;

    end;

implementation

end.

