unit DX12.DCommon;

{$IFDEF FPC}
{$MODE delphi}{$H+}
{$ENDIF}

interface

{$Z4}

uses
    Windows, Classes, SysUtils, DX12.DXGI;

type
    TDWRITE_MEASURING_MODE = (DWRITE_MEASURING_MODE_NATURAL, DWRITE_MEASURING_MODE_GDI_CLASSIC, DWRITE_MEASURING_MODE_GDI_NATURAL);

    TD2D1_ALPHA_MODE = (D2D1_ALPHA_MODE_UNKNOWN = 0, D2D1_ALPHA_MODE_PREMULTIPLIED = 1, D2D1_ALPHA_MODE_STRAIGHT = 2, D2D1_ALPHA_MODE_IGNORE = 3,
        D2D1_ALPHA_MODE_FORCE_DWORD = $FFFFFFFF);

    TD2D1_PIXEL_FORMAT = record
        format: TDXGI_FORMAT;
        alphaMode: TD2D1_ALPHA_MODE;
    end;

    PD2D1_PIXEL_FORMAT = ^TD2D1_PIXEL_FORMAT;

implementation

end.
