{ **************************************************************************
    FreePascal/Delphi DirectX 12 Header Files

    Copyright (C) 2013-2025 Norbert Sonnleitner

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
************************************************************************** }

{ **************************************************************************
   Additional Copyright (C) for this modul:

   Copyright (C) Microsoft Corporation.
   Licensed under the MIT license

   This unit consists of the following header files
   File name: SDKMesh.h
   DirectX 12 Toolkit version: 2025.12.27

  ************************************************************************** }

//--------------------------------------------------------------------------------------
// File: SDKMesh.h

// SDKMESH format is generated by the legacy DirectX SDK's Content Exporter and
// originally rendered by the DXUT helper class SDKMesh

// http://go.microsoft.com/fwlink/?LinkId=226208

// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// http://go.microsoft.com/fwlink/?LinkId=248929
// http://go.microsoft.com/fwlink/?LinkID=615561
//--------------------------------------------------------------------------------------
unit DX12TK.SDKMesh;

{$mode ObjFPC}{$H+}

interface

uses
    Windows, Classes, SysUtils,
    DX12.DXGIFormat,
    DirectX.Math;

const

    //--------------------------------------------------------------------------------------
    // Hard Defines for the various structures
    //--------------------------------------------------------------------------------------
    SDKMESH_FILE_VERSION = 101;
    SDKMESH_FILE_VERSION_V2 = 200;

    MAX_VERTEX_ELEMENTS = 32;
    MAX_VERTEX_STREAMS = 16;
    MAX_FRAME_NAME = 100;
    MAX_MESH_NAME = 100;
    MAX_SUBSET_NAME = 100;
    MAX_MATERIAL_NAME = 100;
    MAX_TEXTURE_NAME = MAX_PATH;
    MAX_MATERIAL_PATH = MAX_PATH;
    INVALID_FRAME = uint32(-1);
    INVALID_MESH = uint32(-1);
    INVALID_MATERIAL = uint32(-1);
    INVALID_SUBSET = uint32(-1);
    INVALID_ANIMATION_DATA = uint32(-1);

type

    // .SDKMESH files

    // SDKMESH_HEADER
    // SDKMESH_VERTEX_BUFFER_HEADER header->VertexStreamHeadersOffset
    // SDKMESH_INDEX_BUFFER_HEADER  header->IndexStreamHeadersOffset
    // SDKMESH_MESH                 header->MeshDataOffset
    // SDKMESH_SUBSET               header->SubsetDataOffset
    // SDKMESH_FRAME                header->FrameDataOffset
    // SDKMESH_MATERIAL             header->MaterialDataOffset
    // [header->NonBufferDataSize]
    // { [ header->NumVertexBuffers]
    //      VB data
    // }
    // { [ header->NumIndexBuffers]
    //      IB data
    // }


    // .SDDKANIM files

    // SDKANIMATION_FILE_HEADER
    // uint8_t[] - Length of fileheader->AnimationDataSize

    // .SDKMESH uses Direct3D 9 decls, but only a subset of these is ever generated by the legacy DirectX SDK Content Exporter

    // D3DDECLUSAGE_POSITION / D3DDECLTYPE_FLOAT3
    // (D3DDECLUSAGE_BLENDWEIGHT / D3DDECLTYPE_UBYTE4N
    // D3DDECLUSAGE_BLENDINDICES / D3DDECLTYPE_UBYTE4)?
    // (D3DDECLUSAGE_NORMAL / D3DDECLTYPE_FLOAT3, D3DDECLTYPE_FLOAT16_4, D3DDECLTYPE_SHORT4N, D3DDECLTYPE_UBYTE4N, or D3DDECLTYPE_DEC3N)?
    // (D3DDECLUSAGE_COLOR / D3DDECLTYPE_D3DCOLOR)?
    // (D3DDECLUSAGE_TEXCOORD / D3DDECLTYPE_FLOAT1, D3DDECLTYPE_FLOAT2 or D3DDECLTYPE_FLOAT16_2, D3DDECLTYPE_FLOAT3 or D3DDECLTYPE_FLOAT16_4, D3DDECLTYPE_FLOAT4 or D3DDECLTYPE_FLOAT16_4)*
    // (D3DDECLUSAGE_TANGENT / same as D3DDECLUSAGE_NORMAL)?
    // (D3DDECLUSAGE_BINORMAL / same as D3DDECLUSAGE_NORMAL)?


    TD3DDECLUSAGE = (
        D3DDECLUSAGE_POSITION = 0,
        D3DDECLUSAGE_BLENDWEIGHT = 1,
        D3DDECLUSAGE_BLENDINDICES = 2,
        D3DDECLUSAGE_NORMAL = 3,
        D3DDECLUSAGE_TEXCOORD = 5,
        D3DDECLUSAGE_TANGENT = 6,
        D3DDECLUSAGE_BINORMAL = 7,
        D3DDECLUSAGE_COLOR = 10);

    PD3DDECLUSAGE = ^TD3DDECLUSAGE;


    TD3DDECLTYPE = (
        D3DDECLTYPE_FLOAT1 = 0,
        // 1D float expanded to (value, 0., 0., 1.)
        D3DDECLTYPE_FLOAT2 = 1,
        // 2D float expanded to (value, value, 0., 1.)
        D3DDECLTYPE_FLOAT3 = 2,
        // 3D float expanded to (value, value, value, 1.)
        D3DDECLTYPE_FLOAT4 = 3,
        // 4D float
        D3DDECLTYPE_D3DCOLOR = 4,
        // 4D packed unsigned bytes mapped to 0. to 1. range
        // Input is in D3DCOLOR format (ARGB) expanded to (R, G, B, A)
        D3DDECLTYPE_UBYTE4 = 5,
        // 4D unsigned uint8_t
        D3DDECLTYPE_UBYTE4N = 8,
        // Each of 4 bytes is normalized by dividing to 255.0
        D3DDECLTYPE_SHORT4N = 10,
        // 4D signed short normalized (v[0]/32767.0,v[1]/32767.0,v[2]/32767.0,v[3]/32767.0)
        D3DDECLTYPE_DEC3N = 14,
        // 3D signed normalized (v[0]/511.0, v[1]/511.0, v[2]/511.0, 1.)
        // Note: There is no equivalent to D3DDECLTYPE_DEC3N (14) as a DXGI_FORMAT
        D3DDECLTYPE_FLOAT16_2 = 15,
        // Two 16-bit floating point values, expanded to (value, value, 0, 1)
        D3DDECLTYPE_FLOAT16_4 = 16,
        // Four 16-bit floating point values
        D3DDECLTYPE_UNUSED = 17,
        // When the type field in a decl is unused.
        // These are extensions for DXGI-based versions of Direct3D
        D3DDECLTYPE_DXGI_R10G10B10A2_UNORM = 32 + Ord(DXGI_FORMAT_R10G10B10A2_UNORM),
        D3DDECLTYPE_DXGI_R11G11B10_FLOAT = 32 + Ord(DXGI_FORMAT_R11G11B10_FLOAT),
        D3DDECLTYPE_DXGI_R8G8B8A8_SNORM = 32 + Ord(DXGI_FORMAT_R8G8B8A8_SNORM));

    PD3DDECLTYPE = ^TD3DDECLTYPE;

    {$PACKRECORDS 4}

    TD3DVERTEXELEMENT9 = record
        Stream: uint16; // Stream index
        Offset: uint16; // Offset in the stream in bytes
        DataType: uint8; // Data type
        Method: uint8; // Processing method
        Usage: uint8; // Semantics
        UsageIndex: uint8; // Semantic index
    end;
    PD3DVERTEXELEMENT9 = ^TD3DVERTEXELEMENT9;


    {$PACKRECORDS DEFAULT}


    //--------------------------------------------------------------------------------------
    // Enumerated Types.
    //--------------------------------------------------------------------------------------
    TSDKMESH_PRIMITIVE_TYPE = (
        PT_TRIANGLE_LIST = 0,
        PT_TRIANGLE_STRIP,
        PT_LINE_LIST,
        PT_LINE_STRIP,
        PT_POINT_LIST,
        PT_TRIANGLE_LIST_ADJ,
        PT_TRIANGLE_STRIP_ADJ,
        PT_LINE_LIST_ADJ,
        PT_LINE_STRIP_ADJ,
        PT_QUAD_PATCH_LIST,
        PT_TRIANGLE_PATCH_LIST);

    PSDKMESH_PRIMITIVE_TYPE = ^TSDKMESH_PRIMITIVE_TYPE;


    TSDKMESH_INDEX_TYPE = (
        IT_16BIT = 0,
        IT_32BIT);

    PSDKMESH_INDEX_TYPE = ^TSDKMESH_INDEX_TYPE;


    TFRAME_TRANSFORM_TYPE = (
        FTT_RELATIVE = 0,
        FTT_ABSOLUTE// This is not currently used but is here to support absolute transformations in the future
        );

    PFRAME_TRANSFORM_TYPE = ^TFRAME_TRANSFORM_TYPE;


    //--------------------------------------------------------------------------------------
    // Structures.
    //--------------------------------------------------------------------------------------
    {$PACKRECORDS 8}

    TSDKMESH_HEADER = record
        //Basic Info and sizes
        Version: uint32;
        IsBigEndian: uint8;
        HeaderSize: uint64;
        NonBufferDataSize: uint64;
        BufferDataSize: uint64;
        //Stats
        NumVertexBuffers: uint32;
        NumIndexBuffers: uint32;
        NumMeshes: uint32;
        NumTotalSubsets: uint32;
        NumFrames: uint32;
        NumMaterials: uint32;
        //Offsets to Data
        VertexStreamHeadersOffset: uint64;
        IndexStreamHeadersOffset: uint64;
        MeshDataOffset: uint64;
        SubsetDataOffset: uint64;
        FrameDataOffset: uint64;
        MaterialDataOffset: uint64;
    end;
    PSDKMESH_HEADER = ^TSDKMESH_HEADER;


    TSDKMESH_VERTEX_BUFFER_HEADER = record
        NumVertices: uint64;
        SizeBytes: uint64;
        StrideBytes: uint64;
        Decl: array [0..MAX_VERTEX_ELEMENTS - 1] of TD3DVERTEXELEMENT9;
        DataOffset: uint64;
    end;
    PSDKMESH_VERTEX_BUFFER_HEADER = ^TSDKMESH_VERTEX_BUFFER_HEADER;


    TSDKMESH_INDEX_BUFFER_HEADER = record
        NumIndices: uint64;
        SizeBytes: uint64;
        IndexType: uint32;
        DataOffset: uint64;
    end;
    PSDKMESH_INDEX_BUFFER_HEADER = ^TSDKMESH_INDEX_BUFFER_HEADER;


    TSDKMESH_MESH = record
        Name: array [0..MAX_MESH_NAME - 1] of char;
        NumVertexBuffers: uint8;
        VertexBuffers: array [0..MAX_VERTEX_STREAMS - 1] of uint32;
        IndexBuffer: uint32;
        NumSubsets: uint32;
        NumFrameInfluences: uint32; //aka bones
        BoundingBoxCenter: TXMFLOAT3;
        BoundingBoxExtents: TXMFLOAT3;
        case integer of
            0: (
                SubsetOffset: uint64;
                FrameInfluenceOffset: uint64;
            );
            1: (
                pSubsets: PINT32;
                pFrameInfluences: Puint32;
            );
    end;
    PSDKMESH_MESH = ^TSDKMESH_MESH;


    TSDKMESH_SUBSET = record
        Name: array [0..MAX_SUBSET_NAME - 1] of char;
        MaterialID: uint32;
        PrimitiveType: uint32;
        IndexStart: uint64;
        IndexCount: uint64;
        VertexStart: uint64;
        VertexCount: uint64;
    end;
    PSDKMESH_SUBSET = ^TSDKMESH_SUBSET;


    TSDKMESH_FRAME = record
        Name: array [0..MAX_FRAME_NAME - 1] of char;
        Mesh: uint32;
        ParentFrame: uint32;
        ChildFrame: uint32;
        SiblingFrame: uint32;
        Matrix: TXMFLOAT4X4;
        AnimationDataIndex: uint32; //Used to index which set of keyframes transforms this frame
    end;
    PSDKMESH_FRAME = ^TSDKMESH_FRAME;


    TSDKMESH_MATERIAL = record
        Name: array [0..MAX_MATERIAL_NAME - 1] of char;
        // Use MaterialInstancePath
        MaterialInstancePath: array [0..MAX_MATERIAL_PATH - 1] of char;
        // Or fall back to d3d8-type materials
        DiffuseTexture: array [0..MAX_TEXTURE_NAME - 1] of char;
        NormalTexture: array [0..MAX_TEXTURE_NAME - 1] of char;
        SpecularTexture: array [0..MAX_TEXTURE_NAME - 1] of char;
        Diffuse: TXMFLOAT4;
        Ambient: TXMFLOAT4;
        Specular: TXMFLOAT4;
        Emissive: TXMFLOAT4;
        Power: single;
        Force64_1: uint64;
        Force64_2: uint64;
        Force64_3: uint64;
        Force64_4: uint64;
        Force64_5: uint64;
        Force64_6: uint64;
    end;
    PSDKMESH_MATERIAL = ^TSDKMESH_MATERIAL;


    TSDKMESH_MATERIAL_V2 = record
        Name: array [0..MAX_MATERIAL_NAME - 1] of char;
        // PBR materials
        RMATexture: array [0..MAX_TEXTURE_NAME - 1] of char;
        AlbedoTexture: array [0..MAX_TEXTURE_NAME - 1] of char;
        NormalTexture: array [0..MAX_TEXTURE_NAME - 1] of char;
        EmissiveTexture: array [0..MAX_TEXTURE_NAME - 1] of char;
        Alpha: single;
        Reserved: array [0..60 - 1] of char;
        Force64_1: uint64;
        Force64_2: uint64;
        Force64_3: uint64;
        Force64_4: uint64;
        Force64_5: uint64;
        Force64_6: uint64;
    end;
    PSDKMESH_MATERIAL_V2 = ^TSDKMESH_MATERIAL_V2;


    TSDKANIMATION_FILE_HEADER = record
        Version: uint32;
        IsBigEndian: uint8;
        FrameTransformType: uint32;
        NumFrames: uint32;
        NumAnimationKeys: uint32;
        AnimationFPS: uint32;
        AnimationDataSize: uint64;
        AnimationDataOffset: uint64;
    end;
    PSDKANIMATION_FILE_HEADER = ^TSDKANIMATION_FILE_HEADER;


    TSDKANIMATION_DATA = record
        Translation: TXMFLOAT3;
        Orientation: TXMFLOAT4;
        Scaling: TXMFLOAT3;
    end;
    PSDKANIMATION_DATA = ^TSDKANIMATION_DATA;


    TSDKANIMATION_FRAME_DATA = record
        FrameName: array [0..MAX_FRAME_NAME - 1] of char;
        DataOffset: uint64;
    end;
    PSDKANIMATION_FRAME_DATA = ^TSDKANIMATION_FRAME_DATA;


    {$PACKRECORDS DEFAULT}


    {$if sizeof(TD3DVERTEXELEMENT9) <> 8}{$error Direct3D9 Decl structure size incorrect}{$endif}
    {$if sizeof(TSDKMESH_HEADER)<> 104}{$error SDK Mesh structure size incorrect}{$endif}
    {$if sizeof(TSDKMESH_VERTEX_BUFFER_HEADER) <> 288}{$error SDK Mesh structure size incorrect}{$endif}
    {$if sizeof(TSDKMESH_INDEX_BUFFER_HEADER) <> 32}{$error SDK Mesh structure size incorrect}{$endif}
    {$if sizeof(TSDKMESH_MESH) <> 224}{$error SDK Mesh structure size incorrect}{$endif}
    {$if sizeof(TSDKMESH_SUBSET) <> 144}{$error SDK Mesh structure size incorrect}{$endif}
    {$if sizeof(TSDKMESH_FRAME) <> 184}{$error SDK Mesh structure size incorrect}{$endif}
    {$if sizeof(TSDKMESH_MATERIAL) <> 1256}{$error SDK Mesh structure size incorrect}{$endif}
    {$if sizeof(TSDKMESH_MATERIAL_V2) <> sizeof(TSDKMESH_MATERIAL)}{$error SDK Mesh structure size incorrect}{$endif}
    {$if sizeof(TSDKANIMATION_FILE_HEADER) <> 40}{$error SDK Mesh structure size incorrect}{$endif}
    {$if sizeof(TSDKANIMATION_DATA) <> 40}{$error SDK Mesh structure size incorrect}{$endif}
    {$if sizeof(TSDKANIMATION_FRAME_DATA) <> 112}{$error SDK Mesh structure size incorrect}{$endif}

implementation

end.
